// vue-demo/src/components/pages/MessagesV3Compose.vue
<template>
  <div>
    <div class="row">

      <!-- Messages sidebox -->
      <div class="messages-sidebox col mb-4">

        <b-btn variant="primary mt-md-4" :block="true">Compose</b-btn>
        <hr class="border-light my-4">

        <!-- Mail boxes -->
        <a v-for="(box, boxId) in mailBoxes" :key="box.title" href="javascript:void(0)" class="d-flex justify-content-between align-items-center py-2" :class="{'font-weight-bold text-dark': currentMailBox === boxId, 'text-muted': currentMailBox !== boxId}">
          <div><i :class="box.icon"></i> &nbsp; {{box.title}}</div>
          <div class="badge badge-primary" v-if="box.count">{{box.count}}</div>
        </a>
        <!-- / Mail boxes -->

        <hr class="border-light my-4">

        <!-- Labels -->
        <h6 class="text-tiny font-weight-bold">LABELS</h6>
        <a v-for="label in labels" :key="label.title" href="javascript:void(0)" class="d-block text-muted py-1">
          <span class="badge badge-dot" :class="`badge-${label.color}`"></span> &nbsp; {{label.title}}
        </a>
        <!-- / Labels -->

      </div>
      <!-- / Messages sidebox -->

      <div class="col">
        <b-card header="New message" header-tag="h4" header-class="py-4">

          <b-form-group label="To:">
            <b-input v-model="messageData.to" />
          </b-form-group>

          <b-form-group label="Subject:">
            <b-input v-model="messageData.subject" />
          </b-form-group>

          <b-form-group class="mt-4">
            <quill-editor v-model="messageData.content" :options="editorOptions" v-if="!isIE10Mode" />
            <!-- Fallback -->
            <b-textarea v-model="messageData.content" style="height: 400px" v-if="isIE10Mode" />
          </b-form-group>

          <!-- Footer -->
          <div class="text-right mt-4">
            <b-btn variant="primary ml-2"><i class="ion ion-ios-paper-plane"></i>&nbsp; Send</b-btn>
            <b-btn variant="default ml-2"><i class="ion ion-md-save"></i>&nbsp; Save</b-btn>
            <b-btn variant="default ml-2">Cancel</b-btn>
          </div>
          <!-- / Footer -->

        </b-card>
      </div>
    </div><!-- / .row -->
  </div>
</template>

<style src="@/vendor/libs/vue-quill-editor/typography.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/editor.scss" lang="scss"></style>

<!-- Page -->
<style src="@/vendor/styles/pages/messages.scss" lang="scss"></style>

<style lang="scss">
  .ql-container.ql-snow {
    height: 400px;
  }
</style>

<script>
export default {
  name: 'pages-messages-v3-compose',
  metaInfo: {
    title: 'Compose message v3 - Pages'
  },
  components: {
    quillEditor: () => import('vue-quill-editor/dist/vue-quill-editor').then(m => m.quillEditor).catch(() => {})
  },
  data: () => ({
    // Mail boxes
    currentMailBox: null,
    mailBoxes: {
      inbox: { title: 'Inbox', icon: 'ion ion-ios-filing', count: 15 },
      sent: { title: 'Sent', icon: 'ion ion ion-ios-mail' },
      drafts: { title: 'Drafts', icon: 'ion ion ion-md-create' },
      spam: { title: 'Spam', icon: 'ion ion ion-md-folder-open' },
      trash: { title: 'Trash', icon: 'ion ion ion-md-trash' }
    },

    // Labels
    labels: {
      clients: { title: 'Clients', color: 'success' },
      important: { title: 'Important', color: 'danger' },
      social: { title: 'Social', color: 'info' },
      other: { title: 'Other', color: 'warning' }
    },

    // Message
    messageData: {
      to: '',
      subject: '',
      content: ''
    },

    // Editor
    editorOptions: {
      modules: {
        toolbar: [
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }, { 'font': [] }, { 'size': [] }],
          ['bold', 'italic', 'underline', 'strike'],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'script': 'sub' }, { 'script': 'super' }],
          ['blockquote', 'code-block'],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
          [{ 'direction': 'rtl' }, { 'align': [] }],
          ['link', 'image', 'video'],
          ['clean']
        ]
      }
    }
  }),
  mounted () {
    this.layoutHelpers.setCollapsed(true, false)
  }
}
</script>

// angular-demo/src/app/+pages/messages-v3-compose/messages-v3-compose.component.ts
import { Component, AfterViewInit } from '@angular/core';
import { AppService } from '../../app.service';
import { LayoutService } from '../../layout/layout.service';

@Component({
  selector: 'app-messages-v3-compose',
  templateUrl: './messages-v3-compose.component.html',
  styleUrls: [
    '../../../vendor/libs/quill/typography.scss',
    '../../../vendor/libs/quill/editor.scss',
    '../../../vendor/styles/pages/messages.scss',
    './messages-v3-compose.component.scss'
  ]
})
export class MessagesV3ComposeComponent implements AfterViewInit {
  isIE10: boolean;

  constructor(private appService: AppService, private layoutService: LayoutService) {
    this.appService.pageTitle = 'Compose message v3 - Pages';
    this.isIE10 = this.appService.isIE10;
  }

  // Mail boxes
  currentMailBox = null;
  mailBoxes = {
    inbox: { title: 'Inbox', icon: 'ion ion-ios-filing', count: 15 },
    sent: { title: 'Sent', icon: 'ion ion ion-ios-mail' },
    drafts: { title: 'Drafts', icon: 'ion ion ion-md-create' },
    spam: { title: 'Spam', icon: 'ion ion ion-md-folder-open' },
    trash: { title: 'Trash', icon: 'ion ion ion-md-trash' }
  };

  // Labels
  labels = {
    clients: { title: 'Clients', color: 'success' },
    important: { title: 'Important', color: 'danger' },
    social: { title: 'Social', color: 'info' },
    other: { title: 'Other', color: 'warning' }
  };

  // Message
  messageData = {
    to: '',
    subject: '',
    content: ''
  };

  ngAfterViewInit() {
    setTimeout(() => this.layoutService.setCollapsed(true, false));
  }

  objectKeys(o) {
    return Object.keys(o);
  }

}

<div class="row">

  <!-- Messages sidebox -->
  <div class="messages-sidebox col mb-4">

    <button type="button" class="btn btn-primary btn-block mt-md-4">Compose</button>
    <hr class="border-light my-4">

    <!-- Mail boxes -->
    <a *ngFor="let boxId of objectKeys(mailBoxes)" href="javascript:void(0)" class="d-flex justify-content-between align-items-center py-2" [ngClass]="{'font-weight-bold text-dark': currentMailBox === boxId, 'text-muted': currentMailBox !== boxId}">
      <div><i [ngClass]="mailBoxes[boxId].icon"></i> &nbsp; {{mailBoxes[boxId].title}}</div>
      <div class="badge badge-primary" *ngIf="mailBoxes[boxId].count">{{mailBoxes[boxId].count}}</div>
    </a>
    <!-- / Mail boxes -->

    <hr class="border-light my-4">

    <!-- Labels -->
    <h6 class="text-tiny font-weight-bold">LABELS</h6>
    <a *ngFor="let labelId of objectKeys(labels)" href="javascript:void(0)" class="d-block text-muted py-1">
      <span class="badge badge-dot" [ngClass]="'badge-' + labels[labelId].color"></span> &nbsp; {{labels[labelId].title}}
    </a>
    <!-- / Labels -->

  </div>
  <!-- / Messages sidebox -->

  <div class="col">

    <!-- Messages list -->
    <div class="card">
      <h4 class="card-header py-4">New message</h4>

      <div class="card-body">

        <div class="form-group">
          <label class="form-label">To:</label>
          <input [(ngModel)]="messageData.to" type="text" class="form-control">
        </div>

        <div class="form-group">
          <label class="form-label">Subject:</label>
          <input [(ngModel)]="messageData.subject" type="text" class="form-control">
        </div>

        <div class="form-group mt-4">
          <quill-editor [(ngModel)]="messageData.content" placeholder="Type something" *ngIf="!isIE10">
            <div quill-editor-toolbar>
              <span class="ql-formats">
                <select class="ql-font"></select>
                <select class="ql-size"></select>
              </span>
              <span class="ql-formats">
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-strike"></button>
              </span>
              <span class="ql-formats">
                <select class="ql-color"></select>
                <select class="ql-background"></select>
              </span>
              <span class="ql-formats">
                <button class="ql-script" value="sub"></button>
                <button class="ql-script" value="super"></button>
              </span>
              <span class="ql-formats">
                <button class="ql-header" value="1"></button>
                <button class="ql-header" value="2"></button>
                <button class="ql-blockquote"></button>
                <button class="ql-code-block"></button>
              </span>
              <span class="ql-formats">
                <button class="ql-list" value="ordered"></button>
                <button class="ql-list" value="bullet"></button>
                <button class="ql-indent" value="-1"></button>
                <button class="ql-indent" value="+1"></button>
              </span>
              <span class="ql-formats">
                <button class="ql-direction" value="rtl"></button>
                <select class="ql-align"></select>
              </span>
              <span class="ql-formats">
                <button class="ql-link"></button>
                <button class="ql-image"></button>
                <button class="ql-video"></button>
              </span>
              <span class="ql-formats">
                <button class="ql-clean"></button>
              </span>
            </div>
          </quill-editor>

          <!-- Fallback -->
          <textarea [(ngModel)]="messageData.content" class="form-control" style="height: 400px" *ngIf="isIE10"></textarea>
        </div>

        <div class="text-right mt-4">
          <button type="button" class="btn btn-primary ml-2"><i class="ion ion-ios-paper-plane"></i>&nbsp; Send</button>
          <button type="button" class="btn btn-default ml-2"><i class="ion ion-md-save"></i>&nbsp; Save</button>
          <button type="button" class="btn btn-default ml-2">Cancel</button>
        </div>

      </div>

    </div>
    <!-- / Messages list -->

  </div>
</div>
