// vue-demo/src/components/forms/Switchers.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Forms /</span> Switchers
    </h4>

    <b-card no-body class="mb-4">
      <b-card-body>
        <label class="switcher">
          <input type="checkbox" class="switcher-input">
          <span class="switcher-indicator">
            <span class="switcher-yes"></span>
            <span class="switcher-no"></span>
          </span>
          <span class="switcher-label">Default</span>
        </label>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">With icon</div>

        <label class="switcher">
          <input type="checkbox" class="switcher-input">
          <span class="switcher-indicator">
            <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
            <span class="switcher-no"><span class="ion ion-md-close"></span></span>
          </span>
          <span class="switcher-label">With icon</span>
        </label>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Square</div>

        <label class="switcher switcher-square">
          <input type="checkbox" class="switcher-input">
          <span class="switcher-indicator">
            <span class="switcher-yes"></span>
            <span class="switcher-no"></span>
          </span>
          <span class="switcher-label">Square</span>
        </label>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Sizes</div>

        <div class="demo-vertical-spacing-sm">
          <label class="switcher switcher-sm">
            <input type="checkbox" class="switcher-input">
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Small</span>
          </label>

          <br>

          <label class="switcher switcher-lg">
            <input type="checkbox" class="switcher-input">
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Large</span>
          </label>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Variations</div>

        <div class="demo-inline-spacing">
          <label class="switcher switcher-success">
            <input type="checkbox" class="switcher-input" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Success</span>
          </label>

          <label class="switcher switcher-info">
            <input type="checkbox" class="switcher-input" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Info</span>
          </label>

          <label class="switcher switcher-warning">
            <input type="checkbox" class="switcher-input" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Warning</span>
          </label>

          <label class="switcher switcher-danger">
            <input type="checkbox" class="switcher-input" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Danger</span>
          </label>

          <label class="switcher switcher-secondary">
            <input type="checkbox" class="switcher-input" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Secondary</span>
          </label>

          <label class="switcher switcher-dark">
            <input type="checkbox" class="switcher-input" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"><span class="ion ion-md-checkmark"></span></span>
              <span class="switcher-no"><span class="ion ion-md-close"></span></span>
            </span>
            <span class="switcher-label">Dark</span>
          </label>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Disabled</div>

        <div class="demo-vertical-spacing-sm">
          <div>
            <label class="switcher">
              <input type="checkbox" class="switcher-input" disabled>
              <span class="switcher-indicator">
                <span class="switcher-yes"></span>
                <span class="switcher-no"></span>
              </span>
              <span class="switcher-label">Default - OFF</span>
            </label>

            <label class="switcher">
              <input type="checkbox" class="switcher-input" checked disabled>
              <span class="switcher-indicator">
                <span class="switcher-yes"></span>
                <span class="switcher-no"></span>
              </span>
              <span class="switcher-label">Default - ON</span>
            </label>
          </div>

          <fieldset disabled>
            <label class="switcher switcher-success">
              <input type="checkbox" class="switcher-input" checked>
              <span class="switcher-indicator">
                <span class="switcher-yes"></span>
                <span class="switcher-no"></span>
              </span>
              <span class="switcher-label">Success - ON</span>
            </label>
          </fieldset>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Validation states</div>

        <div class="demo-vertical-spacing-sm">
          <div class="form-group">
            <label class="switcher">
              <input type="checkbox" class="switcher-input is-valid" checked>
              <span class="switcher-indicator">
                <span class="switcher-yes"></span>
                <span class="switcher-no"></span>
              </span>
              <span class="switcher-label">Valid</span>
            </label>
          </div>

          <div class="form-group has-error">
            <label class="switcher">
              <input type="checkbox" class="switcher-input is-invalid" checked>
              <span class="switcher-indicator">
                <span class="switcher-yes"></span>
                <span class="switcher-no"></span>
              </span>
              <span class="switcher-label">Invalid</span>
            </label>
          </div>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Stacked</div>

        <div class="switchers-stacked">
          <label class="switcher">
            <input type="radio" class="switcher-input" name="switchers-stacked-radio" checked>
            <span class="switcher-indicator">
              <span class="switcher-yes"></span>
              <span class="switcher-no"></span>
            </span>
            <span class="switcher-label">Option 1</span>
          </label>

          <label class="switcher">
            <input type="radio" class="switcher-input" name="switchers-stacked-radio">
            <span class="switcher-indicator">
              <span class="switcher-yes"></span>
              <span class="switcher-no"></span>
            </span>
            <span class="switcher-label">Option 2</span>
          </label>

          <label class="switcher">
            <input type="radio" class="switcher-input" name="switchers-stacked-radio">
            <span class="switcher-indicator">
              <span class="switcher-yes"></span>
              <span class="switcher-no"></span>
            </span>
            <span class="switcher-label">Option 3</span>
          </label>
        </div>
      </b-card-body>
    </b-card>

  </div>
</template>

<script>
export default {
  name: 'forms-switchers',
  metaInfo: {
    title: 'Switchers - Forms'
  }
}
</script>

// angular-demo/src/app/+forms/switchers/switchers.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'forms-switchers', // tslint:disable-line
  templateUrl: './switchers.component.html'
})
export class SwitchersComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Switchers - Forms';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Forms /</span> Switchers
</h4>

<div class="card mb-4">
  <div class="card-body">
    <label class="switcher">
      <input type="checkbox" class="switcher-input">
      <span class="switcher-indicator">
        <span class="switcher-yes"></span>
        <span class="switcher-no"></span>
      </span>
      <span class="switcher-label">Default</span>
    </label>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">With icon</div>

    <label class="switcher">
      <input type="checkbox" class="switcher-input">
      <span class="switcher-indicator">
        <span class="switcher-yes">
          <span class="ion ion-md-checkmark"></span>
        </span>
        <span class="switcher-no">
          <span class="ion ion-md-close"></span>
        </span>
      </span>
      <span class="switcher-label">With icon</span>
    </label>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Square</div>

    <label class="switcher switcher-square">
      <input type="checkbox" class="switcher-input">
      <span class="switcher-indicator">
        <span class="switcher-yes"></span>
        <span class="switcher-no"></span>
      </span>
      <span class="switcher-label">Square</span>
    </label>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Sizes</div>

    <div class="demo-vertical-spacing-sm">
      <label class="switcher switcher-sm">
        <input type="checkbox" class="switcher-input">
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Small</span>
      </label>

      <br>

      <label class="switcher switcher-lg">
        <input type="checkbox" class="switcher-input">
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Large</span>
      </label>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Variations</div>

    <div class="demo-inline-spacing">
      <label class="switcher switcher-success">
        <input type="checkbox" class="switcher-input" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Success</span>
      </label>

      <label class="switcher switcher-info">
        <input type="checkbox" class="switcher-input" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Info</span>
      </label>

      <label class="switcher switcher-warning">
        <input type="checkbox" class="switcher-input" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Warning</span>
      </label>

      <label class="switcher switcher-danger">
        <input type="checkbox" class="switcher-input" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Danger</span>
      </label>

      <label class="switcher switcher-secondary">
        <input type="checkbox" class="switcher-input" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Secondary</span>
      </label>

      <label class="switcher switcher-dark">
        <input type="checkbox" class="switcher-input" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes">
            <span class="ion ion-md-checkmark"></span>
          </span>
          <span class="switcher-no">
            <span class="ion ion-md-close"></span>
          </span>
        </span>
        <span class="switcher-label">Dark</span>
      </label>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Disabled</div>

    <div class="demo-vertical-spacing-sm">
      <div>
        <label class="switcher">
          <input type="checkbox" class="switcher-input" disabled>
          <span class="switcher-indicator">
            <span class="switcher-yes"></span>
            <span class="switcher-no"></span>
          </span>
          <span class="switcher-label">Default - OFF</span>
        </label>

        <label class="switcher">
          <input type="checkbox" class="switcher-input" checked disabled>
          <span class="switcher-indicator">
            <span class="switcher-yes"></span>
            <span class="switcher-no"></span>
          </span>
          <span class="switcher-label">Default - ON</span>
        </label>
      </div>

      <fieldset disabled>
        <label class="switcher switcher-success">
          <input type="checkbox" class="switcher-input" checked>
          <span class="switcher-indicator">
            <span class="switcher-yes"></span>
            <span class="switcher-no"></span>
          </span>
          <span class="switcher-label">Success - ON</span>
        </label>
      </fieldset>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Validation states</div>

    <div class="form-group">
      <label class="switcher">
        <input type="checkbox" class="switcher-input is-valid" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes"></span>
          <span class="switcher-no"></span>
        </span>
        <span class="switcher-label">Valid</span>
      </label>
    </div>

    <div class="form-group has-error">
      <label class="switcher">
        <input type="checkbox" class="switcher-input is-invalid" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes"></span>
          <span class="switcher-no"></span>
        </span>
        <span class="switcher-label">Invalid</span>
      </label>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Stacked</div>

    <div class="switchers-stacked">
      <label class="switcher">
        <input type="radio" class="switcher-input" name="switchers-stacked-radio" checked>
        <span class="switcher-indicator">
          <span class="switcher-yes"></span>
          <span class="switcher-no"></span>
        </span>
        <span class="switcher-label">Option 1</span>
      </label>

      <label class="switcher">
        <input type="radio" class="switcher-input" name="switchers-stacked-radio">
        <span class="switcher-indicator">
          <span class="switcher-yes"></span>
          <span class="switcher-no"></span>
        </span>
        <span class="switcher-label">Option 2</span>
      </label>

      <label class="switcher">
        <input type="radio" class="switcher-input" name="switchers-stacked-radio">
        <span class="switcher-indicator">
          <span class="switcher-yes"></span>
          <span class="switcher-no"></span>
        </span>
        <span class="switcher-label">Option 3</span>
      </label>
    </div>
  </div>
</div>
