// angular-starter/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { AppService } from '../app.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent {

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Home';
  }

}

<h4 class="font-weight-bold py-3 mb-4">Home</h4>
<p>This page is an example of basic layout. For more options use <strong>Angular starter template generator</strong> in the docs.</p>
<p><button class="btn btn-primary btn-lg">Button</button></p>

// vue-starter-cli2-deprecated/src/components/Home.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">Home</h4>
    <p>This page is an example of basic layout. For more options use <strong>Vue starter template generator</strong> in the docs.</p>
    <p><button class="btn btn-primary btn-lg">Button</button></p>
  </div>
</template>

<script>
export default {
  name: 'home',
  metaInfo: {
    title: 'Home'
  }
}
</script>
