// angular-demo/src/app/+forms/extras/extras.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

import * as textMaskAddons from 'text-mask-addons/dist/textMaskAddons';

@Component({
  selector: 'forms-extras', // tslint:disable-line
  templateUrl: './extras.component.html'
})
export class ExtrasComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Extras - Forms';
  }

  //
  // angular2-text-mask
  //

  phoneModel = '';
  phoneMaskOptions = {
    mask: ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]
  };

  numberModel = '';
  numberMaskOptions = {
    mask: textMaskAddons.createNumberMask({
      prefix: '$'
    })
  };

  emailModel = '';
  emailMaskOptions = {
    mask: textMaskAddons.emailMask
  };

  dateModel = '';
  dateMaskOptions = {
    mask: [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/],
    pipe: textMaskAddons.createAutoCorrectedDatePipe('mm/dd/yyyy')
  };

  //
  // ng2-password-strength-bar
  //

  password = '';
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Forms /</span> Extras
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    ng-autosize
  </h6>
  <div class="card-body">
    <textarea class="form-control" autosize rows="3">Hello, this is an example of Autosize in Angular2 with a Min Height.</textarea>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    angular2-text-mask
  </h6>
  <div class="card-body demo-vertical-spacing">
    <input type="text" class="form-control" placeholder="(___) ___-____"
      [(ngModel)]="phoneModel"
      [textMask]="phoneMaskOptions">

    <input type="text" class="form-control" placeholder="$"
      [(ngModel)]="numberModel"
      [textMask]="numberMaskOptions">

    <input type="text" class="form-control" placeholder=" @ ."
      [(ngModel)]="emailModel"
      [textMask]="emailMaskOptions">

    <input type="text" class="form-control" placeholder="__/__/____"
      [(ngModel)]="dateModel"
      [textMask]="dateMaskOptions">
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    ng2-password-strength-bar
  </h6>
  <div class="card-body">
    <input [(ngModel)]="password" type="password" class="form-control" placeholder="Enter password">
    <ng2-password-strength-bar [passwordToCheck]="password"></ng2-password-strength-bar>
  </div>
</div>

// vue-demo/src/components/forms/Extras.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Forms /</span> Extras
    </h4>

    <b-card header="Vue Text Mask" header-tag="h6" class="mb-4">
      <div class="demo-vertical-spacing-sm">
        <masked-input type="text" class="form-control" placeholder="Phone"
          v-model="phone"
          :mask="phoneMask" />

        <masked-input type="text" class="form-control" placeholder="Number"
          v-model="number"
          :mask="numberMask" />

        <masked-input type="text" class="form-control" placeholder="Email"
          v-model="email"
          :mask="emailMask" />

        <masked-input type="text" class="form-control" placeholder="Date"
          v-model="date"
          :mask="dateMask"
          :pipe="datePipe" />
      </div>
    </b-card>

    <b-card header="Vue Password Strength Meter" header-tag="h6" class="mb-4">
      <password
        v-model="password"
        defaultClass="form-control" />
    </b-card>

  </div>
</template>

<style src="@/vendor/libs/vue-password-strength-meter/vue-password-strength-meter.scss" lang="scss"></style>

<script>
import MaskedInput from 'vue-text-mask'
import * as textMaskAddons from 'text-mask-addons/dist/textMaskAddons'
import Password from 'vue-password-strength-meter'

export default {
  name: 'forms-extras',
  metaInfo: {
    title: 'Extras - Forms'
  },
  components: {
    MaskedInput,
    Password
  },
  data: () => ({
    //
    // Vue Text Mask
    //

    phone: '',
    phoneMask: ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],

    number: '',
    numberMask: textMaskAddons.createNumberMask({
      prefix: '$'
    }),

    email: '',
    emailMask: textMaskAddons.emailMask,

    date: '',
    dateMask: [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/],
    datePipe: textMaskAddons.createAutoCorrectedDatePipe('mm/dd/yyyy'),

    //
    // Vue Password Strength Meter
    //

    password: null
  })
}
</script>
