// vue-demo-cli2-deprecated/src/components/layouts/Layout2Example.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Layouts /</span> Layout 2
    </h4>

    <div class="layout-example-block layout-example-block-2">
      <code>.layout-wrapper.layout-2</code>

      <div class="layout-example-block">
        <code>.layout-inner</code>

        <div class="layout-example-block-inner">

          <div class="layout-example-block layout-example-block-sidenav">
            <code>.layout-sidenav</code>
          </div>

          <div class="layout-example-block layout-example-block-container">
            <code>.layout-container</code>

            <div class="layout-example-block layout-example-block-navbar">
              <code>.layout-navbar</code>
            </div>

            <div class="layout-example-block layout-example-block-content">
              <code>.layout-content</code>

              <div class="layout-example-block bg-white">
                <code class="text-dark">.container-fluid</code>
              </div>
            </div>

          </div>

        </div>

      </div>

    </div>
  </div>
</template>

<script>
export default {
  name: 'layout-2-example',
  metaInfo: {
    title: 'Layout 2 - Layouts'
  }
}
</script>

// angular-demo/src/app/+layouts/layout-2-example/layout-2-example.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'layout-2-example', // tslint:disable-line
  templateUrl: './layout-2-example.component.html'
})
export class Layout2ExampleComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Layout 2 - Layouts';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Layouts /</span> Layout 2
</h4>

<div class="layout-example-block layout-example-block-2">
  <code>.layout-wrapper.layout-2</code>

  <div class="layout-example-block">
    <code>.layout-inner</code>

    <div class="layout-example-block-inner">

      <div class="layout-example-block layout-example-block-sidenav">
        <code>.layout-sidenav</code>
      </div>

      <div class="layout-example-block layout-example-block-container">
        <code>.layout-container</code>

        <div class="layout-example-block layout-example-block-navbar">
          <code>.layout-navbar</code>
        </div>

        <div class="layout-example-block layout-example-block-content">
          <code>.layout-content</code>

          <div class="layout-example-block bg-white">
            <code class="text-dark">.container-fluid</code>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>
