// vue-demo/src/components/pages/TicketsList.vue
<template>
  <div>
    <h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
      <div>Tickets</div>
      <b-btn variant="primary btn-round" class="d-block"><span class="ion ion-md-add"></span>&nbsp; Create ticket</b-btn>
    </h4>

    <!-- Filters -->
    <div class="ui-bordered px-4 pt-4 mb-4">
      <div class="form-row align-items-center">
        <div class="col-md mb-4">
          <label class="form-label">Priority</label>
          <b-select v-model="filterPriority" :options="['Any', 'High', 'Medium', 'Low']" />
        </div>
        <div class="col-md mb-4">
          <label class="form-label">Status</label>
          <b-select v-model="filterStatus" :options="['Any', 'Open', 'Reopened', 'In progress', 'Closed']" />
        </div>
        <div class="col-md mb-4">
          <label class="form-label">Created date</label>
          <flat-pickr v-model="filterCreatedDate" :config="{ altInput: true, animate: !isRTL, dateFormat: 'm/d/Y', altFormat: 'm/d/Y', mode: 'range' }" :placeholder="!isIEMode ? 'Any' : null" />
        </div>
        <div class="col-md col-xl-2 mb-4">
          <label class="form-label d-none d-md-block">&nbsp;</label>
          <b-btn variant="secondary" :block="true">Show</b-btn>
        </div>
      </div>
    </div>
    <!-- / Filters -->

    <b-card no-body>

      <!-- Table controls -->
      <b-card-body>

        <div class="row">
          <div class="col">
            Per page: &nbsp;
            <b-select size="sm" v-model="perPage" :options="[10, 20, 30, 40, 50]" class="d-inline-block w-auto" />
          </div>
          <div class="col">
            <b-input size="sm" placeholder="Search..." class="d-inline-block w-auto float-sm-right" @input="filter($event)" />
          </div>
        </div>

      </b-card-body>
      <!-- / Table controls -->

      <!-- Table -->
      <hr class="border-light m-0">
      <div class="table-responsive">

        <b-table
          :items="ticketsData"
          :fields="fields"
          :sort-by.sync="sortBy"
          :sort-desc.sync="sortDesc"
          :striped="true"
          :bordered="true"
          :current-page="currentPage"
          :per-page="perPage"
          class="card-table">

          <template slot="priority" slot-scope="data">
            <b-dropdown :variant="priorityDropdownVariant(data.item.priority)" :right="isRTL">
              <template slot="button-content">
                <span v-if="data.item.priority === 1">High</span>
                <span v-if="data.item.priority === 2">Medium</span>
                <span v-if="data.item.priority === 3">Low</span>
              </template>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.priority === 1">High</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.priority === 2">Medium</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.priority === 3">Low</b-dropdown-item>
            </b-dropdown>
          </template>

          <template slot="status" slot-scope="data">
            <b-dropdown variant="outline-secondary btn-xs md-btn-flat" :right="isRTL">
              <template slot="button-content">
                <span v-if="data.item.status === 1">Open</span>
                <span v-if="data.item.status === 2">Reopened</span>
                <span v-if="data.item.status === 3">In progress</span>
                <span v-if="data.item.status === 4">Closed</span>
              </template>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.status === 1">Open</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.status === 2">Reopened</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.status === 3">In progress</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)" :active="data.item.status === 4">Closed</b-dropdown-item>
            </b-dropdown>
          </template>

          <template slot="actions" slot-scope="data">
            <b-btn variant="default btn-xs icon-btn md-btn-flat" v-b-tooltip.hover title="Edit"><i class="ion ion-md-create"></i></b-btn>
            <b-btn variant="default btn-xs icon-btn md-btn-flat" v-b-tooltip.hover title="Remove"><i class="ion ion-md-close"></i></b-btn>
          </template>
        </b-table>

      </div>

      <!-- Pagination -->
      <b-card-body class="pt-0 pb-3">

        <div class="row">
          <div class="col-sm text-sm-left text-center pt-3">
            <span class="text-muted" v-if="totalItems">Page {{ currentPage }} of {{ totalPages }}</span>
          </div>
          <div class="col-sm pt-3">
            <b-pagination class="justify-content-center justify-content-sm-end m-0"
              v-if="totalItems"
              v-model="currentPage"
              :total-rows="totalItems"
              :per-page="perPage"
              size="sm" />
          </div>
        </div>

      </b-card-body>
      <!-- / Pagination -->

    </b-card>
  </div>
</template>

<style src="@/vendor/libs/vue-flatpickr-component/vue-flatpickr-component.scss" lang="scss"></style>

<script>
import flatPickr from 'vue-flatpickr-component'

export default {
  name: 'pages-ticket-list',
  metaInfo: {
    title: 'Ticket list - Pages'
  },
  components: {
    flatPickr
  },
  data: () => ({
    // Options
    dataUrl: 'json/pages_tickets_list.json',
    searchKeys: ['id', 'subject'],
    sortBy: 'id',
    sortDesc: false,
    perPage: 10,

    fields: [
      { key: 'id', sortable: true, thClass: 'text-nowrap', tdClass: 'align-middle py-3' },
      { key: 'subject', sortable: true, thClass: 'text-nowrap', thStyle: 'min-width: 300px', tdClass: 'align-middle py-3' },
      { key: 'created_at', sortable: true, thClass: 'text-nowrap', tdClass: 'align-middle py-3' },
      { key: 'last_update', sortable: true, thClass: 'text-nowrap', tdClass: 'align-middle py-3' },
      { key: 'priority', sortable: true, thClass: 'text-nowrap', tdClass: 'align-middle py-3' },
      { key: 'status', sortable: true, thClass: 'text-nowrap', tdClass: 'align-middle py-3' },
      { key: 'actions', label: ' ', thClass: 'text-nowrap', tdClass: 'text-nowrap align-middle text-center py-3' }
    ],

    // Filters
    filterPriority: 'Any',
    filterStatus: 'Any',
    filterCreatedDate: null,

    ticketsData: [],
    originalTicketsData: [],

    currentPage: 1
  }),

  computed: {
    totalItems () {
      return this.ticketsData.length
    },
    totalPages () {
      return Math.ceil(this.totalItems / this.perPage)
    }
  },

  methods: {
    filter (value) {
      const val = value.toLowerCase()
      const filtered = this.originalTicketsData.filter(d => {
        return Object.keys(d)
          .filter(k => this.searchKeys.includes(k))
          .map(k => String(d[k]))
          .join('|')
          .toLowerCase()
          .indexOf(val) !== -1 || !val
      })
      this.ticketsData = filtered
    },

    priorityDropdownVariant (priority) {
      let variant

      if (priority === 1) variant = 'danger'
      if (priority === 2) variant = 'success'
      if (priority === 3) variant = 'warning'

      return `${variant} btn-xs md-btn-flat`
    }
  },

  created () {
    const req = new XMLHttpRequest()
    req.open('GET', `${this.baseUrl}${this.dataUrl}`)

    req.onload = () => {
      const data = JSON.parse(req.response)
      this.ticketsData = data
      this.originalTicketsData = data.slice(0)
    }

    req.send()
  }
}
</script>

// angular-demo/src/app/+pages/tickets-list/tickets-list.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-tickets-list',
  templateUrl: './tickets-list.component.html'
})
export class TicketsListComponent {
  isRTL: boolean;

  constructor(private http: HttpClient, private appService: AppService) {
    this.appService.pageTitle = 'User list - Pages';
    this.isRTL = appService.isRTL;
    this.loadData();
  }

  // Filters

  filterPriority = 'Any';
  filterStatus = 'Any';
  filterCreatedDate = [null, null];

  // Table

  // Options
  dataUrl = 'assets/json/pages_tickets_list.json';
  searchKeys = ['id', 'subject'];
  sortBy = 'id';
  sortDesc = true;
  perPage = 10;

  filterVal = '';
  currentPage = 1;
  totalItems = 0;

  ticketsData: Object[] = [];
  originalTicketsData: Object[] = [];

  priorityDropdownVariant (priority) {
    if (priority === 1) { return 'btn-danger'; }
    if (priority === 2) { return 'btn-success'; }
    if (priority === 3) { return 'btn-warning'; }
  }

  loadData() {
    this.http.get(this.dataUrl)
      .subscribe((data: any) => {
        this.originalTicketsData = data.slice(0);
        this.update();
      });
  }

  get totalPages() {
    return Math.ceil(this.totalItems / this.perPage);
  }

  update() {
    const data = this.filter(this.originalTicketsData);

    this.totalItems = data.length;

    this.sort(data);
    this.ticketsData = this.paginate(data);
  }

  filter(data) {
    const filter = this.filterVal.toLowerCase();
    return !filter ?
      data.slice(0) :
      data.filter(d => {
        return Object.keys(d)
          .filter(k => this.searchKeys.includes(k))
          .map(k => String(d[k]))
          .join('|')
          .toLowerCase()
          .indexOf(filter) !== -1 || !filter;
      });
  }

  sort(data) {
    data.sort((a: any, b: any) => {
      a = typeof(a[this.sortBy]) === 'string' ? a[this.sortBy].toUpperCase() : a[this.sortBy];
      b = typeof(b[this.sortBy]) === 'string' ? b[this.sortBy].toUpperCase() : b[this.sortBy];

      if (a < b) { return this.sortDesc ? 1 : -1; }
      if (a > b) { return this.sortDesc ? -1 : 1; }
      return 0;
    });
  }

  paginate(data) {
    const perPage = parseInt(String(this.perPage), 10);
    const offset = (this.currentPage - 1) * perPage;

    return data.slice(offset, offset + perPage);
  }

  setSort(key) {
    if (this.sortBy !== key) {
      this.sortBy = key;
      this.sortDesc = false;
    } else {
      this.sortDesc = !this.sortDesc;
    }

    this.currentPage = 1;
    this.update();
  }
}

<h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
  <div>Tickets</div>
  <button type="button" class="btn btn-primary btn-round d-block"><span class="ion ion-md-add"></span>&nbsp; Create ticket</button>
</h4>

<!-- Filters -->
<div class="ui-bordered px-4 pt-4 mb-4">
  <div class="form-row align-items-center">
    <div class="col-md mb-4">
      <label class="form-label">Priority</label>
      <select class="custom-select" [(ngModel)]="filterPriority">
        <option *ngFor="let item of ['Any', 'High', 'Medium', 'Low']" [value]="item">{{item}}</option>
      </select>
    </div>
    <div class="col-md mb-4">
      <label class="form-label">Status</label>
      <select class="custom-select" [(ngModel)]="filterStatus">
        <option *ngFor="let item of ['Any', 'Open', 'Reopened', 'In progress', 'Closed']" [value]="item">{{item}}</option>
      </select>
    </div>
    <div class="col-md mb-4">
      <label class="form-label">Created date</label>
      <custom-daterange-picker [(ngModel)]="filterCreatedDate"></custom-daterange-picker>
    </div>
    <div class="col-md col-xl-2 mb-4">
      <label class="form-label d-none d-md-block">&nbsp;</label>
      <button type="button" class="btn btn-secondary btn-block">Show</button>
    </div>
  </div>
</div>
<!-- / Filters -->

<div class="card">

  <!-- Table controls -->
  <div class="card-body">

    <div class="row">
      <div class="col">
        Per page: &nbsp;
        <select
          [(ngModel)]="perPage"
          (change)="update()"
          class="custom-select custom-select-sm d-inline-block w-auto">
          <option *ngFor="let limit of [10, 20, 30, 40, 50]">{{limit}}</option>
        </select>
      </div>
      <div class="col">
        <input type="text"
          [(ngModel)]="filterVal"
          (input)="currentPage = 1; update()"
          class="form-control form-control-sm d-inline-block w-auto float-sm-right"
          placeholder="Search...">
      </div>
    </div>

  </div>
  <!-- / Table controls -->

  <!-- Table -->
  <hr class="border-light m-0">
  <div class="table-responsive">
    <table class="table table-striped table-bordered card-table">
      <thead>
        <tr>
          <th class="text-nowrap cursor-pointer" (click)="setSort('id')">
            ID<i class="ion text-muted ml-2" *ngIf="sortBy=='id'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" style="min-width: 300px" (click)="setSort('subject')">
            Subject<i class="ion text-muted ml-2" *ngIf="sortBy=='subject'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('createdAt')">
            Created at<i class="ion text-muted ml-2" *ngIf="sortBy=='createdAt'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('lastUpdate')">
            Last update<i class="ion text-muted ml-2" *ngIf="sortBy=='lastUpdate'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('priority')">
            Priority<i class="ion text-muted ml-2" *ngIf="sortBy=='priority'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('status')">
            Status<i class="ion text-muted ml-2" *ngIf="sortBy=='status'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let ticket of ticketsData">
          <td class="align-middle py-3">{{ticket.id}}</td>
          <td class="align-middle py-3">{{ticket.subject}}</td>
          <td class="align-middle py-3">{{ticket.createdAt}}</td>
          <td class="align-middle py-3">{{ticket.lastUpdate}}</td>
          <td class="align-middle py-3">
            <div class="btn-group" ngbDropdown [placement]="!isRTL ? 'bottom-right' : 'bottom-left'">
              <button type="button" class="btn btn-xs md-btn-flat" [ngClass]="priorityDropdownVariant(ticket.priority)" ngbDropdownToggle>
                <span *ngIf="ticket.priority === 1">High</span>
                <span *ngIf="ticket.priority === 2">Medium</span>
                <span *ngIf="ticket.priority === 3">Low</span>
              </button>
              <div ngbDropdownMenu [class.dropdown-menu-right]="!isRTL">
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.priority === 1}">High</a>
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.priority === 2}">Medium</a>
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.priority === 3}">Low</a>
              </div>
            </div>
          </td>
          <td class="align-middle py-3">
            <div class="btn-group" ngbDropdown [placement]="!isRTL ? 'bottom-right' : 'bottom-left'">
              <button type="button" class="btn btn-outline-secondary btn-xs md-btn-flat" ngbDropdownToggle>
                <span *ngIf="ticket.status === 1">Open</span>
                <span *ngIf="ticket.status === 2">Reopened</span>
                <span *ngIf="ticket.status === 3">In progress</span>
                <span *ngIf="ticket.status === 4">Closed</span>
              </button>
              <div ngbDropdownMenu [class.dropdown-menu-right]="!isRTL">
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.status === 1}">Open</a>
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.status === 2}">Reopened</a>
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.status === 3}">In progress</a>
                <a class="dropdown-item" href="javascript:void(0)" [ngClass]="{active: ticket.status === 4}">Closed</a>
              </div>
            </div>
          </td>
          <td class="text-center text-nowrap align-middle py-3">
            <a href="javascript:void(0)" class="btn btn-default btn-xs icon-btn md-btn-flat" ngbTooltip="Edit"><i class="ion ion-md-create"></i></a>
            <a href="javascript:void(0)" class="btn btn-default btn-xs icon-btn md-btn-flat" ngbTooltip="Remove"><i class="ion ion-md-close"></i></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- / Table -->

  <!-- Pagination -->
  <div class="card-body py-0">

    <div class="row">
      <div class="col-sm text-sm-left text-center pt-3">
        <span class="text-muted" *ngIf="totalItems">Page {{ currentPage }} of {{ totalPages }}</span>
      </div>
      <div class="col-sm pt-3">
        <ngb-pagination
          [collectionSize]="totalItems"
          [pageSize]="perPage"
          [(page)]="currentPage"
          (pageChange)="update()"
          size="sm"
          class="d-flex justify-content-center justify-content-sm-end m-0"></ngb-pagination>
      </div>
    </div>

  </div>
  <!-- / Pagination -->
</div>
