// angular-demo/src/app/+complete-ui/cui-button-groups/cui-button-groups.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'cui-button-groups', // tslint:disable-line
  templateUrl: './cui-button-groups.component.html',
})
export class CuiButtonGroupsComponent {
  isRTL: boolean;

  constructor(appService: AppService) {
    this.isRTL = appService.isRTL;
  }
}

<div class="ui-block">
  <h3 class="ui-block-heading">Button groups</h3>

  <h4 class="ui-block-heading">Sizes</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <!-- Extra-large -->
    <div class="btn-group btn-group-xl">
      <button type="button" class="btn btn-secondary">Left</button>
      <button type="button" class="btn btn-secondary">Middle</button>
      <button type="button" class="btn btn-secondary">Right</button>
    </div>

    <br>

    <!-- Large -->
    <div class="btn-group btn-group-lg">
      <button type="button" class="btn btn-secondary">Left</button>
      <button type="button" class="btn btn-secondary">Middle</button>
      <button type="button" class="btn btn-secondary">Right</button>
    </div>

    <br>

    <!-- Default -->
    <div class="btn-group">
      <button type="button" class="btn btn-secondary">Left</button>
      <button type="button" class="btn btn-secondary">Middle</button>
      <button type="button" class="btn btn-secondary">Right</button>
    </div>

    <br>

    <!-- Small -->
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-secondary">Left</button>
      <button type="button" class="btn btn-secondary">Middle</button>
      <button type="button" class="btn btn-secondary">Right</button>
    </div>

    <br>

    <!-- Extra-small -->
    <div class="btn-group btn-group-xs">
      <button type="button" class="btn btn-secondary">Left</button>
      <button type="button" class="btn btn-secondary">Middle</button>
      <button type="button" class="btn btn-secondary">Right</button>
    </div>
  </div>

  <h4 class="ui-block-heading">Button toolbars</h4>

  <div class="cui-example">
    <div class="btn-toolbar">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-secondary">1</button>
        <button type="button" class="btn btn-secondary">2</button>
        <button type="button" class="btn btn-secondary">3</button>
        <button type="button" class="btn btn-secondary">4</button>
      </div>
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-secondary">5</button>
        <button type="button" class="btn btn-secondary">6</button>
        <button type="button" class="btn btn-secondary">7</button>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-secondary">8</button>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Nesting</h4>

  <div class="cui-example">
    <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-secondary">1</button>
      <button type="button" class="btn btn-secondary">2</button>
      <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
        <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Vertical</h4>

  <div class="cui-example">
    <div class="btn-group-vertical">
      <button type="button" class="btn btn-secondary">Button</button>
      <button type="button" class="btn btn-secondary">Button</button>
      <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
        </div>
      </div>
      <button type="button" class="btn btn-secondary">Button</button>
      <button type="button" class="btn btn-secondary">Button</button>
      <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
        </div>
      </div>
      <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
        </div>
      </div>
      <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
          <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
        </div>
      </div>
    </div>
  </div>
</div>

// vue-demo/src/cui-components/CuiButtonGroups.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Button groups</h3>

    <h4 class="ui-block-heading">Sizes</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <!-- Extra-large -->
      <b-btn-group class="btn-group-xl">
        <b-btn>Left</b-btn>
        <b-btn>Middle</b-btn>
        <b-btn>Right</b-btn>
      </b-btn-group>

      <br>

      <!-- Large -->
      <b-btn-group size="lg">
        <b-btn>Left</b-btn>
        <b-btn>Middle</b-btn>
        <b-btn>Right</b-btn>
      </b-btn-group>

      <br>

      <!-- Default -->
      <b-btn-group>
        <b-btn>Left</b-btn>
        <b-btn>Middle</b-btn>
        <b-btn>Right</b-btn>
      </b-btn-group>

      <br>

      <!-- Small -->
      <b-btn-group class="btn-group-sm">
        <b-btn>Left</b-btn>
        <b-btn>Middle</b-btn>
        <b-btn>Right</b-btn>
      </b-btn-group>

      <br>

      <!-- Extra-small -->
      <b-btn-group class="btn-group-xs">
        <b-btn>Left</b-btn>
        <b-btn>Middle</b-btn>
        <b-btn>Right</b-btn>
      </b-btn-group>
    </div>

    <h4 class="ui-block-heading">Button toolbars</h4>

    <div class="cui-example">
      <b-btn-toolbar key-nav>
        <b-btn-group class="mr-2">
          <b-btn>&laquo;</b-btn>
          <b-btn>&lsaquo;</b-btn>
        </b-btn-group>
        <b-btn-group class="mr-2">
          <b-btn>Edit</b-btn>
          <b-btn>Undo</b-btn>
          <b-btn>Redo</b-btn>
        </b-btn-group>
        <b-btn-group>
          <b-btn>&rsaquo;</b-btn>
          <b-btn>&raquo;</b-btn>
        </b-btn-group>
      </b-btn-toolbar>
    </div>

    <h4 class="ui-block-heading">Nesting</h4>

    <div class="cui-example">
      <b-btn-group>
        <b-btn>1</b-btn>
        <b-btn>2</b-btn>
        <b-dd :right="isRTL" text="Dropdown">
          <b-dd-item>Dropdown link</b-dd-item>
          <b-dd-item>Dropdown link</b-dd-item>
        </b-dd>
      </b-btn-group>
    </div>

    <h4 class="ui-block-heading">Vertical</h4>

    <div class="cui-example">
      <b-btn-group vertical>
        <b-btn class="btn btn-secondary">Button</b-btn>
        <b-btn class="btn btn-secondary">Button</b-btn>
        <b-dd :right="isRTL" text="Dropdown">
          <b-dd-item>Dropdown link</b-dd-item>
          <b-dd-item>Dropdown link</b-dd-item>
        </b-dd>
        <b-btn class="btn btn-secondary">Button</b-btn>
        <b-btn class="btn btn-secondary">Button</b-btn>
        <b-dd :right="isRTL" text="Dropdown">
          <b-dd-item>Dropdown link</b-dd-item>
          <b-dd-item>Dropdown link</b-dd-item>
        </b-dd>
        <b-dd :right="isRTL" text="Dropdown">
          <b-dd-item>Dropdown link</b-dd-item>
          <b-dd-item>Dropdown link</b-dd-item>
        </b-dd>
        <b-dd :right="isRTL" text="Dropdown">
          <b-dd-item>Dropdown link</b-dd-item>
          <b-dd-item>Dropdown link</b-dd-item>
        </b-dd>
      </b-btn-group>
    </div>
  </div>
</template>

<script>
export default {}
</script>
