// angular-demo/src/app/+complete-ui/cui-custom-checkboxes-and-radios/cui-custom-checkboxes-and-radios.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-custom-checkboxes-and-radios', // tslint:disable-line
  templateUrl: './cui-custom-checkboxes-and-radios.component.html'
})
export class CuiCustomCheckboxesAndRadiosComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">Custom checkboxes and radios</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <!-- Custom checkbox -->
    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input">
      <span class="custom-control-label">Check this custom checkbox</span>
    </label>

    <br>

    <!-- Custom indeterminate checkbox -->
    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" [indeterminate]="true">
      <span class="custom-control-label">Check this custom checkbox</span>
    </label>

    <br>

    <!-- Custom radios -->
    <label class="custom-control custom-radio">
      <input name="custom-radio" type="radio" class="custom-control-input">
      <span class="custom-control-label">Toggle this custom radio</span>
    </label>
    <label class="custom-control custom-radio">
      <input name="custom-radio" type="radio" class="custom-control-input">
      <span class="custom-control-label">Or toggle this other custom radio</span>
    </label>
  </div>

  <h4 class="ui-block-heading">Disabled</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <!-- Custom checkboxes -->
    <div>
      <label class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" disabled checked>
        <span class="custom-control-label">Check this custom checkbox</span>
      </label>
      <label class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" [indeterminate]="true" disabled>
        <span class="custom-control-label">Check this custom checkbox</span>
      </label>
      <label class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" disabled>
        <span class="custom-control-label">Check this custom checkbox</span>
      </label>
    </div>

    <!-- Custom radios -->
    <fieldset disabled>
      <label class="custom-control custom-radio">
        <input name="custom-radio-2" type="radio" class="custom-control-input" checked>
        <span class="custom-control-label">Toggle this custom radio</span>
      </label>
      <label class="custom-control custom-radio">
        <input name="custom-radio-2" type="radio" class="custom-control-input">
        <span class="custom-control-label">Or toggle this other custom radio</span>
      </label>
    </fieldset>
  </div>

  <h4 class="ui-block-heading">Validations states</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div class="form-group">
      <label class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input is-valid">
        <span class="custom-control-label">Valid state</span>
      </label>
    </div>

    <div class="form-group">
      <label class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input is-invalid">
        <span class="custom-control-label">Invalid state</span>
      </label>
    </div>
  </div>

  <h4 class="ui-block-heading">Stacked</h4>

  <div class="cui-example">
    <div class="custom-controls-stacked">
      <label class="custom-control custom-radio">
        <input name="custom-radio-3" type="radio" class="custom-control-input" checked>
        <span class="custom-control-label">Toggle this custom radio</span>
      </label>
      <label class="custom-control custom-radio">
        <input name="custom-radio-3" type="radio" class="custom-control-input">
        <span class="custom-control-label">Or toggle this other custom radio</span>
      </label>
      <label class="custom-control custom-radio">
        <input name="custom-radio-3" type="radio" class="custom-control-input">
        <span class="custom-control-label">Or toggle this other custom radio</span>
      </label>
    </div>
  </div>
</div>

// vue-demo/src/cui-components/CuiCustomCheckboxesAndRadios.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Custom checkboxes and radios</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <!-- Custom checkbox -->
      <b-check-group v-model="multipleModel" :options="options" />

      <!-- Indeterminate custom checkbox -->
      <b-form-checkbox v-model="indeterminateChecked" :indeterminate.sync="indeterminate">
        Indeterminate
      </b-form-checkbox>

      <!-- Custom radios -->
      <b-radio-group v-model="singleModel" :options="options" />
    </div>

    <h4 class="ui-block-heading">Disabled</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <!-- Custom checkboxes -->
      <b-check-group v-model="multipleModel" :options="options" disabled />

      <!-- Indeterminate custom checkbox -->
      <b-form-checkbox v-model="dIndeterminateChecked" :indeterminate.sync="dIndeterminate" disabled>
        Indeterminate
      </b-form-checkbox>

      <!-- Custom radios -->
      <fieldset disabled>
        <b-radio-group v-model="singleModel" :options="options" />
      </fieldset>
    </div>

    <h4 class="ui-block-heading">Validation states</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-check :state="'valid'">Valid state</b-check>
      <b-check :state="'invalid'">Invalid state</b-check>
    </div>

    <h4 class="ui-block-heading">Stacked</h4>

    <div class="cui-example">
      <!-- Checkboxs -->
      <b-check-group stacked v-model="multipleModel" :options="options" />

      <br>

      <!-- Radios -->
      <b-radio-group stacked v-model="singleModel" :options="options" />
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    options: [
      { text: 'Orange', value: 'orange' },
      { text: 'Apple', value: 'apple' },
      { text: 'Pineapple', value: 'pineapple' },
      { text: 'Grape', value: 'grape', disabled: true }
    ],
    singleModel: 'apple',
    multipleModel: ['orange'],
    indeterminateChecked: false,
    indeterminate: true,
    dIndeterminateChecked: false,
    dIndeterminate: true
  })
}
</script>
