// angular-demo/src/app/+pages/invoice-print/invoice-print.component.ts
/// <reference types="numeral" />

import { Component, ViewEncapsulation, AfterViewInit } from '@angular/core';
import { AppService } from '../../app.service';
import * as numeral from 'numeral';

@Component({
  selector: 'app-invoice-print',
  templateUrl: './invoice-print.component.html',
  styles: [`
    html, body { background: #fff !important; }
    body > :not(app-root) { display: none !important; }
    .invoice-print { min-width: 768px !important; font-size: 15px !important; }
    .invoice-print * { border-color: #aaa !important; color: #000 !important; }
  `],
  encapsulation: ViewEncapsulation.None
})
export class InvoicePrintComponent implements AfterViewInit {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Invoice (Print version) - Pages';
  }

  invoiceData = {
    id: 49029,
    date: 'January 12, 2015',
    dueDate: 'May 12, 2015',
    taxPercent: 25,

    recipient: {
      name: 'Alice Hampton',
      company: 'Company LTD',
      street: '70 Bowman St.',
      city: 'South Windsor, CT 06074',
      country: 'United States',
      phone: '+9 (965) 645 8146',
      email: 'ahampton@mail.com'
    },

    details: {
      bankName: 'Finance Bank',
      country: 'United States',
      city: 'West New York, NJ 07093',
      address: '23 Sussex Ave.',
      iban: 'ETD85039283901259',
      swiftCode: 'AS4F1'
    },

    items: [{
      title: 'Website design and development',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.',
      hourRate: 50,
      hours: 63
    }, {
      title: 'Branding',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.',
      hourRate: 47.95,
      hours: 36
    }]
  };

  ngAfterViewInit() {
    window.print();
  }

  get invoiceSubtotal() {
    return this.invoiceData['items'].reduce((cnt, item) => {
      cnt += item.hourRate * item.hours;
      return cnt;
    }, 0);
  }

  get invoiceTax() {
    return this.invoiceSubtotal * this.invoiceData['taxPercent'] / 100;
  }

  get invoiceTotal() {
    return this.invoiceSubtotal + this.invoiceTax;
  }

  formatPrice(p) {
    return numeral(p).format('$0,0.00');
  }

}

<div class="invoice-print p-5">

  <div class="row">
    <div class="col-6 pb-4">

      <div class="media align-items-center mb-4">
        <div class="ui-w-40">
          <div class="w-100 position-relative" style="padding-bottom: 54%">
            <svg class="w-100 h-100 position-absolute" viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path fill="#999" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
          </div>
        </div>
        <div class="media-body text-big font-weight-bold ml-2">
          Appwork
        </div>
      </div>

      <div class="mb-1">Office 154, 330 North Brand Boulevard</div>
      <div class="mb-1">Glendale, CA 91203, USA</div>
      <div>+0 (123) 456 7891, +9 (876) 543 2198</div>

    </div>

    <div class="col-6 text-right pb-4">

      <h6 class="text-big text-large font-weight-bold mb-3">INVOICE #{{invoiceData.id}}</h6>
      <div class="mb-1">Date: <strong class="font-weight-semibold">{{invoiceData.date}}</strong></div>
      <div>Due date: <strong class="font-weight-semibold">{{invoiceData.dueDate}}</strong></div>

    </div>
  </div>

  <hr class="mb-4">

  <div class="row">
    <div class="col-6 mb-4">

      <div class="font-weight-bold mb-2">Invoice To:</div>
      <div>{{invoiceData.recipient.name}}</div>
      <div *ngIf="invoiceData.recipient.company">{{invoiceData.recipient.company}}</div>
      <div>{{invoiceData.recipient.street}}</div>
      <div>{{invoiceData.recipient.city}}</div>
      <div>{{invoiceData.recipient.country}}</div>
      <div *ngIf="invoiceData.recipient.phone">{{invoiceData.recipient.phone}}</div>
      <div>{{invoiceData.recipient.email}}</div>

    </div>
    <div class="col-6 mb-4">

      <div class="font-weight-bold mb-2">Payment Details:</div>
      <table>
        <tbody>
          <tr>
            <td class="pr-3">Total Due:</td>
            <td><strong>{{formatPrice(invoiceTotal)}}</strong></td>
          </tr>
          <tr>
            <td class="pr-3">Bank name:</td>
            <td>{{invoiceData.details.bankName}}</td>
          </tr>
          <tr>
            <td class="pr-3">Country:</td>
            <td>{{invoiceData.details.country}}</td>
          </tr>
          <tr>
            <td class="pr-3">City:</td>
            <td>{{invoiceData.details.city}}</td>
          </tr>
          <tr>
            <td class="pr-3">Address:</td>
            <td>{{invoiceData.details.address}}</td>
          </tr>
          <tr>
            <td class="pr-3">IBAN:</td>
            <td>{{invoiceData.details.iban}}</td>
          </tr>
          <tr>
            <td class="pr-3">SWIFT code:</td>
            <td>{{invoiceData.details.swiftCode}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="table-responsive mb-4">
    <table class="table m-0">
      <thead>
        <tr>
          <th class="py-3">
            Task description
          </th>
          <th class="py-3">
            Rate
          </th>
          <th class="py-3">
            Hours
          </th>
          <th class="py-3">
            Line total
          </th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let item of invoiceData.items">
          <td class="py-3">
            <div class="font-weight-semibold">{{item.title}}</div>
            <div *ngIf="item.description" class="text-muted">{{item.description}}</div>
          </td>
          <td class="py-3">
            <strong>{{formatPrice(item.hourRate)}}</strong>
          </td>
          <td class="py-3">
            <strong>{{item.hours}}</strong>
          </td>
          <td class="py-3">
            <strong>{{formatPrice(item.hourRate * item.hours)}}</strong>
          </td>
        </tr>
        <tr>
          <td colspan="3" class="text-right py-3">
            Subtotal:<br>
            Tax({{invoiceData.taxPercent}}%):<br>
            <span class="d-block text-big mt-2">Total:</span>
          </td>
          <td class="py-3">
            <strong>{{formatPrice(invoiceSubtotal)}}</strong><br>
            <strong>{{formatPrice(invoiceTax)}}</strong><br>
            <strong class="d-block text-big mt-2">{{formatPrice(invoiceTotal)}}</strong>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="text-muted">
    <strong>Note:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet, dolor id dapibus dapibus, neque mi tincidunt quam, quis congue ligula risus vitae magna. Curabitur ultrices nisi massa, nec viverra lorem feugiat sed. Mauris non porttitor nunc. Integer eu orci in magna auctor vestibulum.
  </div>

</div>

// vue-demo/src/components/pages/InvoicePrint.vue
<template>
  <div class="invoice-print p-5">

    <div class="row">
      <div class="col-6 pb-4">

        <div class="media align-items-center mb-4">
          <div class="ui-w-40">
            <div class="w-100 position-relative" style="padding-bottom: 54%">
              <svg class="w-100 h-100 position-absolute" viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path fill="#999" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
            </div>
          </div>
          <div class="media-body text-big font-weight-bold ml-2">
            Appwork
          </div>
        </div>

        <div class="mb-1">Office 154, 330 North Brand Boulevard</div>
        <div class="mb-1">Glendale, CA 91203, USA</div>
        <div>+0 (123) 456 7891, +9 (876) 543 2198</div>

      </div>

      <div class="col-6 text-right pb-4">

        <h6 class="text-big text-large font-weight-bold mb-3">INVOICE #{{invoiceData.id}}</h6>
        <div class="mb-1">Date: <strong class="font-weight-semibold">{{invoiceData.date}}</strong></div>
        <div>Due date: <strong class="font-weight-semibold">{{invoiceData.dueDate}}</strong></div>

      </div>
    </div>

    <hr class="mb-4">

    <div class="row">
      <div class="col-6 mb-4">

        <div class="font-weight-bold mb-2">Invoice To:</div>
        <div>{{invoiceData.recipient.name}}</div>
        <div v-if="invoiceData.recipient.company">{{invoiceData.recipient.company}}</div>
        <div>{{invoiceData.recipient.street}}</div>
        <div>{{invoiceData.recipient.city}}</div>
        <div>{{invoiceData.recipient.country}}</div>
        <div v-if="invoiceData.recipient.phone">{{invoiceData.recipient.phone}}</div>
        <div>{{invoiceData.recipient.email}}</div>

      </div>
      <div class="col-6 mb-4">

        <div class="font-weight-bold mb-2">Payment Details:</div>
        <table>
          <tbody>
            <tr>
              <td class="pr-3">Total Due:</td>
              <td><strong>{{formatPrice(invoiceTotal)}}</strong></td>
            </tr>
            <tr>
              <td class="pr-3">Bank name:</td>
              <td>{{invoiceData.details.bankName}}</td>
            </tr>
            <tr>
              <td class="pr-3">Country:</td>
              <td>{{invoiceData.details.country}}</td>
            </tr>
            <tr>
              <td class="pr-3">City:</td>
              <td>{{invoiceData.details.city}}</td>
            </tr>
            <tr>
              <td class="pr-3">Address:</td>
              <td>{{invoiceData.details.address}}</td>
            </tr>
            <tr>
              <td class="pr-3">IBAN:</td>
              <td>{{invoiceData.details.iban}}</td>
            </tr>
            <tr>
              <td class="pr-3">SWIFT code:</td>
              <td>{{invoiceData.details.swiftCode}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="table-responsive mb-4">
      <table class="table m-0">
        <thead>
          <tr>
            <th class="py-3">Task description</th>
            <th class="py-3">Rate</th>
            <th class="py-3">Hours</th>
            <th class="py-3">Line total</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in invoiceData.items" :key="item.title">
            <td class="py-3">
              <div class="font-weight-semibold">{{item.title}}</div>
              <div v-if="item.description" class="text-muted">{{item.description}}</div>
            </td>
            <td class="py-3">
              <strong>{{formatPrice(item.hourRate)}}</strong>
            </td>
            <td class="py-3">
              <strong>{{item.hours}}</strong>
            </td>
            <td class="py-3">
              <strong>{{formatPrice(item.hourRate * item.hours)}}</strong>
            </td>
          </tr>
          <tr>
            <td colspan="3" class="text-right py-3">
              Subtotal:<br>
              Tax({{invoiceData.taxPercent}}%):<br>
              <span class="d-block text-big mt-2">Total:</span>
            </td>
            <td class="py-3">
              <strong>{{formatPrice(invoiceSubtotal)}}</strong><br>
              <strong>{{formatPrice(invoiceTax)}}</strong><br>
              <strong class="d-block text-big mt-2">{{formatPrice(invoiceTotal)}}</strong>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="text-muted">
      <strong>Note:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet, dolor id dapibus dapibus, neque mi tincidunt quam, quis congue ligula risus vitae magna. Curabitur ultrices nisi massa, nec viverra lorem feugiat sed. Mauris non porttitor nunc. Integer eu orci in magna auctor vestibulum.
    </div>

  </div>
</template>

<style scoped>
  html, body { background: #fff !important; }
  body > :not(#app) { display: none !important; }
  .invoice-print { min-width: 768px !important; font-size: 15px !important; }
  .invoice-print * { border-color: #aaa !important; color: #000 !important; }
</style>

<script>
import * as numeral from 'numeral'

export default {
  name: 'pages-invoice-print',
  metaInfo: {
    title: 'Invoice (Print version) - Pages'
  },
  data: () => ({
    invoiceData: {
      id: 49029,
      date: 'January 12, 2015',
      dueDate: 'May 12, 2015',
      taxPercent: 25,

      recipient: {
        name: 'Alice Hampton',
        company: 'Company LTD',
        street: '70 Bowman St.',
        city: 'South Windsor, CT 06074',
        country: 'United States',
        phone: '+9 (965) 645 8146',
        email: 'ahampton@mail.com'
      },

      details: {
        bankName: 'Finance Bank',
        country: 'United States',
        city: 'West New York, NJ 07093',
        address: '23 Sussex Ave.',
        iban: 'ETD85039283901259',
        swiftCode: 'AS4F1'
      },

      items: [{
        title: 'Website design and development',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.',
        hourRate: 50,
        hours: 63
      }, {
        title: 'Branding',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.',
        hourRate: 47.95,
        hours: 36
      }]
    }
  }),
  computed: {
    invoiceSubtotal () {
      return this.invoiceData.items.reduce((cnt, item) => {
        cnt += item.hourRate * item.hours
        return cnt
      }, 0)
    },
    invoiceTax () {
      return this.invoiceSubtotal * this.invoiceData.taxPercent / 100
    },
    invoiceTotal () {
      return this.invoiceSubtotal + this.invoiceTax
    }
  },
  methods: {
    formatPrice (p) {
      return numeral(p).format('$0,0.00')
    }
  },
  mounted () {
    window.print()
  }
}
</script>
