// vue-demo/src/cui-components/CuiCarousel.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Carousel</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example">
      <b-carousel controls indicators :interval="4000">
        <b-carousel-slide
          caption="First slide"
          text="Eos mutat malis maluisset et, agam ancillae quo te, in vim congue pertinacia."
          :img-src="`${baseUrl}img/bg/1.jpg`" />
        <b-carousel-slide
          caption="Second slide"
          text="In numquam omittam sea."
          :img-src="`${baseUrl}img/bg/2.jpg`" />
        <b-carousel-slide
          caption="Third slide"
          text="Lorem ipsum dolor sit amet, virtute consequat ea qui, minim graeco mel no."
          :img-src="`${baseUrl}img/bg/3.jpg`" />
      </b-carousel>
    </div>
  </div>
</template>

<script>
export default {}
</script>

// angular-demo/src/app/+complete-ui/cui-carousel/cui-carousel.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-carousel', // tslint:disable-line
  templateUrl: './cui-carousel.component.html'
})
export class CuiCarouselComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">Carousel</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example">
    <ngb-carousel>
      <ng-template ngbSlide>
        <img class="d-block w-100" src="assets/img/bg/1.jpg" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
          <h3>First slide</h3>
          <p>Eos mutat malis maluisset et, agam ancillae quo te, in vim congue pertinacia.</p>
        </div>
      </ng-template>
      <ng-template ngbSlide>
        <img class="d-block w-100" src="assets/img/bg/2.jpg" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
          <h3>Second slide</h3>
          <p>In numquam omittam sea.</p>
        </div>
      </ng-template>
      <ng-template ngbSlide>
        <img class="d-block w-100" src="assets/img/bg/3.jpg" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
          <h3>Third slide</h3>
          <p>Lorem ipsum dolor sit amet, virtute consequat ea qui, minim graeco mel no.</p>
        </div>
      </ng-template>
    </ngb-carousel>
  </div>
</div>
