// angular-demo/src/app/+pages/articles-edit/articles-edit.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-articles-edit',
  templateUrl: './articles-edit.component.html',
  styleUrls: [
    '../../../vendor/libs/quill/typography.scss',
    '../../../vendor/libs/quill/editor.scss',
    './articles-edit.component.scss'
  ]
})
export class ArticlesEditComponent {
  isIE10: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Edit article - Pages';
    this.isIE10 = this.appService.isIE10;
  }

  articleData = {
    id: 563,
    createdAt: '03/30/2018',
    title: 'What Is The Big R For Marketing Your Business',
    slug: 'what-is-the-big-r-for-marketing-your-business',
    tags: ['Productivity', 'Creativity', 'Writing', 'Inspiration', 'Psychology'],
    status: 1,
    content: 'Article content',
    mainImage: '13.jpg',

    author: {
      avatar: '1-small.png',
      username: 'mgreene',
      name: 'Mike Greene'
    },

    meta: {
      title: 'What Is The Big R For Marketing Your Business',
      description: 'Read What Is The Big R For Marketing Your Business',
      keywords: 'Productivity, Creativity, Writing, Inspiration, Psychology'
    }
  };
}

<h4 class="font-weight-bold py-3 mb-4">
  Edit article <span class="text-muted">#{{articleData.id}}</span>
</h4>

<div class="card">
  <div class="card-body media align-items-center">
    <img [src]="'assets/img/avatars/' + articleData.author.avatar" class="d-block ui-w-40 rounded-circle" alt="">
    <div class="media-body ml-3">
      <a href="javascript:void(0)" class="d-block text-dark">
        <strong>{{articleData.author.name}}</strong>
        <span class="text-muted">@{{articleData.author.username}}</span>
      </a>
      Created at {{articleData.createdAt}}
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body pb-2">

    <div class="form-group">
      <label class="form-label">Title</label>
      <input [(ngModel)]="articleData.title" type="text" class="form-control">
    </div>

    <div class="form-group">
      <label class="form-label">Slug</label>
      <input [(ngModel)]="articleData.slug" type="text" class="form-control">
    </div>

    <div class="form-group">
      <label class="form-label">Tags</label>
      <tag-input [(ngModel)]="articleData.tags"></tag-input>
    </div>

    <div class="form-group">
      <label class="form-label">Status</label>
      <select class="custom-select" [(ngModel)]="articleData.status">
        <option *ngFor="let i of [[1, 'Published'], [2, 'Draft'], [3, 'Deleted']]" [value]="i[0]">{{i[1]}}</option>
      </select>
    </div>

    <div class="form-group">
      <label class="form-label">Content</label>
      <quill-editor [(ngModel)]="articleData.content" placeholder="Type something" *ngIf="!isIE10">
        <div quill-editor-toolbar>
          <span class="ql-formats">
            <select class="ql-font"></select>
            <select class="ql-size"></select>
          </span>
          <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-italic"></button>
            <button class="ql-underline"></button>
            <button class="ql-strike"></button>
          </span>
          <span class="ql-formats">
            <select class="ql-color"></select>
            <select class="ql-background"></select>
          </span>
          <span class="ql-formats">
            <button class="ql-script" value="sub"></button>
            <button class="ql-script" value="super"></button>
          </span>
          <span class="ql-formats">
            <button class="ql-header" value="1"></button>
            <button class="ql-header" value="2"></button>
            <button class="ql-blockquote"></button>
            <button class="ql-code-block"></button>
          </span>
          <span class="ql-formats">
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
            <button class="ql-indent" value="-1"></button>
            <button class="ql-indent" value="+1"></button>
          </span>
          <span class="ql-formats">
            <button class="ql-direction" value="rtl"></button>
            <select class="ql-align"></select>
          </span>
          <span class="ql-formats">
            <button class="ql-link"></button>
            <button class="ql-image"></button>
            <button class="ql-video"></button>
          </span>
          <span class="ql-formats">
            <button class="ql-clean"></button>
          </span>
        </div>
      </quill-editor>

      <!-- Fallback -->
      <textarea [(ngModel)]="articleData.content" class="form-control" style="height: 400px" *ngIf="isIE10"></textarea>
    </div>

    <div class="form-group media" style="min-height:1px">
      <div class="ui-bg-cover" style="width: 100px;height: 100px;" [style.backgroundImage]="'url(\'assets/img/bg/' + articleData.mainImage + '\')'"></div>
      <div class="media-body ml-3">
        <label class="form-label">
          Main image:
        </label>
        <a href="javascript:void(0)" class="d-block">http://example.com/path/to/image/{{articleData.mainImage}}</a>
        <label class="custom-file mt-3">
          <input type="file" class="custom-file-input">
          <span class="custom-file-label"></span>
        </label>
      </div>
    </div>

  </div>
  <hr class="m-0">
  <div class="card-body pb-2">
    <h6 class="small font-weight-semibold mb-4">Meta</h6>

    <div class="form-group">
      <label class="form-label">Title</label>
      <input [(ngModel)]="articleData.meta.title" type="text" class="form-control">
    </div>

    <div class="form-group">
      <label class="form-label">Description</label>
      <textarea [(ngModel)]="articleData.meta.description" class="form-control" rows="3"></textarea>
    </div>

    <div class="form-group">
      <label class="form-label">Keywords</label>
      <input [(ngModel)]="articleData.meta.keywords" type="text" class="form-control">
    </div>
  </div>

</div>

<div class="text-right mt-3">
  <button type="button" class="btn btn-primary">Save changes</button>&nbsp;
  <button type="button" class="btn btn-default">Cancel</button>
</div>

// vue-demo-cli2-deprecated/src/components/pages/ArticlesEdit.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      Edit article <span class="text-muted">#{{articleData.id}}</span>
    </h4>

    <b-card no-body>
      <b-card-body class="media align-items-center">

        <img :src="`${baseUrl}img/avatars/${articleData.author.avatar}`" class="d-block ui-w-40 rounded-circle" alt="">
        <div class="media-body ml-3">
          <a href="javascript:void(0)" class="d-block text-dark">
            <strong>{{articleData.author.name}}</strong>
            <span class="text-muted">@{{articleData.author.username}}</span>
          </a>
          Created at {{articleData.created_at}}
        </div>

      </b-card-body>
      <hr class="m-0">
      <b-card-body class="pb-2">

        <b-form-group label="Title">
          <b-input v-model="articleData.title" />
        </b-form-group>

        <b-form-group label="Slug">
          <b-input v-model="articleData.slug" />
        </b-form-group>

        <b-form-group label="Tags">
          <multiselect v-model="articleData.tags" :multiple="true" :taggable="true" :options="[]" @tag="addTag" placeholder="Add tag" />
        </b-form-group>

        <b-form-group label="Status">
          <b-select v-model="articleData.status" :options="{1: 'Published', 2: 'Draft', 3: 'Deleted'}" />
        </b-form-group>

        <b-form-group label="Content">
          <quill-editor v-model="articleData.content" :options="editorOptions" v-if="!isIE10Mode" />
          <!-- Fallback -->
          <b-textarea v-model="articleData.content" style="height: 400px" v-if="isIE10Mode" />
        </b-form-group>

        <div class="form-group media" style="min-height:1px">
          <div class="ui-bg-cover" style="width: 100px;height: 100px" :style="{'background-image': `url('${baseUrl}img/bg/${articleData.main_image}')`}"></div>
          <div class="media-body ml-3">
            <label class="form-label">Main image:</label>
            <a href="javascript:void(0)" class="d-block">http://example.com/path/to/image/{{articleData.main_image}}</a>
            <b-form-file v-model="mainFileSelect" placeholder="Choose a file..." class="mt-3" />
          </div>
        </div>

      </b-card-body>
      <hr class="m-0">
      <b-card-body class="pb-2">

        <h6 class="small font-weight-semibold mb-4">Meta</h6>

        <b-form-group label="Title">
          <b-input v-model="articleData.meta.title" />
        </b-form-group>

        <b-form-group label="Description">
          <b-textarea v-model="articleData.meta.description" :rows="3" />
        </b-form-group>

        <b-form-group label="Keywords">
          <b-input v-model="articleData.meta.keywords" />
        </b-form-group>

      </b-card-body>
    </b-card>

    <div class="text-right mt-3">
      <b-btn variant="primary">Save changes</b-btn>&nbsp;
      <b-btn variant="default">Cancel</b-btn>
    </div>
  </div>
</template>

<style src="vue-multiselect/dist/vue-multiselect.min.css" />
<style src="@/vendor/libs/vue-multiselect/vue-multiselect.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/typography.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/editor.scss" lang="scss"></style>

<style lang="scss">
  .ql-container.ql-snow {
    height: 400px;
  }
</style>

<script>
import Multiselect from 'vue-multiselect'

export default {
  name: 'pages-article-edit',
  metaInfo: {
    title: 'Article edit - Pages'
  },
  components: {
    Multiselect,
    quillEditor: () => import('vue-quill-editor/dist/vue-quill-editor').then(m => m.quillEditor).catch(() => {})
  },
  data: () => ({
    articleData: {
      id: 563,
      created_at: '03/30/2018',
      title: 'What Is The Big R For Marketing Your Business',
      slug: 'what-is-the-big-r-for-marketing-your-business',
      tags: ['Productivity', 'Creativity', 'Writing', 'Inspiration', 'Psychology'],
      status: 1,
      content: 'Article content',
      main_image: '13.jpg',

      author: {
        avatar: '1-small.png',
        username: 'mgreene',
        name: 'Mike Greene'
      },

      meta: {
        title: 'What Is The Big R For Marketing Your Business',
        description: 'Read What Is The Big R For Marketing Your Business',
        keywords: 'Productivity, Creativity, Writing, Inspiration, Psychology'
      }
    },

    mainFileSelect: null,

    editorOptions: {
      modules: {
        toolbar: [
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }, { 'font': [] }, { 'size': [] }],
          ['bold', 'italic', 'underline', 'strike'],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'script': 'sub' }, { 'script': 'super' }],
          ['blockquote', 'code-block'],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
          [{ 'direction': 'rtl' }, { 'align': [] }],
          ['link', 'image', 'video'],
          ['clean']
        ]
      }
    }
  }),
  methods: {
    addTag (newTag) {
      this.articleData.tags.push(newTag)
    }
  }
}
</script>
