// angular-demo/src/app/+pages/authentication-register-v1/authentication-register-v1.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-authentication-register-v1',
  templateUrl: './authentication-register-v1.component.html',
  styleUrls: [
    '../../../vendor/styles/pages/authentication.scss'
  ]
})
export class AuthenticationRegisterV1Component {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Register v1 - Pages';
  }

  credentials = {
    name: '',
    email: '',
    password: ''
  };

}

<div class="authentication-wrapper authentication-1 px-4">
  <div class="authentication-inner py-5">

    <!-- Logo -->
    <div class="d-flex justify-content-center align-items-center">
      <div class="ui-w-60">
        <div class="w-100 position-relative" style="padding-bottom: 54%">
          <svg class="w-100 h-100 position-absolute" viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path class="fill-primary" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
        </div>
      </div>
    </div>
    <!-- / Logo -->

    <!-- Form -->
    <form class="my-5">
      <div class="form-group">
        <label class="form-label">Your name</label>
        <input [(ngModel)]="credentials.name" name="name" type="text" class="form-control">
      </div>
      <div class="form-group">
        <label class="form-label">Your email</label>
        <input [(ngModel)]="credentials.email" name="email" type="text" class="form-control">
      </div>
      <div class="form-group">
        <label class="form-label">Password</label>
        <input [(ngModel)]="credentials.password" name="password" type="password" class="form-control">
      </div>
      <button type="button" class="btn btn-primary btn-block mt-4">Sign Up</button>
      <div class="bg-lightest text-muted small p-2 mt-4">
        By clicking "Sign Up", you agree to our
        <a href="javascript:void(0)">terms of service and privacy policy</a>. We’ll occasionally send you account related emails.
      </div>
    </form>
    <!-- / Form -->

    <div class="text-center text-muted">
      Already have an account? <a href="javascript:void(0)">Sign In</a>
    </div>

  </div>
</div>

// vue-demo-cli2-deprecated/src/components/pages/AuthenticationRegisterV1.vue
<template>
  <div class="authentication-wrapper authentication-1 px-4">
    <div class="authentication-inner py-5">

      <!-- Logo -->
      <div class="d-flex justify-content-center align-items-center">
        <div class="ui-w-60">
          <div class="w-100 position-relative" style="padding-bottom: 54%">
            <svg class="w-100 h-100 position-absolute" viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path class="fill-primary" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
          </div>
        </div>
      </div>
      <!-- / Logo -->

      <!-- Form -->
      <form class="my-5">
        <b-form-group label="Your name">
          <b-input v-model="credentials.name" />
        </b-form-group>
        <b-form-group label="Your email">
          <b-input v-model="credentials.email" />
        </b-form-group>
        <b-form-group label="Password">
          <b-input type="password" v-model="credentials.password" />
        </b-form-group>
        <b-btn variant="primary" :block="true" class="mt-4">Sign Up</b-btn>
        <div class="bg-lightest text-muted small p-2 mt-4">
          By clicking "Sign Up", you agree to our
          <a href="javascript:void(0)">terms of service and privacy policy</a>.
          We’ll occasionally send you account related emails.
        </div>
      </form>
      <!-- / Form -->

      <div class="text-center text-muted">
        Already have an account? <a href="javascript:void(0)">Sign In</a>
      </div>

    </div>
  </div>
</template>

<!-- Page -->
<style src="@/vendor/styles/pages/authentication.scss" lang="scss"></style>

<script>
export default {
  name: 'pages-authentication-register-v1',
  metaInfo: {
    title: 'Register v1 - Pages'
  },
  data: () => ({
    credentials: {
      name: '',
      email: '',
      password: ''
    }
  })
}
</script>
