// angular-demo/src/app/+pages/ecommerce-product-edit/ecommerce-product-edit.component.ts
/* tslint:disable:max-line-length */
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-ecommerce-product-edit',
  templateUrl: './ecommerce-product-edit.component.html',
  styleUrls: [
    '../../../vendor/libs/ng-select/ng-select.scss',
    '../../../vendor/libs/quill/typography.scss',
    '../../../vendor/libs/quill/editor.scss',
    '../../../vendor/styles/pages/products.scss',
    './ecommerce-product-edit.component.scss'
  ]
})
export class EcommerceProductEditComponent {
  isRTL: boolean;
  isIE10: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Product edit - Pages';
    this.isRTL = appService.isRTL;
    this.isIE10 = this.appService.isIE10;
  }

  // Selects
  statuses = [[1, 'Published'], [ 2, 'Out of stock'], [3, 'Pending'], [4, 'Hidden']];
  categories = [ 'Computers', 'Portable tech', 'Mobile phones', 'Audio', 'Photo and video', 'Video game consoles' ];
  brands = [ 'Apple', 'Blueberry', 'Samsung', 'LG', 'Asus', 'Sony', 'Honor', 'Huawei', 'Xiaomi' ];
  storages = [{ label: '8GB', value: '8GB' }, { label: '16GB', value: '16GB' }, { label: '32GB', value: '32GB' }, { label: '64GB', value: '64GB' }, { label: '128GB', value: '128GB' }];
  colors = [{ label: 'Black', value: '#000' }, { label: 'White', value: '#fff' }, { label: 'Silver', value: 'silver' }, { label: 'Gray', value: 'gray' }, { label: 'Green', value: '#5f9ea0' }, { label: 'Gold', value: '#c5baab' }, { label: 'Pink', value: 'pink' }, { label: 'Red', value: 'red' }];
  warranties = [{ label: 'Standard - 1 year', value: 'Standard - 1 year' }, { label: 'Extended - 2 years | $99', value: 'Extended - 2 years | $99' }];
  shipsFrom = [{ label: 'USA', value: 'USA' }, { label: 'China', value: 'China' }, { label: 'France', value: 'France' }, { label: 'Germany', value: 'Germany' }, { label: 'UK', value: 'UK' }];

  // Product data

  productData = {
    id: 3455632,
    title: 'Samsung Galaxy S7 Edge',
    price: 1049,
    category: 'Mobile phones',
    inStock: 123,
    tax: 25,
    status: 1,

    // Options
    options: {
      brand: 'Samsung',
      storages: ['32GB', '64GB'],
      colors: ['#000', '#5f9ea0', '#c5baab'],
      warranties: ['Standard - 1 year', 'Extended - 2 years | $99'],
      shipsFrom: ['USA', 'China', 'Germany']
    },

    // Meta
    meta: {
      title: 'Samsung Galaxy S7 Edge',
      description: 'Buy Samsung Galaxy S7 Edge!',
      keywords: 'Mobile, Smartphone, Samsung, Galaxy, S3, Edge'
    },

    // Images
    images: <any[]> [
      { image: 's7edge-1.jpg', primary: true },
      { image: 's7edge-2.jpg' },
      { image: 's7edge-3.jpg' },
      { image: 's7edge-4.jpg' }
    ],

    // Discounts
    discounts: [
      { discount: '5', type: 'General', code: '', quantity: '100', period: { start: null, end: null } },
      { discount: '10', type: 'General', code: '', quantity: '', period: { start: '02/01/2018', end: '03/01/2018' } },
      { discount: '20', type: 'Code', code: 'G446DJ', quantity: '100', period: { start: '02/12/2018', end: '03/05/2018' } },
      { discount: '15', type: 'Code', code: 'HDA56D', quantity: '30', period: { start: '02/23/2018', end: '04/06/2018' } },
      { discount: '10', type: 'General', code: '', quantity: '', period: { start: '05/14/2018', end: '05/30/2018' } }
    ],

    // Description
    description: 'Item description'
  };

  editorOptions = {
    modules: {
      toolbar: [
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }, { 'font': [] }, { 'size': [] }],
        ['bold', 'italic', 'underline', 'strike'],
        [{ 'color': [] }, { 'background': [] }],
        [{ 'script': 'sub' }, { 'script': 'super' }],
        ['blockquote', 'code-block'],
        [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
        [{ 'direction': 'rtl' }, { 'align': [] }],
        ['link', 'image', 'video'],
        ['clean']
      ]
    }
  };

  setPrimaryImage (index) {
    const images = this.productData['images'].slice(0);
    images.map((img, _index) => { img.primary = index === _index; });
    this.productData['images'] = images;
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  Edit product <span class="text-muted">#{{productData.id}}</span>
</h4>

<ngb-tabset class="nav-tabs-top nav-responsive-sm">
  <ngb-tab title="Basic info">
    <ng-template ngbTabContent>

      <div class="card-body">

        <div class="form-group">
          <label class="form-label">Title</label>
          <input type="text" class="form-control" [(ngModel)]="productData.title">
        </div>

        <div class="form-group">
          <label class="form-label">Price</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text">$</div>
            </div>
            <input type="text" class="form-control" [(ngModel)]="productData.price">
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">Items in stock</label>
          <input type="text" class="form-control" [(ngModel)]="productData.inStock">
        </div>

        <div class="form-group">
          <label class="form-label">Tax</label>
          <div class="input-group">
            <input type="text" class="form-control" [(ngModel)]="productData.tax">
            <div class="input-group-append">
              <div class="input-group-text">%</div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">Status</label>
          <select class="custom-select" [(ngModel)]="productData.status">
            <option *ngFor="let i of statuses" [value]="i[0]">{{i[1]}}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-label">Category</label>
          <select class="custom-select" [(ngModel)]="productData.category">
            <option *ngFor="let category of categories" [value]="category">{{category}}</option>
          </select>
        </div>

      </div>
      <hr class="m-0">

      <div class="card-body">
        <h6 class="small font-weight-semibold mb-4">Options <span class="text-muted font-weight-normal">(depending on category)</span></h6>

        <div class="form-group">
          <label class="form-label">Brand</label>
          <select class="custom-select" [(ngModel)]="productData.options.brand">
            <option *ngFor="let brand of brands" [value]="brand">{{brand}}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-label">Storages</label>
          <ng-select
            [items]="storages"
            bindLabel="label"
            bindValue="value"
            [multiple]="true"
            [(ngModel)]="productData.options.storages">
          </ng-select>
        </div>

        <div class="form-group">
          <label class="form-label">Colors</label>
          <ng-select
            [items]="colors"
            bindLabel="label"
            bindValue="value"
            [multiple]="true"
            [(ngModel)]="productData.options.colors">
            <ng-template ng-label-tmp let-item="item" let-clear="clear">
              <span class="ng-value-label line-height-1">
                <span class="ui-product-color ui-product-color-sm" [style.background]="item.value"></span>
                <span class="align-middle">{{item.label}}</span>
              </span>
              <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
            </ng-template>

            <ng-template ng-option-tmp let-item="item">
              <span class="ng-value-label">
                <span class="ui-product-color ui-product-color-sm" [style.background]="item.value"></span>
                <span class="align-middle">{{item.label}}</span>
              </span>
            </ng-template>
          </ng-select>
        </div>

        <div class="form-group">
          <label class="form-label">Warranties</label>
          <ng-select
            [items]="warranties"
            bindLabel="label"
            bindValue="value"
            [multiple]="true"
            [(ngModel)]="productData.options.warranties">
          </ng-select>
        </div>

        <div class="form-group">
          <label class="form-label">Ships from</label>
          <ng-select
            [items]="shipsFrom"
            bindLabel="label"
            bindValue="value"
            [multiple]="true"
            [(ngModel)]="productData.options.shipsFrom">
          </ng-select>
        </div>

      </div>
      <hr class="m-0">

      <div class="card-body">
        <h6 class="small font-weight-semibold mb-4">Meta</h6>

        <div class="form-group">
          <label class="form-label">Title</label>
          <input type="text" class="form-control" [(ngModel)]="productData.meta.title">
        </div>

        <div class="form-group">
          <label class="form-label">Description</label>
          <textarea class="form-control" rows="3" [(ngModel)]="productData.meta.description"></textarea>
        </div>

        <div class="form-group">
          <label class="form-label">Keywords</label>
          <input type="text" class="form-control" [(ngModel)]="productData.meta.keywords">
        </div>

      </div>

    </ng-template>
  </ngb-tab>
  <ngb-tab title="Description">
    <ng-template ngbTabContent>
      <div class="card-body">

        <quill-editor [(ngModel)]="productData.description" placeholder="Type something" *ngIf="!isIE10">
          <div quill-editor-toolbar>
            <span class="ql-formats">
              <select class="ql-font"></select>
              <select class="ql-size"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-color"></select>
              <select class="ql-background"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-script" value="sub"></button>
              <button class="ql-script" value="super"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-header" value="1"></button>
              <button class="ql-header" value="2"></button>
              <button class="ql-blockquote"></button>
              <button class="ql-code-block"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              <button class="ql-list" value="bullet"></button>
              <button class="ql-indent" value="-1"></button>
              <button class="ql-indent" value="+1"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-direction" value="rtl"></button>
              <select class="ql-align"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-link"></button>
              <button class="ql-image"></button>
              <button class="ql-video"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-clean"></button>
            </span>
          </div>
        </quill-editor>

        <!-- Fallback -->
        <textarea [(ngModel)]="productData.description" class="form-control" style="height: 600px" *ngIf="isIE10"></textarea>

      </div>
    </ng-template>
  </ngb-tab>
  <ngb-tab title="Discounts">
    <ng-template ngbTabContent>

      <div class="card-body">

        <div class="table-responsive">
          <table class="table product-discounts-edit">
            <thead>
              <tr>
                <th>Discount</th>
                <th>Type</th>
                <th>Code</th>
                <th>Quantity</th>
                <th>Period</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let discount of productData.discounts; let i = index">
                <td>
                  <div class="input-group">
                    <input type="text" class="form-control" [(ngModel)]="discount.discount">
                    <div class="input-group-append">
                      <div class="input-group-text">%</div>
                    </div>
                  </div>
                </td>
                <td>
                  <select class="custom-select" [(ngModel)]="discount.type">
                    <option *ngFor="let discountType of ['General', 'Code']" [value]="discountType">{{discountType}}</option>
                  </select>
                </td>
                <td><input type="text" class="form-control" [(ngModel)]="discount.code" [disabled]="discount.type !== 'Code'"></td>
                <td><input type="text" class="form-control" [(ngModel)]="discount.quantity"></td>
                <td>
                  <custom-daterange-picker [(ngModel)]="discount.period"></custom-daterange-picker>
                </td>
                <td>
                  <a (click)="productData.discounts.splice(i, 1)" href="javascript:void(0)" class="btn btn-default md-btn-flat icon-btn btn-sm"><i class="ion ion-md-close"></i></a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <button (click)="productData.discounts.push({ discount: '', type: 'General', code: '', quantity: '', start_date: '', end_date: '' })" type="button" class="btn btn-outline-primary">
          <i class="ion ion-md-add"></i>&nbsp; Add discount
        </button>

      </div>


    </ng-template>
  </ngb-tab>
  <ngb-tab title="Images">
    <ng-template ngbTabContent>
      <div class="card-body">

        <div [sortablejs]="productData.images" [sortablejsOptions]="{ animation: 150, handle: '.product-image-move' }">
          <div *ngFor="let i of productData.images; let ind = index" class="media align-items-center bg-white ui-bordered py-3 mb-2">

            <div class="product-image-move ion ion-ios-move text-muted text-big p-4"></div>
            <a [href]="'assets/img/uikit/' + i.image" target="_blank" class="d-block ui-w-100 mr-4">
              <img [src]="'assets/img/uikit/' + i.image" class="img-fluid" alt="">
            </a>
            <div class="media-body">
              <input type="text" [value]="'example.com/assets/img/uikit/' + i.image" class="form-control form-control-sm bg-transparent border-light mb-2" readonly>
              <label class="switcher switcher-sm">
                <input type="radio" name="product-primary-image" class="switcher-input" [checked]="i.primary" (change)="setPrimaryImage(ind)">
                <span class="switcher-indicator">
                  <span class="switcher-yes"></span>
                  <span class="switcher-no"></span>
                </span>
                <span class="switcher-label">Primary image</span>
              </label>
            </div>
            <button (click)="productData.images.splice(ind, 1)" type="button" class="btn btn-outline-danger borderless icon-btn d-block mx-4">
              <i class="ion ion-md-close"></i>
            </button>

          </div>
        </div>
        <button type="button" class="btn btn-outline-primary mt-3">
          <i class="ion ion-md-cloud-upload"></i>&nbsp; Upload images
        </button>

      </div>
    </ng-template>
  </ngb-tab>
</ngb-tabset>

<div class="text-right mt-3">
  <button type="button" class="btn btn-default">Cancel</button> &nbsp;
  <button type="button" class="btn btn-primary">Save changes</button>
</div>

// vue-demo-cli2-deprecated/src/components/pages/ECommerceProductEdit.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      Edit product <span class="text-muted">#{{productData.id}}</span>
    </h4>

    <b-tabs class="nav-tabs-top nav-responsive-sm">
      <b-tab title="Basic info" active>
        <b-card-body>

          <b-form-group label="Title">
            <b-input v-model="productData.title" />
          </b-form-group>

          <b-form-group label="Price">
            <b-input-group prepend="$">
              <b-input v-model="productData.price" />
            </b-input-group>
          </b-form-group>

          <b-form-group label="Items in stock">
            <b-input v-model="productData.in_stock" />
          </b-form-group>

          <b-form-group label="Tax">
            <b-input-group append="%">
              <b-input v-model="productData.tax" />
            </b-input-group>
          </b-form-group>

          <b-form-group label="Status">
            <b-select v-model="productData.status" :options="{ 1: 'Published', 2: 'Out of stock', 3: 'Pending', 4: 'Hidden' }" />
          </b-form-group>

          <b-form-group label="Category">
            <b-select v-model="productData.category" :options="['Computers', 'Portable tech', 'Mobile phones', 'Audio', 'Photo and video', 'Video game consoles']" />
          </b-form-group>

        </b-card-body>
        <hr class="m-0">
        <b-card-body>

          <h6 class="small font-weight-semibold mb-4">Options <span class="text-muted font-weight-normal">(depending on category)</span></h6>

          <b-form-group label="Brand">
            <b-select v-model="productData.options.brand" :options="['Apple', 'Blueberry', 'Samsung', 'LG', 'Asus', 'Sony', 'Honor', 'Huawei', 'Xiaomi']" />
          </b-form-group>

          <b-form-group label="Storages">
            <multiselect v-model="productData.options.storages" :multiple="true" :options="['8GB', '16GB', '32GB', '64GB', '128GB']" />
          </b-form-group>

          <b-form-group label="Colors">
            <multiselect v-model="productData.options.colors" :multiple="true" :trackBy="'1'" :options="[['Black', '#000'], ['White', '#fff'], ['Silver', 'silver'], ['Gray', 'gray'], ['Green', '#5f9ea0'], ['Gold', '#c5baab'], ['Pink', 'pink'], ['Red', 'red']]">
              <template slot="option" slot-scope="props">
                <span class="ui-product-color align-middle" :style="{background: props.option[1]}"></span>
                <span class="align-middle">{{props.option[0]}}</span>
              </template>
              <template slot="tag" slot-scope="props">
                <span class="multiselect__tag">
                  <span class="badge badge-dot" :style="{background: props.option[1]}"></span>&nbsp; {{props.option[0]}}
                  <i class="multiselect__tag-icon" @click="props.remove(props.option)"></i>
                </span>
              </template>
            </multiselect>
          </b-form-group>

          <b-form-group label="Warranties">
            <multiselect v-model="productData.options.warranties" :multiple="true" :options="['Standard - 1 year', 'Extended - 2 years | $99']" />
          </b-form-group>

          <b-form-group label="Ships from">
            <multiselect v-model="productData.options.ships_from" :multiple="true" :options="['USA', 'China', 'France', 'Germany', 'UK']" />
          </b-form-group>

        </b-card-body>
        <hr class="m-0">
        <b-card-body>

          <h6 class="small font-weight-semibold mb-4">Meta</h6>

          <b-form-group label="Title">
            <b-input v-model="productData.meta.title" />
          </b-form-group>

          <b-form-group label="Description">
            <b-textarea v-model="productData.meta.description" :rows="3" />
          </b-form-group>

          <b-form-group label="Keywords">
            <b-input v-model="productData.meta.keywords" />
          </b-form-group>

        </b-card-body>
      </b-tab>
      <b-tab title="Description">
        <b-card-body>

          <quill-editor v-model="productData.description" :options="editorOptions" v-if="!isIE10Mode" />
          <!-- Fallback -->
          <b-textarea v-model="productData.description" style="height: 600px" v-if="isIE10Mode" />

        </b-card-body>
      </b-tab>
      <b-tab title="Discounts">
        <b-card-body>

          <div class="table-responsive">
            <b-table :items="productData.discounts" :fields="['type','code','quantity','start_date','end_date',{ key: 'actions', label: ' ' }]" class="product-item-discounts-table">
              <template slot="discount" slot-scope="data">
                <b-input-group>
                  <b-input v-model="data.item.discount" />
                </b-input-group>
              </template>
              <template slot="type" slot-scope="data">
                <b-select v-model="data.item.type" :options="['General', 'Code']" />
              </template>
              <template slot="code" slot-scope="data">
                <b-input v-model="data.item.code" :disabled="data.item.type !== 'Code'" />
              </template>
              <template slot="quantity" slot-scope="data">
                <b-input v-model="data.item.quantity" />
              </template>
              <template slot="start_date" slot-scope="data">
                <flat-pickr v-model="data.item.start_date" :config="{ altInput: true, animate: !isRTL, dateFormat: 'm/d/Y', altFormat: 'm/d/Y' }" :placeholder="!isIEMode ? 'Select a start date' : null" />
              </template>
              <template slot="end_date" slot-scope="data">
                <flat-pickr v-model="data.item.end_date" :config="{ altInput: true, animate: !isRTL, dateFormat: 'm/d/Y', altFormat: 'm/d/Y', minDate: data.item.start_date }" :placeholder="!isIEMode ? 'Select an end date' : null" />
              </template>
              <template slot="actions" slot-scope="data">
                <b-btn @click="productData.discounts.splice(data.index, 1)" variant="default md-btn-flat icon-btn" size="sm">
                  <i class="ion ion-md-close"></i>
                </b-btn>
              </template>
            </b-table>
          </div>
          <b-btn variant="outline-primary" @click="productData.discounts.push({ discount: '', type: 'General', code: '', quantity: '', start_date: '', end_date: '' })">
            <i class="ion ion-md-add"></i>&nbsp; Add discount
          </b-btn>

        </b-card-body>
      </b-tab>
      <b-tab title="Images">
        <b-card-body>
          <draggable v-model="productData.images" :options="draggableOptions">

            <div v-for="(i, index) in productData.images" :key="i.image" class="media align-items-center bg-white ui-bordered py-3 mb-2">
              <div class="product-image-move ion ion-ios-move text-muted text-big p-4"></div>
              <a :href="`${baseUrl}img/uikit/${i.image}`" target="_blank" class="d-block ui-w-100 mr-4">
                <img :src="`${baseUrl}img/uikit/${i.image}`" class="img-fluid" alt="">
              </a>
              <div class="media-body">
                <input type="text" :value="`example.com/img/uikit/${i.image}`" class="form-control form-control-sm bg-transparent border-light mb-2" readonly>
                <label class="switcher switcher-sm">
                  <input type="radio" name="product-primary-image" class="switcher-input" :checked="i.primary" @change="setPrimaryImage(index)">
                  <span class="switcher-indicator">
                    <span class="switcher-yes"></span>
                    <span class="switcher-no"></span>
                  </span>
                  <span class="switcher-label">Primary image</span>
                </label>
              </div>
              <b-btn @click="productData.images.splice(index, 1)" variant="outline-danger borderless icon-btn" class="d-block mx-4">
                <i class="ion ion-md-close"></i>
              </b-btn>
            </div>

          </draggable>
          <b-btn variant="outline-primary" class="mt-3">
            <i class="ion ion-md-cloud-upload"></i>&nbsp; Upload images
          </b-btn>

        </b-card-body>
      </b-tab>
    </b-tabs>

    <div class="text-right mt-3">
      <b-btn variant="default">Cancel</b-btn> &nbsp;
      <b-btn variant="primary">Save changes</b-btn>
    </div>

  </div>
</template>

<style src="vue-multiselect/dist/vue-multiselect.min.css" />
<style src="@/vendor/libs/vue-multiselect/vue-multiselect.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/typography.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/editor.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-flatpickr-component/vue-flatpickr-component.scss" lang="scss"></style>

<style lang="scss">
  .ql-container.ql-snow {
    height: 600px;
  }
</style>

<!-- Page -->
<style src="@/vendor/styles/pages/products.scss" lang="scss"></style>

<script>
import Multiselect from 'vue-multiselect'
import flatPickr from 'vue-flatpickr-component'
import draggable from 'vuedraggable'

export default {
  name: 'pages-e-commerce-product-edit',
  metaInfo: {
    title: 'Product edit - Pages'
  },
  components: {
    Multiselect,
    quillEditor: () => import('vue-quill-editor/dist/vue-quill-editor').then(m => m.quillEditor).catch(() => {}),
    flatPickr,
    draggable
  },
  data: () => ({
    productData: {
      id: 3455632,
      title: 'Samsung Galaxy S7 Edge',
      price: 1049,
      category: 'Mobile phones',
      in_stock: 123,
      tax: 25,
      status: 1,

      // Options
      options: {
        brand: 'Samsung',
        storages: ['32GB', '64GB'],
        colors: [['Black', '#000'], ['Green', '#5f9ea0'], ['Gold', '#c5baab']],
        warranties: ['Standard - 1 year', 'Extended - 2 years | $99'],
        ships_from: ['USA', 'China', 'Germany']
      },

      // Meta
      meta: {
        title: 'Samsung Galaxy S7 Edge',
        description: 'Buy Samsung Galaxy S7 Edge!',
        keywords: 'Mobile, Smartphone, Samsung, Galaxy, S3, Edge'
      },

      // Images
      images: [
        { image: 's7edge-1.jpg', primary: true },
        { image: 's7edge-2.jpg' },
        { image: 's7edge-3.jpg' },
        { image: 's7edge-4.jpg' }
      ],

      // Discounts
      discounts: [
        { discount: '5', type: 'General', code: '', quantity: '100', start_date: '', end_date: '' },
        { discount: '10', type: 'General', code: '', quantity: '', start_date: '02/01/2018', end_date: '03/01/2018' },
        { discount: '20', type: 'Code', code: 'G446DJ', quantity: '100', start_date: '02/12/2018', end_date: '03/05/2018' },
        { discount: '15', type: 'Code', code: 'HDA56D', quantity: '30', start_date: '02/23/2018', end_date: '04/06/2018' },
        { discount: '10', type: 'General', code: '', quantity: '', start_date: '05/14/2018', end_date: '05/30/2018' }
      ],

      // Description
      description: 'Item description'
    },

    editorOptions: {
      modules: {
        toolbar: [
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }, { 'font': [] }, { 'size': [] }],
          ['bold', 'italic', 'underline', 'strike'],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'script': 'sub' }, { 'script': 'super' }],
          ['blockquote', 'code-block'],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
          [{ 'direction': 'rtl' }, { 'align': [] }],
          ['link', 'image', 'video'],
          ['clean']
        ]
      }
    },

    draggableOptions: {
      animation: 150,
      handle: '.product-image-move'
    }
  }),
  methods: {
    setPrimaryImage (index) {
      const images = this.productData.images.slice(0)
      images.map((img, _index) => { img.primary = index === _index })
      this.productData.images = images
    }
  }
}
</script>
