// angular-demo/src/app/+pages/ecommerce-order-list/ecommerce-order-list.component.ts
/// <reference types="numeral" />

import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AppService } from '../../app.service';
import * as numeral from 'numeral';

@Component({
  selector: 'app-ecommerce-order-list',
  templateUrl: './ecommerce-order-list.component.html'
})
export class EcommerceOrderListComponent {
  isRTL: boolean;

  constructor(private http: HttpClient, private appService: AppService) {
    this.appService.pageTitle = 'Order list - Pages';
    this.isRTL = appService.isRTL;
    this.loadData();
  }

  // Table

  // Options
  dataUrl = 'assets/json/pages_e-commerce_order-list.json';
  searchKeys = ['id', 'customer', 'amount'];
  sortBy = 'id';
  sortDesc = true;
  perPage = 10;

  filterVal = '';
  currentPage = 1;
  totalItems = 0;

  ordersData: Object[] = [];
  originalOrdersData: Object[] = [];

  formatPrice(price) {
    return numeral(price).format('$0,0.00');
  }

  loadData() {
    this.http.get(this.dataUrl)
      .subscribe((data: any) => {
        this.originalOrdersData = data.slice(0);
        this.update();
      });
  }

  get totalPages() {
    return Math.ceil(this.totalItems / this.perPage);
  }

  update() {
    const data = this.filter(this.originalOrdersData);

    this.totalItems = data.length;

    this.sort(data);
    this.ordersData = this.paginate(data);
  }

  filter(data) {
    const filter = this.filterVal.toLowerCase();
    return !filter ?
      data.slice(0) :
      data.filter(d => {
        return Object.keys(d)
          .filter(k => this.searchKeys.includes(k))
          .map(k => String(d[k]))
          .join('|')
          .toLowerCase()
          .indexOf(filter) !== -1 || !filter;
      });
  }

  sort(data) {
    data.sort((a: any, b: any) => {
      a = typeof(a[this.sortBy]) === 'string' ? a[this.sortBy].toUpperCase() : a[this.sortBy];
      b = typeof(b[this.sortBy]) === 'string' ? b[this.sortBy].toUpperCase() : b[this.sortBy];

      if (a < b) { return this.sortDesc ? 1 : -1; }
      if (a > b) { return this.sortDesc ? -1 : 1; }
      return 0;
    });
  }

  paginate(data) {
    const perPage = parseInt(String(this.perPage), 10);
    const offset = (this.currentPage - 1) * perPage;

    return data.slice(offset, offset + perPage);
  }

  setSort(key) {
    if (this.sortBy !== key) {
      this.sortBy = key;
      this.sortDesc = false;
    } else {
      this.sortDesc = !this.sortDesc;
    }

    this.currentPage = 1;
    this.update();
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  Orders
</h4>

<div class="card">

  <!-- Table controls -->
  <div class="card-body">

    <div class="row">
      <div class="col">
        Per page: &nbsp;
        <select
          [(ngModel)]="perPage"
          (change)="update()"
          class="custom-select custom-select-sm d-inline-block w-auto">
          <option *ngFor="let limit of [10, 20, 30, 40, 50]">{{limit}}</option>
        </select>
      </div>
      <div class="col">
        <input type="text"
          [(ngModel)]="filterVal"
          (input)="currentPage = 1; update()"
          class="form-control form-control-sm d-inline-block w-auto float-sm-right"
          placeholder="Search...">
      </div>
    </div>

  </div>
  <!-- / Table controls -->

  <!-- Table -->
  <hr class="border-light m-0">
  <div class="table-responsive">
    <table class="table table-striped table-bordered card-table">
      <thead>
        <tr>
          <th class="text-nowrap cursor-pointer" (click)="setSort('id')">
            ID<i class="ion text-muted ml-2" *ngIf="sortBy=='id'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('customer')">
            Customer<i class="ion text-muted ml-2" *ngIf="sortBy=='customer'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('amount')">
            Amount<i class="ion text-muted ml-2" *ngIf="sortBy=='amount'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('date')">
            Date<i class="ion text-muted ml-2" *ngIf="sortBy=='date'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('status')">
            Status<i class="ion text-muted ml-2" *ngIf="sortBy=='status'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let order of ordersData">
          <td class="align-middle">{{order.id}}</td>
          <td class="align-middle">{{order.customer}}</td>
          <td class="align-middle">{{formatPrice(order.amount)}}</td>
          <td class="align-middle">{{order.date}}</td>
          <td class="align-middle">
            <span class="badge badge-outline-success" *ngIf="order.status === 1">Shipped</span>
            <span class="badge badge-outline-warning" *ngIf="order.status === 2">Pending</span>
            <span class="badge badge-outline-info" *ngIf="order.status === 3">Sent</span>
            <span class="badge badge-outline-danger" *ngIf="order.status === 4">Cancelled</span>
          </td>
          <td class="text-nowrap align-middle">
            <a href="javascript:void(0)" class="btn btn-default btn-xs icon-btn md-btn-flat" ngbTooltip="Show"><i class="ion ion-md-eye"></i></a>&nbsp;
            <a href="javascript:void(0)" class="btn btn-default btn-xs icon-btn md-btn-flat" ngbTooltip="Edit"><i class="ion ion-md-create"></i></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- / Table -->

  <!-- Pagination -->
  <div class="card-body py-0">

    <div class="row">
      <div class="col-sm text-sm-left text-center pt-3">
        <span class="text-muted" *ngIf="totalItems">Page {{ currentPage }} of {{ totalPages }}</span>
      </div>
      <div class="col-sm pt-3">
        <ngb-pagination
          [collectionSize]="totalItems"
          [pageSize]="perPage"
          [(page)]="currentPage"
          (pageChange)="update()"
          size="sm"
          class="d-flex justify-content-center justify-content-sm-end m-0"></ngb-pagination>
      </div>
    </div>

  </div>
  <!-- / Pagination -->
</div>

// vue-demo-cli2-deprecated/src/components/pages/ECommerceOrderList.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      Orders
    </h4>

    <b-card no-body>

      <!-- Table controls -->
      <b-card-body>

        <div class="row">
          <div class="col">
            Per page: &nbsp;
            <b-select size="sm" v-model="perPage" :options="[10, 20, 30, 40, 50]" class="d-inline-block w-auto" />
          </div>
          <div class="col">
            <b-input size="sm" placeholder="Search..." class="d-inline-block w-auto float-sm-right" @input="filter($event)" />
          </div>
        </div>

      </b-card-body>
      <!-- / Table controls -->

      <!-- Table -->
      <hr class="border-light m-0">
      <div class="table-responsive">

        <b-table
          :items="ordersData"
          :fields="fields"
          :sort-by.sync="sortBy"
          :sort-desc.sync="sortDesc"
          :striped="true"
          :bordered="true"
          :current-page="currentPage"
          :per-page="perPage"
          class="orders-table card-table">

          <template slot="status" slot-scope="data">
            <b-badge variant="outline-success" v-if="data.item.status === 1">Shipped</b-badge>
            <b-badge variant="outline-warning" v-if="data.item.status === 2">Pending</b-badge>
            <b-badge variant="outline-info" v-if="data.item.status === 3">Sent</b-badge>
            <b-badge variant="outline-danger" v-if="data.item.status === 4">Cancelled</b-badge>
          </template>

          <template slot="actions" slot-scope="data">
            <b-btn variant="default btn-xs icon-btn md-btn-flat" v-b-tooltip.hover title="Show"><i class="ion ion-md-eye"></i></b-btn>
            <b-btn variant="default btn-xs icon-btn md-btn-flat" v-b-tooltip.hover title="Edit"><i class="ion ion-md-create"></i></b-btn>
          </template>
        </b-table>

      </div>

      <!-- Pagination -->
      <b-card-body class="pt-0 pb-3">

        <div class="row">
          <div class="col-sm text-sm-left text-center pt-3">
            <span class="text-muted" v-if="totalItems">Page {{ currentPage }} of {{ totalPages }}</span>
          </div>
          <div class="col-sm pt-3">
            <b-pagination class="justify-content-center justify-content-sm-end m-0"
              v-if="totalItems"
              v-model="currentPage"
              :total-rows="totalItems"
              :per-page="perPage"
              size="sm" />
          </div>
        </div>

      </b-card-body>
      <!-- / Pagination -->

    </b-card>
  </div>
</template>

<script>
import * as numeral from 'numeral'

export default {
  name: 'pages-e-commerce-order-list',
  metaInfo: {
    title: 'Order list - Pages'
  },

  data: () => ({
    // Options
    dataUrl: 'json/pages_e-commerce_order-list.json',
    searchKeys: ['id', 'customer', 'amount'],
    sortBy: 'id',
    sortDesc: true,
    perPage: 10,

    fields: [
      { key: 'id', sortable: true, tdClass: 'align-middle' },
      { key: 'customer', sortable: true, tdClass: 'align-middle' },
      { key: 'amount', sortable: true, formatter: value => numeral(value).format('$0,0.00'), tdClass: 'align-middle' },
      { key: 'date', sortable: true, tdClass: 'align-middle' },
      { key: 'status', sortable: true, tdClass: 'align-middle' },
      { key: 'actions', label: ' ', tdClass: 'text-nowrap align-middle' }
    ],

    ordersData: [],
    originalOrdersData: [],

    currentPage: 1
  }),

  computed: {
    totalItems () {
      return this.ordersData.length
    },
    totalPages () {
      return Math.ceil(this.totalItems / this.perPage)
    }
  },

  methods: {
    filter (value) {
      const val = value.toLowerCase()
      const filtered = this.originalOrdersData.filter(d => {
        return Object.keys(d)
          .filter(k => this.searchKeys.includes(k))
          .map(k => String(d[k]))
          .join('|')
          .toLowerCase()
          .indexOf(val) !== -1 || !val
      })
      this.ordersData = filtered
    }
  },

  created () {
    const req = new XMLHttpRequest()
    req.open('GET', `${this.baseUrl}${this.dataUrl}`)

    req.onload = () => {
      const data = JSON.parse(req.response)
      this.ordersData = data
      this.originalOrdersData = data.slice(0)
    }

    req.send()
  }
}
</script>
