// vue-demo-cli2-deprecated/src/cui-components/CuiModals.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Modals</h3>

    <h4 class="ui-block-heading">Default modals</h4>

    <div class="cui-example">
      <b-radio-group v-model="defaultModalSize" :options="sizes" name="modals-default-size" class="mb-3" />
      <b-btn variant="primary" v-b-modal.modals-default>Show</b-btn>

      <!-- Modal template -->
      <b-modal id="modals-default" :size="defaultModalSize">
        <div slot="modal-title">
          Payment <span class="font-weight-light">Information</span><br>
          <small class="text-muted">We need payment information to process your order.</small>
        </div>

        <b-form-row>
          <b-form-group label="Card number" class="col">
            <b-input placeholder="XXXX XXXX XXXX XXXX" />
          </b-form-group>
        </b-form-row>
        <b-form-row>
          <b-form-group label="Expiration date" class="col mb-0">
            <b-input placeholder="DD / MM" />
          </b-form-group>
          <b-form-group label="Card holder" class="col mb-0">
            <b-input placeholder="Name on card" />
          </b-form-group>
        </b-form-row>
      </b-modal>
    </div>

    <h4 class="ui-block-heading">Top modals</h4>

    <div class="cui-example">
      <b-radio-group v-model="topModalSize" :options="sizes" name="modals-top-size" class="mb-3" />
      <b-btn variant="primary" v-b-modal.modals-top>Show</b-btn>

      <!-- Modal template -->
      <b-modal id="modals-top" :size="topModalSize" class="modal-top">
        <div slot="modal-title">
          Payment <span class="font-weight-light">Information</span><br>
          <small class="text-muted">We need payment information to process your order.</small>
        </div>

        <b-form-row>
          <b-form-group label="Card number" class="col">
            <b-input placeholder="XXXX XXXX XXXX XXXX" />
          </b-form-group>
        </b-form-row>
        <b-form-row>
          <b-form-group label="Expiration date" class="col mb-0">
            <b-input placeholder="DD / MM" />
          </b-form-group>
          <b-form-group label="Card holder" class="col mb-0">
            <b-input placeholder="Name on card" />
          </b-form-group>
        </b-form-row>
      </b-modal>
    </div>

    <h4 class="ui-block-heading">Slide modals</h4>

    <div class="cui-example">
      <b-btn variant="primary" @click="showSlideModal()">Show</b-btn>

      <!-- Modal template -->
      <b-modal ref="slideModal" class="modal-slide" hide-header hide-footer>
        <p class="text-center text-big mb-4">Before you proceed, you have to login to make the necessary changes</p>
        <b-btn block variant="primary" @click="hideSlideModal()">Continue</b-btn>
        <b-btn block variant="default" @click="hideSlideModal()">Cancel</b-btn>
      </b-modal>
    </div>

    <h4 class="ui-block-heading">Fill-In modals</h4>

    <div class="cui-example">
      <b-radio-group v-model="fillInModalSize" :options="sizes" name="modals-fill-in-size" class="mb-3" />
      <b-btn variant="primary" v-b-modal.modals-fill-in>Show</b-btn>

      <!-- Modal template -->
      <b-modal id="modals-fill-in" :size="fillInModalSize" class="modal-fill-in" hide-header hide-footer>
        <p class="text-white text-large font-weight-light mb-3">Subscribe to our newsletter</p>
        <b-input-group size="lg" class="mb-3">
          <b-input placeholder="Your email" class="bg-white border-0"></b-input>
          <b-input-group-btn slot="right">
            <b-btn variant="primary">Subscribe</b-btn>
          </b-input-group-btn>
        </b-input-group>
        <div class="text-center text-right text-white opacity-50">We will not sell/rent your email address</div>
      </b-modal>
    </div>

  </div>
</template>

<script>
export default {
  data: () => ({
    sizes: [
      { text: 'Small', value: 'sm' },
      { text: 'Medium', value: null },
      { text: 'Large', value: 'lg' }
    ],
    defaultModalSize: null,
    topModalSize: null,
    fillInModalSize: null
  }),
  methods: {
    showSlideModal () {
      this.$refs.slideModal.show()
    },
    hideSlideModal () {
      this.$refs.slideModal.hide()
    }
  }
}
</script>

// angular-demo/src/app/+complete-ui/cui-modals/cui-modals.component.ts
import { Component } from '@angular/core';
import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'cui-modals', // tslint:disable-line
  templateUrl: './cui-modals.component.html'
})
export class CuiModalsComponent {
  constructor(private modalService: NgbModal) {}

  open(content, options = {}) {
    this.modalService.open(content, options).result.then((result) => {
      console.log(`Closed with: ${result}`);
    }, (reason) => {
      console.log(`Dismissed ${this.getDismissReason(reason)}`);
    });
  }

  private getDismissReason(reason: any): string {
    if (reason === ModalDismissReasons.ESC) {
      return 'by pressing ESC';
    } else if (reason === ModalDismissReasons.BACKDROP_CLICK) {
      return 'by clicking on a backdrop';
    } else {
      return  `with: ${reason}`;
    }
  }
}

<div class="ui-block">
  <h3 class="ui-block-heading">Modals</h3>

  <h4 class="ui-block-heading">Default modals</h4>

  <div class="cui-example">
    <button type="button" class="btn btn-default" (click)="open(defaultModal)">Default</button>
    <button type="button" class="btn btn-default" (click)="open(defaultModal, { windowClass: 'modal-sm animate' })">Small</button>
    <button type="button" class="btn btn-default" (click)="open(defaultModal, { windowClass: 'modal-lg animate' })">Large</button>

    <!-- Modal template -->
    <ng-template #defaultModal let-c="close" let-d="dismiss">
      <div class="modal-header">
        <h5 class="modal-title">
          Payment <span class="font-weight-light">Information</span><br>
          <small class="text-muted">We need payment information to process your order.</small>
        </h5>
        <button type="button" class="close" (click)="d('Cross click')">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-row">
          <div class="form-group col">
            <label class="form-label">Card number</label>
            <input type="text" class="form-control" placeholder="XXXX XXXX XXXX XXXX">
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col mb-0">
            <label class="form-label">Expiration date</label>
            <input type="text" class="form-control" placeholder="DD / MM">
          </div>
          <div class="form-group col mb-0">
            <label class="form-label">Card holder</label>
            <input type="text" class="form-control"  placeholder="Name on card">
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" (click)="c('Close click')">Close</button>
        <button type="button" class="btn btn-primary">Save</button>
      </div>
    </ng-template>
  </div>

  <h4 class="ui-block-heading">Top modals</h4>

  <div class="cui-example">
    <button type="button" class="btn btn-default" (click)="open(topModal, { windowClass: 'modal-top' })">Default</button>
    <button type="button" class="btn btn-default" (click)="open(topModal, { windowClass: 'modal-top modal-sm' })">Small</button>
    <button type="button" class="btn btn-default" (click)="open(topModal, { windowClass: 'modal-top modal-lg' })">Large</button>

    <!-- Modal template -->
    <ng-template #topModal let-c="close" let-d="dismiss">
      <div class="modal-header">
        <h5 class="modal-title">
          Payment <span class="font-weight-light">Information</span><br>
          <small class="text-muted">We need payment information to process your order.</small>
        </h5>
        <button type="button" class="close" (click)="d('Cross click')">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-row">
          <div class="form-group col">
            <label class="form-label">Card number</label>
            <input type="text" class="form-control" placeholder="XXXX XXXX XXXX XXXX">
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col mb-0">
            <label class="form-label">Expiration date</label>
            <input type="text" class="form-control" placeholder="DD / MM">
          </div>
          <div class="form-group col mb-0">
            <label class="form-label">Card holder</label>
            <input type="text" class="form-control"  placeholder="Name on card">
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" (click)="c('Close click')">Close</button>
        <button type="button" class="btn btn-primary">Save</button>
      </div>
    </ng-template>
  </div>

  <h4 class="ui-block-heading">Slide modals</h4>

  <div class="cui-example">
    <button type="button" class="btn btn-default" (click)="open(slideModal, { windowClass: 'modal-slide' })">Show</button>

    <!-- Modal template -->
    <ng-template #slideModal let-c="close" let-d="dismiss">
      <button type="button" class="close" (click)="d('Cross click')">&times;</button>
      <div class="modal-body">
        <p class="text-center text-big mb-4">Before you proceed, you have to login to make the necessary changes</p>
        <button type="button" class="btn btn-primary btn-block">Continue</button>
        <button type="button" class="btn btn-default btn-block" (click)="c('Close click')">Cancel</button>
      </div>
    </ng-template>
  </div>

  <h4 class="ui-block-heading">Fill-In modals</h4>

  <div class="cui-example">
    <button type="button" class="btn btn-default" (click)="open(fillInModal, { windowClass: 'modal-fill-in' })">Default</button>
    <button type="button" class="btn btn-default" (click)="open(fillInModal, { windowClass: 'modal-fill-in modal-sm' })">Small</button>
    <button type="button" class="btn btn-default" (click)="open(fillInModal, { windowClass: 'modal-fill-in modal-lg' })">Large</button>

    <!-- Modal template -->
    <ng-template #fillInModal let-c="close" let-d="dismiss">
      <button type="button" class="close" (click)="d('Cross click')">&times;</button>
      <div class="modal-body">
        <p class="text-white text-large font-weight-light mb-3">Subscribe to our newsletter</p>
        <div class="input-group input-group-lg mb-3">
          <input type="text" class="form-control bg-white border-0" placeholder="Your email">
          <span class="input-group-append">
            <button class="btn btn-primary" type="button">Subscribe</button>
          </span>
        </div>
        <div class="text-center text-right text-white opacity-50">We will not sell/rent your email address</div>
      </div>
    </ng-template>
  </div>
</div>
