// vue-demo-cli2-deprecated/src/cui-components/CuiDropdowns.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Dropdowns</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example clearfix">
      <div class="dropdown-menu float-left" style="display: block; position: relative;">
        <b-dd-item><b-badge variant="success" class="float-right">34</b-badge>Action</b-dd-item>
        <b-dd-item><b-badge pill variant="primary" class="float-right">16</b-badge>Another action</b-dd-item>
        <b-dd-item disabled>Something else here</b-dd-item>
        <b-dd-divider />
        <b-dd-header>Dropdown header</b-dd-header>
        <b-dd-item active><i class="ion ion-md-cloud"></i> &nbsp;With icon</b-dd-item>
        <b-dd-item>Last action</b-dd-item>
      </div>
    </div>

    <h4 class="ui-block-heading">Hover dropdowns</h4>

    <div class="cui-example clearfix">
      <b-dd v-hover-dropdown variant="primary" text="Hover" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider />
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
    </div>

    <h4 class="ui-block-heading">Nested</h4>

    <div class="cui-example">
      <b-dd variant="default" text="Nested dropdowns" :right="isRTL">
        <b-dd-item>First action</b-dd-item>

        <div class="dropdown-toggle">
          <b-dd-item>First menu</b-dd-item>
          <div class="dropdown-menu">
            <b-dd-item>First action</b-dd-item>
            <b-dd-item>Second action</b-dd-item>

            <div class="dropdown-toggle">
              <b-dd-item>First menu</b-dd-item>
              <div class="dropdown-menu">
                <b-dd-item>First action</b-dd-item>
                <b-dd-item>Second action</b-dd-item>
              </div>
            </div>
          </div>
        </div>

        <b-dd-item>Second action</b-dd-item>

        <div class="dropdown-toggle">
          <b-dd-item>Second menu</b-dd-item>
          <div class="dropdown-menu">
            <b-dd-item>First action</b-dd-item>
            <b-dd-item>Second action</b-dd-item>
          </div>
        </div>
      </b-dd>
    </div>
  </div>
</template>

<script>
import '@/vendor/libs/hover-dropdown/HoverDropdown'

export default {}
</script>

// angular-demo/src/app/+complete-ui/cui-dropdowns/cui-dropdowns.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'cui-dropdowns', // tslint:disable-line
  templateUrl: './cui-dropdowns.component.html',
})
export class CuiDropdownsComponent {
  isRTL: boolean;

  constructor(appService: AppService) {
    this.isRTL = appService.isRTL;
  }
}

<div class="ui-block">
  <h3 class="ui-block-heading">Dropdowns</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example clearfix">
    <div class="dropdown-menu float-left" style="display: block; position: relative;">
      <a class="dropdown-item" href="javascript:void(0)"><span class="badge badge-success float-right">34</span>Action</a>
      <a class="dropdown-item" href="javascript:void(0)"><span class="badge badge-pill badge-primary float-right">16</span>Another action</a>
      <a class="dropdown-item disabled" href="javascript:void(0)">Something else here</a>
      <div class="dropdown-divider"></div>
      <h6 class="dropdown-header">Dropdown header</h6>
      <a class="dropdown-item active" href="javascript:void(0)"><i class="ion ion-md-cloud"></i> &nbsp;With icon</a>
      <a class="dropdown-item" href="javascript:void(0)">Last action</a>
    </div>
  </div>

  <h4 class="ui-block-heading">Hover dropdowns</h4>

  <div class="cui-example">
    <div ngbDropdown hoverDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-primary dropdown-toggle" ngbDropdownToggle>Hover</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Nested</h4>

  <div class="cui-example">
    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button class="btn btn-default" ngbDropdownToggle>Nested dropdowns</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">First action</a>

        <!-- Level two -->
        <div class="dropdown-toggle">
          <div class="dropdown-item">First menu</div>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="javascript:void(0)">First action</a>
            <a class="dropdown-item" href="javascript:void(0)">Second action</a>

            <!-- Level three -->
            <div class="dropdown-toggle">
              <div class="dropdown-item">Second menu</div>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="javascript:void(0)">First action</a>
                <a class="dropdown-item" href="javascript:void(0)">Second action</a>
              </div>
            </div>

          </div>
        </div>

        <a class="dropdown-item" href="javascript:void(0)">Second action</a>

        <!-- Level two -->
        <div class="dropdown-toggle">
          <div class="dropdown-item">Second menu</div>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="javascript:void(0)">First action</a>
            <a class="dropdown-item" href="javascript:void(0)">Second action</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
