// vue-demo/src/components/pages/ArticlesList.vue
<template>
  <div>
    <h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
      <div>Articles</div>
      <b-btn variant="primary btn-round" class="d-block"><span class="ion ion-md-add"></span>&nbsp; Create article</b-btn>
    </h4>

    <b-card no-body>

      <!-- Table controls -->
      <b-card-body>

        <div class="row">
          <div class="col">
            Per page: &nbsp;
            <b-select size="sm" v-model="perPage" :options="[10, 20, 30, 40, 50]" class="d-inline-block w-auto" />
          </div>
          <div class="col">
            <b-input size="sm" placeholder="Search..." class="d-inline-block w-auto float-sm-right" @input="filter($event)" />
          </div>
        </div>

      </b-card-body>
      <!-- / Table controls -->

      <!-- Table -->
      <hr class="border-light m-0">
      <div class="table-responsive">

        <b-table
          :items="articlesData"
          :fields="fields"
          :sort-by.sync="sortBy"
          :sort-desc.sync="sortDesc"
          :striped="true"
          :bordered="true"
          :current-page="currentPage"
          :per-page="perPage"
          class="card-table">

          <template slot="title" slot-scope="data">
            <a href="javascript:void(0)">{{data.item.title}}</a>
          </template>

          <template slot="status" slot-scope="data">
            <b-badge variant="outline-success" v-if="data.item.status === 1">Published</b-badge>
            <b-badge variant="outline-info" v-if="data.item.status === 2">Draft</b-badge>
            <b-badge variant="outline-default" v-if="data.item.status === 3">Deleted</b-badge>
          </template>

          <template slot="actions" slot-scope="data">
            <b-btn variant="default btn-xs icon-btn md-btn-flat" v-b-tooltip.hover title="Edit"><i class="ion ion-md-create"></i></b-btn>
            <b-btn variant="default btn-xs icon-btn md-btn-flat" v-b-tooltip.hover title="Remove"><i class="ion ion-md-close"></i></b-btn>
          </template>
        </b-table>

      </div>

      <!-- Pagination -->
      <b-card-body class="pt-0 pb-3">

        <div class="row">
          <div class="col-sm text-sm-left text-center pt-3">
            <span class="text-muted" v-if="totalItems">Page {{ currentPage }} of {{ totalPages }}</span>
          </div>
          <div class="col-sm pt-3">
            <b-pagination class="justify-content-center justify-content-sm-end m-0"
              v-if="totalItems"
              v-model="currentPage"
              :total-rows="totalItems"
              :per-page="perPage"
              size="sm" />
          </div>
        </div>

      </b-card-body>
      <!-- / Pagination -->

    </b-card>
  </div>
</template>

<script>
export default {
  name: 'pages-articles-list',
  metaInfo: {
    title: 'Articles list - Pages'
  },
  data: () => ({
    // Options
    dataUrl: 'json/pages_articles_list.json',
    searchKeys: ['id', 'title'],
    sortBy: 'id',
    sortDesc: false,
    perPage: 10,

    fields: [
      { key: 'id', sortable: true },
      { key: 'title', sortable: true, thStyle: 'min-width: 18rem' },
      { key: 'likes', sortable: true },
      { key: 'comments', sortable: true },
      { key: 'created_at', sortable: true, thClass: 'text-nowrap' },
      { key: 'status', sortable: true },
      { key: 'actions', label: ' ', tdClass: 'text-center text-nowrap' }
    ],

    articlesData: [],
    originalArticlesData: [],

    currentPage: 1
  }),

  computed: {
    totalItems () {
      return this.articlesData.length
    },
    totalPages () {
      return Math.ceil(this.totalItems / this.perPage)
    }
  },

  methods: {
    filter (value) {
      const val = value.toLowerCase()
      const filtered = this.originalArticlesData.filter(d => {
        return Object.keys(d)
          .filter(k => this.searchKeys.includes(k))
          .map(k => String(d[k]))
          .join('|')
          .toLowerCase()
          .indexOf(val) !== -1 || !val
      })
      this.articlesData = filtered
    }
  },

  created () {
    const req = new XMLHttpRequest()
    req.open('GET', `${this.baseUrl}${this.dataUrl}`)

    req.onload = () => {
      const data = JSON.parse(req.response)
      this.articlesData = data
      this.originalArticlesData = data.slice(0)
    }

    req.send()
  }
}
</script>

// angular-demo/src/app/+pages/articles-list/articles-list.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-articles-list',
  templateUrl: './articles-list.component.html'
})
export class ArticlesListComponent {
  isRTL: boolean;

  constructor(private http: HttpClient, private appService: AppService) {
    this.appService.pageTitle = 'Article list - Pages';
    this.isRTL = appService.isRTL;
    this.loadData();
  }

  // Table

  // Options
  dataUrl = 'assets/json/pages_articles_list.json';
  searchKeys = ['id', 'title'];
  sortBy = 'id';
  sortDesc = true;
  perPage = 10;

  filterVal = '';
  currentPage = 1;
  totalItems = 0;

  articlesData: Object[] = [];
  originalArticlesData: Object[] = [];

  loadData() {
    this.http.get(this.dataUrl)
      .subscribe((data: any) => {
        this.originalArticlesData = data.slice(0);
        this.update();
      });
  }

  get totalPages() {
    return Math.ceil(this.totalItems / this.perPage);
  }

  update() {
    const data = this.filter(this.originalArticlesData);

    this.totalItems = data.length;

    this.sort(data);
    this.articlesData = this.paginate(data);
  }

  filter(data) {
    const filter = this.filterVal.toLowerCase();
    return !filter ?
      data.slice(0) :
      data.filter(d => {
        return Object.keys(d)
          .filter(k => this.searchKeys.includes(k))
          .map(k => String(d[k]))
          .join('|')
          .toLowerCase()
          .indexOf(filter) !== -1 || !filter;
      });
  }

  sort(data) {
    data.sort((a: any, b: any) => {
      a = typeof(a[this.sortBy]) === 'string' ? a[this.sortBy].toUpperCase() : a[this.sortBy];
      b = typeof(b[this.sortBy]) === 'string' ? b[this.sortBy].toUpperCase() : b[this.sortBy];

      if (a < b) { return this.sortDesc ? 1 : -1; }
      if (a > b) { return this.sortDesc ? -1 : 1; }
      return 0;
    });
  }

  paginate(data) {
    const perPage = parseInt(String(this.perPage), 10);
    const offset = (this.currentPage - 1) * perPage;

    return data.slice(offset, offset + perPage);
  }

  setSort(key) {
    if (this.sortBy !== key) {
      this.sortBy = key;
      this.sortDesc = false;
    } else {
      this.sortDesc = !this.sortDesc;
    }

    this.currentPage = 1;
    this.update();
  }
}

<h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
  <div>Articles</div>
  <button type="button" class="btn btn-primary btn-round d-block"><span class="ion ion-md-add"></span>&nbsp; Create article</button>
</h4>

<div class="card">

  <!-- Table controls -->
  <div class="card-body">

    <div class="row">
      <div class="col">
        Per page: &nbsp;
        <select
          [(ngModel)]="perPage"
          (change)="update()"
          class="custom-select custom-select-sm d-inline-block w-auto">
          <option *ngFor="let limit of [10, 20, 30, 40, 50]">{{limit}}</option>
        </select>
      </div>
      <div class="col">
        <input type="text"
          [(ngModel)]="filterVal"
          (input)="currentPage = 1; update()"
          class="form-control form-control-sm d-inline-block w-auto float-sm-right"
          placeholder="Search...">
      </div>
    </div>

  </div>
  <!-- / Table controls -->

  <!-- Table -->
  <hr class="border-light m-0">
  <div class="table-responsive">
    <table class="table table-striped table-bordered card-table">
      <thead>
        <tr>
          <th class="text-nowrap cursor-pointer" (click)="setSort('id')">
            ID<i class="ion text-muted ml-2" *ngIf="sortBy=='id'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('title')" style="min-width: 18rem">
            Title<i class="ion text-muted ml-2" *ngIf="sortBy=='title'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('likes')">
            Likes<i class="ion text-muted ml-2" *ngIf="sortBy=='likes'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('comments')">
            Comments<i class="ion text-muted ml-2" *ngIf="sortBy=='comments'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('createdAt')">
            Created At<i class="ion text-muted ml-2" *ngIf="sortBy=='createdAt'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th class="text-nowrap cursor-pointer" (click)="setSort('status')">
            Status<i class="ion text-muted ml-2" *ngIf="sortBy=='status'" [ngClass]="'ion-md-arrow-' + (sortDesc ? 'down' : 'up')"></i>
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let article of articlesData">
          <td class="align-middle">{{article.id}}</td>
          <td class="align-middle"><a href="javascript:void(0)">{{article.title}}</a></td>
          <td class="align-middle">{{article.likes}}</td>
          <td class="align-middle">{{article.comments}}</td>
          <td class="align-middle">{{article.createdAt}}</td>
          <td class="align-middle">
            <span class="badge badge-outline-success" *ngIf="article.status === 1">Published</span>
            <span class="badge badge-outline-info" *ngIf="article.status === 2">Draft</span>
            <span class="badge badge-outline-default" *ngIf="article.status === 3">Deleted</span>
          </td>
          <td class="text-center text-nowrap align-middle">
            <a href="javascript:void(0)" class="btn btn-default btn-xs icon-btn md-btn-flat" ngbTooltip="Edit"><i class="ion ion-md-create"></i></a>
            <a href="javascript:void(0)" class="btn btn-default btn-xs icon-btn md-btn-flat" ngbTooltip="Remove"><i class="ion ion-md-close"></i></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- / Table -->

  <!-- Pagination -->
  <div class="card-body py-0">

    <div class="row">
      <div class="col-sm text-sm-left text-center pt-3">
        <span class="text-muted" *ngIf="totalItems">Page {{ currentPage }} of {{ totalPages }}</span>
      </div>
      <div class="col-sm pt-3">
        <ngb-pagination
          [collectionSize]="totalItems"
          [pageSize]="perPage"
          [(page)]="currentPage"
          (pageChange)="update()"
          size="sm"
          class="d-flex justify-content-center justify-content-sm-end m-0"></ngb-pagination>
      </div>
    </div>

  </div>
  <!-- / Pagination -->
</div>
