// angular-demo/src/app/+forms/file-upload/file-upload.component.ts
/* tslint:disable:member-ordering */
import { Component, ViewChild, AfterViewInit } from '@angular/core';
import { AppService } from '../../app.service';
import { DropzoneDirective } from 'ngx-dropzone-wrapper';
import { FileUploader } from 'ng2-file-upload';

@Component({
  selector: 'forms-file-upload', // tslint:disable-line
  templateUrl: './file-upload.component.html',
  styleUrls: [
    '../../../vendor/libs/ngx-dropzone-wrapper/ngx-dropzone-wrapper.scss',
    './file-upload.scss'
  ]
})
export class FileUploadComponent implements AfterViewInit {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'File upload - Forms';
  }

  //
  // ngx-dropzone-wrapper
  //

  dropzoneConfig = {
    url: '/upload',
    parallelUploads: 2,
    maxFilesize:     50000,
    filesizeBase:    1000,
    addRemoveLinks:  true,
    previewTemplate: `
<div class="dz-preview dz-file-preview">
  <div class="dz-details">
    <div class="dz-thumbnail">
      <img data-dz-thumbnail>
      <span class="dz-nopreview">No preview</span>
      <div class="dz-success-mark"></div>
      <div class="dz-error-mark"></div>
      <div class="dz-error-message"><span data-dz-errormessage></span></div>
      <div class="progress">
        <div class="progress-bar progress-bar-primary"
          role="progressbar"
          aria-valuemin="0"
          aria-valuemax="100"
          data-dz-uploadprogress></div>
      </div>
    </div>
    <div class="dz-filename" data-dz-name></div>
    <div class="dz-size" data-dz-size></div>
  </div>
</div>`
  };

  // ***************************************************************************
  // Mock the file upload progress (only for the demo)
  //

  @ViewChild(DropzoneDirective) dropzoneInstance: DropzoneDirective;

  ngAfterViewInit() {
    const component = this;

    this.dropzoneInstance.dropzone().uploadFiles = function(files) {
      const minSteps         = 6;
      const maxSteps         = 60;
      const timeBetweenSteps = 100;
      const bytesPerStep     = 100000;
      const isUploadSuccess  = Math.round(Math.random());

      const self = this;

      for (let i = 0; i < files.length; i++) {

        const file = files[i];
        const totalSteps = Math.round(Math.min(maxSteps, Math.max(minSteps, file.size / bytesPerStep)));

        for (let step = 0; step < totalSteps; step++) {
          const duration = timeBetweenSteps * (step + 1);

          setTimeout(function(_file, _totalSteps, _step) {
            return function() {
              _file.upload = {
                progress: 100 * (_step + 1) / _totalSteps,
                total: _file.size,
                bytesSent: (_step + 1) * _file.size / _totalSteps
              };

              self.emit('uploadprogress', _file, _file.upload.progress, _file.upload.bytesSent);
              if (_file.upload.progress === 100) {

                if (isUploadSuccess) {
                  _file.status = component.dropzoneInstance.DZ_SUCCESS;
                  self.emit('success', _file, 'success', null);
                } else {
                  _file.status = component.dropzoneInstance.DZ_ERROR;
                  self.emit('error', _file, 'Some upload error', null);
                }

                self.emit('complete', _file);
                self.processQueue();
              }
            };
          }(file, totalSteps, step), duration);
        }
      }
    };
  }

  //
  // ng2-file-upload
  //

  uploader = new FileUploader({ url: 'https://evening-anchorage-3159.herokuapp.com/api/' });
  hasBaseDropZoneOver = false;

  fileOver(e: any) {
    this.hasBaseDropZoneOver = e;
  }

}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Forms /</span> File upload
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    ngx-dropzone-wrapper
  </h6>
  <div class="card-body">
    <div class="dropzone" [dropzone]="dropzoneConfig">
      <div class="dz-message needsclick">
        Drop files here or click to upload
        <span class="note needsclick">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span>
      </div>
      <div class="fallback">
        <input name="file" type="file" multiple>
      </div>
    </div>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    ng2-file-upload
  </h6>
  <div class="card-body">
    <div class="ng2-file-upload-drop-zone text-center py-5 px-3"
      ng2FileDrop
      [ngClass]="{'ng2-file-upload-file-over': hasBaseDropZoneOver}"
      (fileOver)="fileOver($event)"
      [uploader]="uploader">

      <h4>Drop files here to upload or</h4>
      <label class="btn btn-secondary">
        Select file
        <input type="file" class="sr-only" ng2FileSelect [uploader]="uploader">
      </label>
      <label class="btn btn-secondary">
        Select multiple files
        <input type="file" class="sr-only" ng2FileSelect [uploader]="uploader" multiple>
      </label>
    </div>

    <div class="media mt-4" [class.d-none]="!uploader?.queue?.length">
      <div class="mr-3">
        <button type="button" class="progress-resume-link btn icon-btn btn-primary" (click)="uploader.uploadAll()" [disabled]="!uploader.getNotUploadedItems().length" ngbTooltip="Upload all"><i class="ion ion-md-play"></i></button>
        <button type="button" class="progress-pause-link btn icon-btn btn-warning" (click)="uploader.cancelAll()" [disabled]="!uploader.isUploading" ngbTooltip="Cancel all"><i class="ion ion-md-close"></i></button>
        <button type="button" class="progress-cancel-link btn icon-btn btn-danger" (click)="uploader.clearQueue()" [disabled]="!uploader.queue.length" ngbTooltip="Remove all"><i class="ion ion-md-trash"></i></button>
      </div>
      <div class="media-body align-self-center">
        <div class="progress-container progress"><div class="progress-bar" [ngStyle]="{ 'width': uploader.progress + '%' }"></div></div>
      </div>
    </div>

    <ul class="list-group mt-4" [class.d-none]="!uploader?.queue?.length">

      <!-- Files -->
      <li class="list-group-item" *ngFor="let item of uploader.queue">
        <div class="media">
          <div class="media-body">
            <div>
              <span *ngIf="item.isSuccess"><i class="ion ion-md-checkmark text-success text-big mr-2"></i></span>
              <span *ngIf="item.isCancel"><i class="ion ion-md-close text-warning text-big mr-2"></i></span>
              <span *ngIf="item.isError"><i class="ion ion-md-alert text-danger text-big mr-2"></i></span>
              <strong>{{ item?.file?.name }}</strong>
              <span>
                - <em class="text-muted">{{ item.progress + '%' }}</em>
              </span>
            </div>
            <div>
              <small class="text-muted" nowrap>
                {{ item?.file?.size/1024/1024 | number:'.2' }} MB
              </small>
            </div>
          </div>
          <div class="align-self-center ml-3">
            <button type="button" class="btn btn-sm icon-btn btn-outline-success" (click)="item.upload()" [disabled]="item.isReady || item.isUploading || item.isSuccess"><i class="ion ion-md-play"></i></button>
            <button type="button" class="btn btn-sm icon-btn btn-outline-warning" (click)="item.cancel()" [disabled]="!item.isUploading"><i class="ion ion-md-close"></i></button>
            <button type="button" class="btn btn-sm icon-btn btn-outline-danger" (click)="item.remove()"><i class="ion ion-md-trash"></i></button>
          </div>
        </div>
      </li>

    </ul>
  </div>
</div>

// vue-demo-cli2-deprecated/src/components/forms/FileUpload.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Forms /</span> File upload
    </h4>

    <b-card header="Vue Dropzone" header-tag="h6" class="mb-4">
      <vue-dropzone id="my-dropzone" :options="dropzoneOptions" ref="dropzoneInstance" />
    </b-card>

    <b-card header="Vue Upload Component" header-tag="h6" class="mb-4">
      <file-upload class="sr-only"
        :name="name"
        :post-action="postAction"
        :extensions="extensions"
        :accept="accept"
        :multiple="multiple"
        :directory="directory"
        :size="size || 0"
        :thread="thread < 1 ? 1 : (thread > 5 ? 5 : thread)"
        :drop="drop"
        :drop-directory="dropDirectory"
        :add-index="addIndex"
        v-model="files"
        @input-filter="inputFilter"
        @input-file="inputFile"
        ref="upload" />

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Thumb</th>
              <th>Name</th>
              <th>Size</th>
              <th>Speed</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="!files.length">
              <td colspan="7">
                <div class="text-center p-5">
                  <h4>Drop files anywhere to upload <div class="text-muted small my-3">or</div></h4>
                  <label :for="name" class="btn btn-primary btn-lg">Select Files</label>
                </div>
              </td>
            </tr>
            <tr v-for="(file, index) in files" :key="file.id">
              <td>{{index}}</td>
              <td>
                <img v-if="file.thumb" :src="file.thumb" width="40" height="auto" />
                <span v-else>No Image</span>
              </td>
              <td>
                <div class="filename">
                  {{file.name}}
                </div>
                <b-progress :value="Number(file.progress)" :variant="file.error ? 'danger' : ''" :animated="file.active" v-if="file.active || file.progress !== '0.00'" height="6px" style="margin: 4px 0 0 0" />
              </td>
              <td>{{ file.size/1024/1024 | fileSize }} MB</td>
              <td>{{file.speed}}</td>

              <td v-if="file.error">{{file.error}}</td>
              <td v-else-if="file.success">success</td>
              <td v-else-if="file.active">active</td>
              <td v-else></td>
              <td>
                <b-dd text="Action" size="sm" :right="!isRTL">
                  <b-dd-item :disabled="!file.active" @click="file.active ? $refs.upload.update(file, {error: 'cancel'}) : false">Cancel</b-dd-item>

                  <b-dd-item v-if="file.active" @click="$refs.upload.update(file, {active: false})">Abort</b-dd-item>
                  <b-dd-item v-else-if="file.error && $refs.upload.features.html5" @click="$refs.upload.update(file, {active: true, error: '', progress: '0.00'})">Retry upload</b-dd-item>
                  <b-dd-item v-else :disabled="file.success" @click="file.success ? false : $refs.upload.update(file, {active: true})">Upload</b-dd-item>

                  <b-dd-divider />

                  <b-dd-item @click="$refs.upload.remove(file)">Remove</b-dd-item>
                </b-dd>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <b-dd split :right="isRTL" @click="$refs.upload.$el.querySelector('input').click()">
        <template slot="button-content">
          <i class="ion ion-md-add"></i> Add files
        </template>
        <b-dd-item @click="onAddFolder">Add folder</b-dd-item>
      </b-dd>
      <b-btn v-if="!$refs.upload || !$refs.upload.active" @click="$refs.upload.active = true" variant="success">
        <i class="ion ion-md-arrow-up" aria-hidden="true"></i> Start Upload
      </b-btn>
      <b-btn v-else @click="$refs.upload.active = false" variant="danger">
        <i class="ion ion-md-close" aria-hidden="true"></i> Stop Upload
      </b-btn>
    </b-card>

  </div>
</template>

<style src="@/vendor/libs/vue-dropzone/vue-dropzone.scss" lang="scss"></style>

<script>
import vue2Dropzone from 'vue2-dropzone'
import Vue from 'vue'
import VueUploadComponent from 'vue-upload-component'

Vue.filter('fileSize', function (value) {
  if (!value) return ''
  const parts = String(value).split('.')
  return `${parts[0]}.${parts[1].slice(0, 2)}`
})

export default {
  name: 'forms-file-upload',
  metaInfo: {
    title: 'File upload - Forms'
  },
  components: {
    vueDropzone: vue2Dropzone,
    FileUpload: VueUploadComponent
  },
  data: () => ({
    //
    // Dropzone
    //

    dropzoneOptions: {
      url: '/upload',
      parallelUploads: 2,
      maxFilesize: 50000,
      filesizeBase: 1000,
      addRemoveLinks: true,
      dictDefaultMessage: `
Drop files here or click to upload<br>
<span class="text-light small">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span>
      `,
      previewTemplate: `
<div class="dz-preview dz-file-preview">
  <div class="dz-details">
    <div class="dz-thumbnail">
      <img data-dz-thumbnail>
      <span class="dz-nopreview">No preview</span>
      <div class="dz-success-mark"></div>
      <div class="dz-error-mark"></div>
      <div class="dz-error-message"><span data-dz-errormessage></span></div>
      <div class="progress"><div class="progress-bar progress-bar-primary" role="progressbar" aria-valuemin="0" aria-valuemax="100" data-dz-uploadprogress></div></div>
    </div>
    <div class="dz-filename" data-dz-name></div>
    <div class="dz-size" data-dz-size></div>
  </div>
</div>`
    },

    //
    // Vue Upload Component
    //

    files: [],
    name: 'file',
    accept: 'image/png,image/gif,image/jpeg,image/webp',
    extensions: 'gif,jpg,jpeg,png,webp',
    // extensions: ['gif', 'jpg', 'jpeg','png', 'webp'],
    // extensions: /\.(gif|jpe?g|png|webp)$/i,
    minSize: 1024,
    size: 1024 * 1024 * 10,
    multiple: true,
    directory: false,
    drop: true,
    dropDirectory: true,
    addIndex: false,
    thread: 3,
    postAction: 'https://evening-anchorage-3159.herokuapp.com/api/'
  }),

  // ***************************************************************************
  // Dropzone:: Mock the file upload progress (only for the demo)
  //

  mounted () {
    if (typeof document.documentMode === 'number' && document.documentMode < 11) return

    const dropzoneInstance = this.$refs.dropzoneInstance.dropzone

    dropzoneInstance.uploadFiles = function (files) {
      const minSteps = 6
      const maxSteps = 60
      const timeBetweenSteps = 100
      const bytesPerStep = 100000
      const isUploadSuccess = Math.round(Math.random())

      for (let i = 0; i < files.length; i++) {
        const file = files[i]
        const totalSteps = Math.round(Math.min(maxSteps, Math.max(minSteps, file.size / bytesPerStep)))

        for (let step = 0; step < totalSteps; step++) {
          const duration = timeBetweenSteps * (step + 1)

          setTimeout(((file, totalSteps, step) => {
            return () => {
              file.upload = {
                progress: 100 * (step + 1) / totalSteps,
                total: file.size,
                bytesSent: (step + 1) * file.size / totalSteps
              }

              this.emit('uploadprogress', file, file.upload.progress, file.upload.bytesSent)

              if (file.upload.progress === 100) {
                if (isUploadSuccess) {
                  file.status = dropzoneInstance.DZ_SUCCESS
                  this.emit('success', file, 'success', null)
                } else {
                  file.status = dropzoneInstance.DZ_ERROR
                  this.emit('error', file, 'Some upload error', null)
                }

                this.emit('complete', file)
                this.processQueue()
              }
            }
          })(file, totalSteps, step), duration)
        }
      }
    }
  },
  methods: {
    //
    // Vue Upload Component
    //

    inputFilter (newFile, oldFile, prevent) {
      if (newFile && !oldFile) {
        // Before adding a file
        // Filter system files or hide files
        if (/(\/|^)(Thumbs\.db|desktop\.ini|\..+)$/.test(newFile.name)) {
          return prevent()
        }
        // Filter php html js file
        if (/\.(php5?|html?|jsx?)$/i.test(newFile.name)) {
          return prevent()
        }
      }
      if (newFile && (!oldFile || newFile.file !== oldFile.file)) {
        // Create a blob field
        newFile.blob = ''
        let URL = window.URL || window.webkitURL
        if (URL && URL.createObjectURL) {
          newFile.blob = URL.createObjectURL(newFile.file)
        }
        // Thumbnails
        newFile.thumb = ''
        if (newFile.blob && newFile.type.substr(0, 6) === 'image/') {
          newFile.thumb = newFile.blob
        }
      }
    },
    // add, update, remove File Event
    inputFile (newFile, oldFile) {
      if (newFile && oldFile) {
        // update
        if (newFile.active && !oldFile.active) {
          // beforeSend
          // min size
          if (newFile.size >= 0 && this.minSize > 0 && newFile.size < this.minSize) {
            this.$refs.upload.update(newFile, { error: 'size' })
          }
        }
      }
    },
    // add folader
    onAddFolder () {
      if (!this.$refs.upload.features.directory) {
        alert('Your browser does not support')
        return
      }
      let input = this.$refs.upload.$el.querySelector('input')
      input.directory = true
      input.webkitdirectory = true
      this.directory = true
      input.onclick = null
      input.click()
      input.onclick = (e) => {
        this.directory = false
        input.directory = false
        input.webkitdirectory = false
      }
    }
  }
}
</script>
