// vue-demo/src/components/pages/AuthenticationLoginAndRegister.vue
<template>
  <div class="authentication-wrapper authentication-4 px-4">
    <div class="authentication-inner py-5">

      <!-- Logo -->
      <div class="d-flex justify-content-center align-items-center mb-5">
        <div class="ui-w-60">
          <div class="w-100 position-relative" style="padding-bottom: 54%">
            <svg class="w-100 h-100 position-absolute" viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path class="fill-primary" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
          </div>
        </div>
      </div>
      <!-- / Logo -->

      <b-card no-body>
        <div class="row no-gutters row-bordered">

          <!-- Login -->
          <div class="col-md-6">
            <h5 class="text-center text-muted font-weight-normal py-4 px-4 px-sm-5 m-0">Login to Your Account</h5>
            <hr class="border-light m-0">

            <div class="px-4 px-sm-5 pt-4 pb-5 pb-sm-5">

              <!-- Login form -->
              <form>
                <b-form-group label="Email">
                  <b-input v-model="loginCredentials.email" />
                </b-form-group>
                <b-form-group>
                  <div slot="label" class="d-flex justify-content-between align-items-end">
                    <div>Password</div>
                    <a href="javascript:void(0)" class="d-block small">Forgot password?</a>
                  </div>
                  <b-input type="password" v-model="loginCredentials.password" />
                </b-form-group>

                <div class="d-flex justify-content-between align-items-center m-0">
                  <b-check v-model="loginCredentials.rememberMe" class="m-0">Remember me</b-check>
                  <b-btn variant="primary">Sign In</b-btn>
                </div>
              </form>
              <!-- / Login form -->

            </div>
          </div>
          <!-- / Login -->

          <!-- Register -->
          <div class="col-md-6">
            <h5 class="text-center text-muted font-weight-normal py-4 px-4 px-sm-5 m-0">Create an Account</h5>
            <hr class="border-light m-0">

            <div class="px-4 px-sm-5 pt-4 pb-5 pb-sm-5">

              <!-- Register form -->
              <form>
                <b-form-group label="Your name">
                  <b-input v-model="registerCredentials.name" />
                </b-form-group>
                <b-form-group label="Your email">
                  <b-input v-model="registerCredentials.email" />
                </b-form-group>
                <b-form-group label="Password">
                  <b-input type="password" v-model="registerCredentials.password" />
                </b-form-group>
                <b-btn variant="primary" :block="true" class="mt-4">Sign Up</b-btn>
                <div class="text-light small mt-4">
                  By clicking "Sign Up", you agree to our
                  <a href="javascript:void(0)">terms of service and privacy policy</a>.
                  We’ll occasionally send you account related emails.
                </div>
              </form>
              <!-- / Register form -->

            </div>
          </div>
          <!-- / Register -->

        </div>
      </b-card>

    </div>
  </div>
</template>

<!-- Page -->
<style src="@/vendor/styles/pages/authentication.scss" lang="scss"></style>

<script>
export default {
  name: 'pages-authentication-login-and-register',
  metaInfo: {
    title: 'Login + register - Pages'
  },
  data: () => ({
    loginCredentials: {
      email: '',
      password: '',
      rememberMe: false
    },
    registerCredentials: {
      name: '',
      email: '',
      password: ''
    }
  })
}
</script>

// angular-demo/src/app/+pages/authentication-login-and-register/authentication-login-and-register.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-authentication-login-and-register',
  templateUrl: './authentication-login-and-register.component.html',
  styleUrls: [
    '../../../vendor/styles/pages/authentication.scss'
  ]
})
export class AuthenticationLoginAndRegisterComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Login + Register - Pages';
  }

  loginCredentials = {
    email: '',
    password: '',
    rememberMe: false
  };

  registerCredentials = {
    name: '',
    email: '',
    password: ''
  };

}

<div class="authentication-wrapper authentication-4 px-4">
  <div class="authentication-inner py-5">

    <!-- Logo -->
    <div class="d-flex justify-content-center align-items-center mb-5">
      <div class="ui-w-60">
        <div class="w-100 position-relative" style="padding-bottom: 54%">
          <svg class="w-100 h-100 position-absolute" viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path class="fill-primary" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
        </div>
      </div>
    </div>
    <!-- / Logo -->

    <div class="card">
      <div class="row no-gutters row-bordered">

        <!-- Login -->
        <div class="col-md-6">
          <h5 class="text-center text-muted font-weight-normal py-4 px-4 px-sm-5 m-0">Login to Your Account</h5>
          <hr class="border-light m-0">

          <div class="px-4 px-sm-5 pt-4 pb-5 pb-sm-5">

            <!-- Login form -->
            <form>
              <div class="form-group">
                <label class="form-label">Email</label>
                <input [(ngModel)]="loginCredentials.email" name="loginEmail" type="text" class="form-control">
              </div>
              <div class="form-group">
                <label class="form-label d-flex justify-content-between align-items-end">
                  <div>Password</div>
                  <a href="javascript:void(0)" class="d-block small">Forgot password?</a>
                </label>
                <input [(ngModel)]="loginCredentials.password" name="loginPassword" type="password" class="form-control">
              </div>
              <div class="d-flex justify-content-between align-items-center m-0">
                <label class="custom-control custom-checkbox m-0">
                  <input type="checkbox" class="custom-control-input" name="loginRememberMe" [(ngModel)]="loginCredentials.rememberMe">
                  <span class="custom-control-label">Remember me</span>
                </label>
                <button type="button" class="btn btn-primary">Sign In</button>
              </div>
            </form>
            <!-- / Login form -->

          </div>
        </div>
        <!-- / Login -->

        <!-- Register -->
        <div class="col-md-6">
          <h5 class="text-center text-muted font-weight-normal py-4 px-4 px-sm-5 m-0">Create an Account</h5>
          <hr class="border-light m-0">

          <div class="px-4 px-sm-5 pt-4 pb-5 pb-sm-5">

            <!-- Register form -->
            <form>
              <div class="form-group">
                <label class="form-label">Your name</label>
                <input [(ngModel)]="registerCredentials.name" name="registerName" type="text" class="form-control">
              </div>
              <div class="form-group">
                <label class="form-label">Your email</label>
                <input [(ngModel)]="registerCredentials.email" name="registerEmail" type="text" class="form-control">
              </div>
              <div class="form-group">
                <label class="form-label">Password</label>
                <input [(ngModel)]="registerCredentials.password" name="registerPassword" type="password" class="form-control">
              </div>
              <button type="button" class="btn btn-primary btn-block mt-4">Sign Up</button>
              <div class="text-light small mt-4">
                By clicking "Sign Up", you agree to our
                <a href="javascript:void(0)">terms of service and privacy policy</a>. We’ll occasionally send you account related emails.
              </div>
            </form>
            <!-- / Register form -->

          </div>
        </div>
        <!-- / Register -->

      </div>
    </div>

  </div>
</div>
