// vue-demo/src/components/pages/ProjectsList.vue
<template>
  <div>

    <h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
      <div>Projects</div>
      <b-btn variant="primary btn-round" class="d-block"><span class="ion ion-md-add"></span>&nbsp; Create project</b-btn>
    </h4>

    <div class="row">
      <div v-for="project in projectsData" :key="project.title" class="col-sm-6 col-xl-4">
        <b-card no-body class="mb-4">

          <b-card-body class="d-flex justify-content-between align-items-start pb-3">
            <div>
              <a href="javascript:void(0)" class="text-dark text-big font-weight-semibold">{{project.title}}</a>
              <b-badge class="align-text-bottom ml-1" :variant="statuses[project.status].color">{{statuses[project.status].title}}</b-badge>
              <div class="text-muted small mt-1">{{project.tasks - project.completedTasks}} opened tasks, {{project.completedTasks}} tasks completed</div>
            </div>
            <b-dropdown variant="default icon-btn borderless btn-round md-btn-flat hide-arrow" size="sm" :right="!isRTL">
              <template slot="button-content"><i class="ion ion-ios-more"></i></template>
              <b-dropdown-item href="javascript:void(0)">View</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)">Edit</b-dropdown-item>
              <b-dropdown-item href="javascript:void(0)">Remove</b-dropdown-item>
            </b-dropdown>
          </b-card-body>

          <b-progress :value="completedPercent(project.tasks, project.completedTasks)" height="3px" class="rounded-0" />
          <div class="card-body small pt-2 pb-0">
            <strong>{{completedPercent(project.tasks, project.completedTasks)}}%</strong> completed
          </div>

          <b-card-body class="pb-3">
            {{project.shortDescription}}
          </b-card-body>

          <b-card-body class="pt-0">
            <div class="row">
              <div class="col">
                <div class="text-muted small">Created</div>
                <div class="font-weight-bold">{{project.created}}</div>
              </div>
              <div class="col">
                <div class="text-muted small">Deadline</div>
                <div class="font-weight-bold">{{project.deadline}}</div>
              </div>
            </div>
          </b-card-body>
          <hr class="m-0">

          <b-card-body class="py-3">
            <div class="text-muted small mb-2">Team</div>
            <div class="d-flex flex-wrap">
              <a v-for="member in project.team" :key="member.avatar" href="javascript:void(0)" class="d-block mr-1 mb-1"><img :src="`${baseUrl}img/avatars/${member.avatar}`" alt="" class="ui-w-30 rounded-circle"></a>
            </div>
          </b-card-body>

        </b-card>
      </div>
    </div>

  </div>
</template>

<script>
export default {
  name: 'pages-projects-list',
  metaInfo: {
    title: 'Project list - Pages'
  },
  data: () => ({
    statuses: {
      1: { title: 'Active', color: 'success' },
      2: { title: 'Pending', color: 'warning' }
    },

    projectsData: [{
      status: 1,
      title: 'Frontend Development',
      tasks: 15,
      completedTasks: 5,
      shortDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac malesuada nisl. Maecenas quis ultrices tellus.',
      created: '02/01/2018',
      deadline: '03/12/2018',
      team: [
        { avatar: '2-small.png' },
        { avatar: '3-small.png' },
        { avatar: '4-small.png' },
        { avatar: '5-small.png' },
        { avatar: '6-small.png' }
      ]
    }, {
      status: 1,
      title: 'Website',
      tasks: 44,
      completedTasks: 29,
      shortDescription: 'Aliquam sem elit, semper sed ante ut, aliquam molestie risus.',
      created: '02/01/2018',
      deadline: '03/12/2018',
      team: [
        { avatar: '7-small.png' },
        { avatar: '8-small.png' },
        { avatar: '9-small.png' }
      ]
    }, {
      status: 1,
      title: 'UI update',
      tasks: 54,
      completedTasks: 48,
      shortDescription: 'Etiam venenatis varius lectus sed fermentum. Nullam hendrerit, massa sed tincidunt sagittis, leo nibh semper sapien, vitae interdum nisl erat ut sapien.',
      created: '02/01/2018',
      deadline: '03/12/2018',
      team: [
        { avatar: '10-small.png' },
        { avatar: '11-small.png' },
        { avatar: '12-small.png' }
      ]
    }, {
      status: 2,
      title: 'SEO',
      tasks: 70,
      completedTasks: 45,
      shortDescription: 'Suspendisse scelerisque nisi ac semper ornare.',
      created: '02/01/2018',
      deadline: '03/12/2018',
      team: [
        { avatar: '2-small.png' },
        { avatar: '3-small.png' },
        { avatar: '4-small.png' }
      ]
    }, {
      status: 1,
      title: 'example.com design',
      tasks: 84,
      completedTasks: 28,
      shortDescription: 'Pellentesque imperdiet nunc quis fringilla euismod. Nunc iaculis eu augue sit amet faucibus.',
      created: '02/01/2018',
      deadline: '03/12/2018',
      team: [
        { avatar: '5-small.png' },
        { avatar: '6-small.png' },
        { avatar: '7-small.png' },
        { avatar: '8-small.png' }
      ]
    }]
  }),
  methods: {
    completedPercent (tasks, completed) {
      return Math.round((completed / tasks) * 100)
    }
  }
}
</script>

// angular-demo/src/app/+pages/projects-list/projects-list.component.ts
/* tslint:disable:max-line-length */
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-projects-list',
  templateUrl: './projects-list.component.html',
  styles: [`
    :host /deep/ .progress { border-radius: 0 !important; }
  `]
})
export class ProjectsListComponent {
  isRTL: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Project list - Pages';
    this.isRTL = appService.isRTL;
  }

  statuses = {
    1: { title: 'Active', color: 'success' },
    2: { title: 'Pending', color: 'warning' }
  };

  projectsData = [{
    status: 1,
    title: 'Frontend Development',
    tasks: 15,
    completedTasks: 5,
    shortDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac malesuada nisl. Maecenas quis ultrices tellus.',
    created: '02/01/2018',
    deadline: '03/12/2018',
    team: [
      { avatar: '2-small.png' },
      { avatar: '3-small.png' },
      { avatar: '4-small.png' },
      { avatar: '5-small.png' },
      { avatar: '6-small.png' }
    ]
  }, {
    status: 1,
    title: 'Website',
    tasks: 44,
    completedTasks: 29,
    shortDescription: 'Aliquam sem elit, semper sed ante ut, aliquam molestie risus.',
    created: '02/01/2018',
    deadline: '03/12/2018',
    team: [
      { avatar: '7-small.png' },
      { avatar: '8-small.png' },
      { avatar: '9-small.png' }
    ]
  }, {
    status: 1,
    title: 'UI update',
    tasks: 54,
    completedTasks: 48,
    shortDescription: 'Etiam venenatis varius lectus sed fermentum. Nullam hendrerit, massa sed tincidunt sagittis, leo nibh semper sapien, vitae interdum nisl erat ut sapien.',
    created: '02/01/2018',
    deadline: '03/12/2018',
    team: [
      { avatar: '10-small.png' },
      { avatar: '11-small.png' },
      { avatar: '12-small.png' }
    ]
  }, {
    status: 2,
    title: 'SEO',
    tasks: 70,
    completedTasks: 45,
    shortDescription: 'Suspendisse scelerisque nisi ac semper ornare.',
    created: '02/01/2018',
    deadline: '03/12/2018',
    team: [
      { avatar: '2-small.png' },
      { avatar: '3-small.png' },
      { avatar: '4-small.png' }
    ]
  }, {
    status: 1,
    title: 'example.com design',
    tasks: 84,
    completedTasks: 28,
    shortDescription: 'Pellentesque imperdiet nunc quis fringilla euismod. Nunc iaculis eu augue sit amet faucibus.',
    created: '02/01/2018',
    deadline: '03/12/2018',
    team: [
      { avatar: '5-small.png' },
      { avatar: '6-small.png' },
      { avatar: '7-small.png' },
      { avatar: '8-small.png' }
    ]
  }];

  completedPercent(tasks, completed) {
    return Math.round((completed / tasks) * 100);
  }
}

<h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
  <div>Projects</div>
  <button type="button" class="btn btn-primary btn-round d-block"><span class="ion ion-md-add"></span>&nbsp; Create project</button>
</h4>

<div class="row">
  <div *ngFor="let project of projectsData" class="col-sm-6 col-xl-4">
    <div class="card mb-4">

      <div class="card-body d-flex justify-content-between align-items-start pb-3">
        <div>
          <a href="javascript:void(0)" class="text-dark text-big font-weight-semibold">{{project.title}}</a>
          <span class="badge align-text-bottom ml-1" [ngClass]="'badge-' + statuses[project.status].color">{{statuses[project.status].title}}</span>
          <div class="text-muted small mt-1">{{project.tasks - project.completedTasks}} opened tasks, {{project.completedTasks}} tasks completed</div>
        </div>

        <div class="btn-group" ngbDropdown [placement]="!isRTL ? 'bottom-right' : 'bottom-left'">
          <button type="button" class="btn btn-default btn-sm icon-btn borderless btn-round md-btn-flat hide-arrow" ngbDropdownToggle><i class="ion ion-ios-more"></i></button>
          <div ngbDropdownMenu [class.dropdown-menu-right]="!isRTL">
            <a class="dropdown-item" href="javascript:void(0)">View</a>
            <a class="dropdown-item" href="javascript:void(0)">Edit</a>
            <a class="dropdown-item" href="javascript:void(0)">Remove</a>
          </div>
        </div>
      </div>

      <ngb-progressbar [value]="completedPercent(project.tasks, project.completedTasks)" height="3px"></ngb-progressbar>
      <div class="card-body small pt-2 pb-0">
        <strong>{{completedPercent(project.tasks, project.completedTasks)}}%</strong> completed
      </div>

      <div class="card-body pb-3">
        {{project.shortDescription}}
      </div>

      <div class="card-body pt-0">
        <div class="row">
          <div class="col">
            <div class="text-muted small">Created</div>
            <div class="font-weight-bold">{{project.created}}</div>
          </div>
          <div class="col">
            <div class="text-muted small">Deadline</div>
            <div class="font-weight-bold">{{project.deadline}}</div>
          </div>
        </div>
      </div>
      <hr class="m-0">
      <div class="card-body py-3">
        <div class="text-muted small mb-2">Team</div>
        <div class="d-flex flex-wrap">
          <a *ngFor="let member of project.team" href="javascript:void(0)" class="d-block mr-1 mb-1"><img [src]="'assets/img/avatars/' + member.avatar" alt="" class="ui-w-30 rounded-circle"></a>
        </div>
      </div>

    </div>
  </div>
</div>
