// vue-starter/src/components/Page2.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">Page 2</h4>
    <p>This page is an example of basic layout. For more options use <strong>Vue starter template generator</strong> in the docs.</p>
    <p><button class="btn btn-primary btn-lg">Button</button></p>
  </div>
</template>

<script>
export default {
  name: 'page-2',
  metaInfo: {
    title: 'Page 2'
  }
}
</script>

// angular-starter/src/app/page-2/page-2.component.ts
import { Component } from '@angular/core';
import { AppService } from '../app.service';

@Component({
  selector: 'app-page-2',
  templateUrl: './page-2.component.html'
})
export class Page2Component {

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Page 2';
  }

}

<h4 class="font-weight-bold py-3 mb-4">Page 2</h4>
<p>This page is an example of basic layout. For more options use <strong>Angular starter template generator</strong> in the docs.</p>
<p><button class="btn btn-primary btn-lg">Button</button></p>
