// angular-demo/src/app/+ui/button-groups/button-groups.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-button-groups', // tslint:disable-line
  templateUrl: './button-groups.component.html'
})
export class ButtonGroupsComponent {
  isRTL: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Button groups - UI elements';
    this.isRTL = appService.isRTL;
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Button groups
</h4>

<div class="row">
  <div class="col-12">

    <div class="card mb-4">
      <h6 class="card-header">
        Sizes
      </h6>
      <div class="card-body demo-vertical-spacing">
        <!-- Extra-large -->
        <div class="btn-group btn-group-xl">
          <button type="button" class="btn btn-secondary">Left</button>
          <button type="button" class="btn btn-secondary">Middle</button>
          <button type="button" class="btn btn-secondary">Right</button>
        </div>

        <br>

        <!-- Large -->
        <div class="btn-group btn-group-lg">
          <button type="button" class="btn btn-secondary">Left</button>
          <button type="button" class="btn btn-secondary">Middle</button>
          <button type="button" class="btn btn-secondary">Right</button>
        </div>

        <br>

        <!-- Default -->
        <div class="btn-group">
          <button type="button" class="btn btn-secondary">Left</button>
          <button type="button" class="btn btn-secondary">Middle</button>
          <button type="button" class="btn btn-secondary">Right</button>
        </div>

        <br>

        <!-- Small -->
        <div class="btn-group btn-group-sm">
          <button type="button" class="btn btn-secondary">Left</button>
          <button type="button" class="btn btn-secondary">Middle</button>
          <button type="button" class="btn btn-secondary">Right</button>
        </div>

        <br>

        <!-- Extra-small -->
        <div class="btn-group btn-group-xs">
          <button type="button" class="btn btn-secondary">Left</button>
          <button type="button" class="btn btn-secondary">Middle</button>
          <button type="button" class="btn btn-secondary">Right</button>
        </div>
      </div>
    </div>

  </div>
  <div class="col-12">

    <div class="card mb-4">
      <h6 class="card-header">
        Toolbar
      </h6>
      <div class="card-body">
        <div class="btn-toolbar">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-secondary">1</button>
            <button type="button" class="btn btn-secondary">2</button>
            <button type="button" class="btn btn-secondary">3</button>
            <button type="button" class="btn btn-secondary">4</button>
          </div>
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-secondary">5</button>
            <button type="button" class="btn btn-secondary">6</button>
            <button type="button" class="btn btn-secondary">7</button>
          </div>
          <div class="btn-group">
            <button type="button" class="btn btn-secondary">8</button>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="col-12">

    <div class="card mb-4">
      <h6 class="card-header">
        Nesting
      </h6>
      <div class="card-body">
        <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
          <button type="button" class="btn btn-secondary">1</button>
          <button type="button" class="btn btn-secondary">2</button>
          <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
          <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
            <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
            <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="col-12">

    <div class="card mb-4">
      <h6 class="card-header">
        Vertical
      </h6>
      <div class="card-body">
        <div class="btn-group-vertical">
          <button type="button" class="btn btn-secondary">Button</button>
          <button type="button" class="btn btn-secondary">Button</button>
          <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
            <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
            </div>
          </div>
          <button type="button" class="btn btn-secondary">Button</button>
          <button type="button" class="btn btn-secondary">Button</button>
          <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
            <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
            </div>
          </div>
          <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
            <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
            </div>
          </div>
          <div class="btn-group" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
            <button class="btn btn-secondary" ngbDropdownToggle>Dropdown</button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
              <a class="dropdown-item" href="javascript:void(0)">Dropdown link</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

// vue-demo/src/components/ui/ButtonGroups.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Button groups
    </h4>

    <div class="row">
      <div class="col-12">

        <b-card no-body header="Sizes" header-tag="h6" class="mb-4">
          <b-card-body class="demo-vertical-spacing">
            <!-- Extra-large -->
            <b-btn-group class="btn-group-xl">
              <b-btn>Left</b-btn>
              <b-btn>Middle</b-btn>
              <b-btn>Right</b-btn>
            </b-btn-group>

            <br>

            <!-- Large -->
            <b-btn-group size="lg">
              <b-btn>Left</b-btn>
              <b-btn>Middle</b-btn>
              <b-btn>Right</b-btn>
            </b-btn-group>

            <br>

            <!-- Default -->
            <b-btn-group>
              <b-btn>Left</b-btn>
              <b-btn>Middle</b-btn>
              <b-btn>Right</b-btn>
            </b-btn-group>

            <br>

            <!-- Small -->
            <b-btn-group class="btn-group-sm">
              <b-btn>Left</b-btn>
              <b-btn>Middle</b-btn>
              <b-btn>Right</b-btn>
            </b-btn-group>

            <br>

            <!-- Extra-small -->
            <b-btn-group class="btn-group-xs">
              <b-btn>Left</b-btn>
              <b-btn>Middle</b-btn>
              <b-btn>Right</b-btn>
            </b-btn-group>
          </b-card-body>
        </b-card>

      </div>
      <div class="col-12">

        <b-card header="Toolbar" header-tag="h6" class="mb-4">
          <b-btn-toolbar key-nav>
            <b-btn-group class="mr-2">
              <b-btn>&laquo;</b-btn>
              <b-btn>&lsaquo;</b-btn>
            </b-btn-group>
            <b-btn-group class="mr-2">
              <b-btn>Edit</b-btn>
              <b-btn>Undo</b-btn>
              <b-btn>Redo</b-btn>
            </b-btn-group>
            <b-btn-group>
              <b-btn>&rsaquo;</b-btn>
              <b-btn>&raquo;</b-btn>
            </b-btn-group>
          </b-btn-toolbar>
        </b-card>

      </div>
      <div class="col-12">

        <b-card header="Nesting" header-tag="h6" class="mb-4">
          <b-btn-group>
            <b-btn>1</b-btn>
            <b-btn>2</b-btn>
            <b-dd :right="isRTL" text="Dropdown">
              <b-dd-item>Dropdown link</b-dd-item>
              <b-dd-item>Dropdown link</b-dd-item>
            </b-dd>
          </b-btn-group>
        </b-card>

      </div>
      <div class="col-12">

        <b-card header="Vertical" header-tag="h6" class="mb-4">
          <b-btn-group vertical>
            <b-btn class="btn btn-secondary">Button</b-btn>
            <b-btn class="btn btn-secondary">Button</b-btn>
            <b-dd :right="isRTL" text="Dropdown">
              <b-dd-item>Dropdown link</b-dd-item>
              <b-dd-item>Dropdown link</b-dd-item>
            </b-dd>
            <b-btn class="btn btn-secondary">Button</b-btn>
            <b-btn class="btn btn-secondary">Button</b-btn>
            <b-dd :right="isRTL" text="Dropdown">
              <b-dd-item>Dropdown link</b-dd-item>
              <b-dd-item>Dropdown link</b-dd-item>
            </b-dd>
            <b-dd :right="isRTL" text="Dropdown">
              <b-dd-item>Dropdown link</b-dd-item>
              <b-dd-item>Dropdown link</b-dd-item>
            </b-dd>
            <b-dd :right="isRTL" text="Dropdown">
              <b-dd-item>Dropdown link</b-dd-item>
              <b-dd-item>Dropdown link</b-dd-item>
            </b-dd>
          </b-btn-group>
        </b-card>

      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ui-button-groups',
  metaInfo: {
    title: 'Button groups - UI elements'
  }
}
</script>
