// angular-demo/src/app/+ui/carousel/carousel.component.ts
 /* tslint:disable:member-ordering */
import { Component, AfterViewInit } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-carousel', // tslint:disable-line
  templateUrl: './carousel.component.html',
  styleUrls: [
    '../../../vendor/libs/ngx-swiper-wrapper/ngx-swiper-wrapper.scss',
    'carousel.scss'
  ]
})
export class CarouselComponent implements AfterViewInit {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Carousel - UI elements';
  }

  ngAfterViewInit() {
    // Trigger resize event to redraw swiper
    setTimeout(() => {
      if (document.createEvent) {
        let event;

        if (typeof document['documentMode'] === 'number' && document['documentMode'] > 10) {
          event = document.createEvent('Event');
          event.initEvent('resize', false, true);
        } else {
          event = new Event('resize');
        }

        window.dispatchEvent(event);
      } else {
        window['fireEvent']('onresize', document['createEventObject']());
      }
    }, 50);
  }

  swiperWithArrows = {
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    }
  };

  swiperWithPagination = {
    pagination: {
      el: '.swiper-pagination',
      clickable: true
    }
  };

  swiperWithFractionPagination = {
    pagination: {
      el: '.swiper-pagination',
      type: 'fraction'
    }
  };

  swiperWithProgress = {
    pagination: {
      el: '.swiper-pagination',
      type: 'progressbar'
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    }
  };

  swiperWithScrollbar = {
    scrollbar: {
      el: '.swiper-scrollbar',
      hide: true
    }
  };

  verticalSwiper = {
    direction: 'vertical',
    pagination: {
      el: '.swiper-pagination',
      clickable: true
    }
  };

  swiperMultipleSlides = {
    slidesPerView: 3,
    spaceBetween: 30,
    pagination: {
      el: '.swiper-pagination',
      clickable: true
    }
  };

  swiperFadeEffect = {
    effect: 'fade',
    pagination: {
      el: '.swiper-pagination',
      clickable: true
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    }
  };

  swiper3dCubeEffect = {
    effect: 'cube',
    grabCursor: true,
    cubeEffect: {
      shadow: true,
      slideShadows: true,
      shadowOffset: 20,
      shadowScale: 0.94
    },
    pagination: {
      el: '.swiper-pagination'
    }
  };

  swiper3dCoverflowEffect = {
    effect: 'coverflow',
    grabCursor: true,
    centeredSlides: true,
    slidesPerView: 'auto',
    coverflowEffect: {
      rotate: 50,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows : true
    },
    pagination: {
      el: '.swiper-pagination'
    }
  };

  swiper3dFlipEffect = {
    effect: 'flip',
    grabCursor: true,
    pagination: {
      el: '.swiper-pagination'
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    }
  };

}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Carousel
</h4>

<hr class="border-light container-m--x mt-0">

<h5 class="font-weight-bold pt-1 pb-1 mt-4 mb-4">Bootstrap carousel</h5>

<ngb-carousel>
  <ng-template ngbSlide>
    <img class="d-block w-100" src="assets/img/bg/1.jpg" alt="First slide">
    <div class="carousel-caption d-none d-md-block">
      <h3>First slide</h3>
      <p>Eos mutat malis maluisset et, agam ancillae quo te, in vim congue pertinacia.</p>
    </div>
  </ng-template>
  <ng-template ngbSlide>
    <img class="d-block w-100" src="assets/img/bg/2.jpg" alt="Second slide">
    <div class="carousel-caption d-none d-md-block">
      <h3>Second slide</h3>
      <p>In numquam omittam sea.</p>
    </div>
  </ng-template>
  <ng-template ngbSlide>
    <img class="d-block w-100" src="assets/img/bg/3.jpg" alt="Third slide">
    <div class="carousel-caption d-none d-md-block">
      <h3>Third slide</h3>
      <p>Lorem ipsum dolor sit amet, virtute consequat ea qui, minim graeco mel no.</p>
    </div>
  </ng-template>
</ngb-carousel>

<hr class="border-light container-m--x mt-5">

<h5 class="font-weight-bold pt-1 pb-1 mt-4 mb-4">ngx-swiper-wrapper</h5>

<div class="demo-vertical-spacing w-100">
  <!-- Default -->
  <div [swiper] class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
  </div>

  <!-- With arrows -->
  <div [swiper]="swiperWithArrows" class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right text-primary"></i></div>
    <div class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left text-primary"></i></div>
  </div>

  <!-- With pagination -->
  <div [swiper]="swiperWithPagination" class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <!-- With fraction pagination -->
  <div [swiper]="swiperWithFractionPagination" class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <!-- With progress -->
  <div [swiper]="swiperWithProgress" class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right"></i></div>
    <div class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left"></i></div>
  </div>

  <!-- With scrollbar -->
  <div [swiper]="swiperWithScrollbar" class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-scrollbar"></div>
  </div>

  <!-- Vertical -->
  <div [swiper]="verticalSwiper" class="swiper-container w-100" id="swiper-vertical">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <!-- Multiple slides -->
  <div [swiper]="swiperMultipleSlides" class="swiper-container w-100">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <!-- Fade effect -->
  <div [swiper]="swiperFadeEffect" class="swiper-container w-100" id="swiper-fade-effect">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination swiper-pagination-white"></div>
    <div class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right small"></i></div>
    <div class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left small"></i></div>
  </div>

  <!-- 3D cube effect -->
  <div [swiper]="swiper3dCubeEffect" class="swiper-container w-100" id="swiper-3d-cube-effect">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <!-- 3D coverflow effect -->
  <div [swiper]="swiper3dCoverflowEffect" class="swiper-container w-100" id="swiper-3d-coverflow-effect">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <!-- 3D flip effect -->
  <div [swiper]="swiper3dFlipEffect" class="swiper-container w-100" id="swiper-3d-flip-effect">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
    </div>
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right text-muted"></i></div>
    <div class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left text-muted"></i></div>
  </div>
</div>

// vue-demo/src/components/ui/Carousel.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Carousel
    </h4>

    <hr class="border-light container-m--x mt-0">

    <h5 class="font-weight-bold pt-1 pb-1 mt-4 mb-4">Bootstrap carousel</h5>

    <b-carousel controls indicators :interval="4000">
      <b-carousel-slide
        caption="First slide"
        text="Eos mutat malis maluisset et, agam ancillae quo te, in vim congue pertinacia."
        :img-src="`${baseUrl}img/bg/1.jpg`" />
      <b-carousel-slide
        caption="Second slide"
        text="In numquam omittam sea."
        :img-src="`${baseUrl}img/bg/2.jpg`" />
      <b-carousel-slide
        caption="Third slide"
        text="Lorem ipsum dolor sit amet, virtute consequat ea qui, minim graeco mel no."
        :img-src="`${baseUrl}img/bg/3.jpg`" />
    </b-carousel>

    <hr class="border-light container-m--x mt-5">

    <h5 class="font-weight-bold pt-1 pb-1 mt-4 mb-4">Vue Awesome Swiper</h5>

    <div class="demo-vertical-spacing w-100">
      <!-- Default -->
      <swiper class="swiper-container">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
      </swiper>

      <!-- With arrows -->
      <swiper class="swiper-container" :options="swiperWithArrows">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="button-prev" class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left text-primary"></i></div>
        <div slot="button-next" class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right text-primary"></i></div>
      </swiper>

      <!-- With pagination -->
      <swiper class="swiper-container" :options="swiperWithPagination">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
      </swiper>

      <!-- With fraction pagination -->
      <swiper class="swiper-container" :options="swiperWithFractionPagination">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
      </swiper>

      <!-- With progress -->
      <swiper class="swiper-container" :options="swiperWithProgress">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
        <div slot="button-prev" class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left"></i></div>
        <div slot="button-next" class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right"></i></div>
      </swiper>

      <!-- With scrollbar -->
      <swiper class="swiper-container" :options="swiperWithScrollbar">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="scrollbar" class="swiper-scrollbar"></div>
      </swiper>

      <!-- Vertical -->
      <swiper class="swiper-container" :options="verticalSwiper" id="swiper-vertical">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
      </swiper>

      <!-- Multiple slides -->
      <swiper class="swiper-container" :options="swiperMultipleSlides">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
      </swiper>

      <!-- Fade effect -->
      <swiper class="swiper-container" :options="swiperFadeEffect" id="swiper-fade-effect">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination swiper-pagination-white"></div>
        <div slot="button-prev" class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left small"></i></div>
        <div slot="button-next" class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right small"></i></div>
      </swiper>

      <!-- 3D cube effect -->
      <swiper class="swiper-container" :options="swiper3dCubeEffect" id="swiper-3d-cube-effect">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
      </swiper>

      <!-- 3D coverflow effect -->
      <swiper class="swiper-container" :options="swiper3dCoverflowEffect" id="swiper-3d-coverflow-effect">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
      </swiper>

      <!-- 3D flip effect -->
      <swiper class="swiper-container" :options="swiper3dFlipEffect" id="swiper-3d-flip-effect">
        <swiper-slide>I'm Slide 1</swiper-slide>
        <swiper-slide>I'm Slide 2</swiper-slide>
        <swiper-slide>I'm Slide 3</swiper-slide>
        <swiper-slide>I'm Slide 4</swiper-slide>
        <swiper-slide>I'm Slide 5</swiper-slide>
        <div slot="pagination" class="swiper-pagination"></div>
        <div slot="button-prev" class="swiper-button-prev custom-icon"><i class="lnr lnr-chevron-left text-muted small"></i></div>
        <div slot="button-next" class="swiper-button-next custom-icon"><i class="lnr lnr-chevron-right text-muted small"></i></div>
      </swiper>
    </div>
  </div>
</template>

<style>
.swiper-container .swiper-slide {
  padding: 5rem 0;
  text-align: center;
  font-size: 1.5rem;
  background: #ecebed;
}

#swiper-vertical {
  max-height: 195px;
}

#swiper-3d-cube-effect {
  max-width: 300px;
}

#swiper-3d-coverflow-effect .swiper-slide {
  max-width: 300px;
}

#swiper-3d-flip-effect,
#swiper-3d-flip-effect .swiper-slide {
  max-width: 300px;
}

#swiper-3d-flip-effect {
  padding: 50px;
}
</style>
<style src="@/vendor/libs/vue-awesome-swiper/vue-awesome-swiper.scss" lang="scss"></style>

<script>
import { swiper, swiperSlide } from 'vue-awesome-swiper'

export default {
  name: 'ui-carousel',
  metaInfo: {
    title: 'Carousel - UI elements'
  },
  components: {
    swiper,
    swiperSlide
  },
  data: () => ({
    swiperWithArrows: {
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      }
    },

    swiperWithPagination: {
      pagination: {
        el: '.swiper-pagination',
        clickable: true
      }
    },

    swiperWithFractionPagination: {
      pagination: {
        el: '.swiper-pagination',
        type: 'fraction'
      }
    },

    swiperWithProgress: {
      pagination: {
        el: '.swiper-pagination',
        type: 'progressbar'
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      }
    },

    swiperWithScrollbar: {
      scrollbar: {
        el: '.swiper-scrollbar',
        hide: true
      }
    },

    verticalSwiper: {
      direction: 'vertical',
      pagination: {
        el: '.swiper-pagination',
        clickable: true
      }
    },

    swiperMultipleSlides: {
      slidesPerView: 3,
      spaceBetween: 30,
      pagination: {
        el: '.swiper-pagination',
        clickable: true
      }
    },

    swiperFadeEffect: {
      effect: 'fade',
      pagination: {
        el: '.swiper-pagination',
        clickable: true
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      }
    },

    swiper3dCubeEffect: {
      effect: 'cube',
      grabCursor: true,
      cubeEffect: {
        shadow: true,
        slideShadows: true,
        shadowOffset: 20,
        shadowScale: 0.94
      },
      pagination: {
        el: '.swiper-pagination'
      }
    },

    swiper3dCoverflowEffect: {
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: true
      },
      pagination: {
        el: '.swiper-pagination'
      }
    },

    swiper3dFlipEffect: {
      effect: 'flip',
      grabCursor: true,
      pagination: {
        el: '.swiper-pagination'
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      }
    }
  })
}
</script>
