// angular-demo/src/app/+ui/footer/footer.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-footer', // tslint:disable-line
  templateUrl: './footer.component.html'
})
export class FooterComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Footer - UI elements';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Footer
</h4>

<nav class="footer bg-footer-theme pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-footer-theme</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-white pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-white</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-primary pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-primary</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-secondary pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-secondary</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-success pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-success</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-info pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-info</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-warning pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-warning</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-danger pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-danger</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-dark pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-dark</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-lighter pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-lighter</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

<nav class="footer bg-light pt-4 mb-4">
  <div class="container text-center py-4">
    <div class="pb-3">
      <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-light</a> <span class="align-top">©</span>
    </div>
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
      </div>
      <div class="col-sm pb-4">
        <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
        <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
      </div>
    </div>
  </div>
</nav>

// vue-demo/src/components/ui/Footer.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Footer
    </h4>

    <nav class="footer bg-footer-theme pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-footer-theme</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-white pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-white</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-primary pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-primary</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-secondary pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-secondary</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-success pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-success</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-info pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-info</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-warning pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-warning</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-danger pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-danger</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-dark pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-dark</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-lighter pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-lighter</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

    <nav class="footer bg-light pt-4 mb-4">
      <div class="container text-center py-4">
        <div class="pb-3">
          <a href="javascript:void(0)" class="footer-text text-large font-weight-normal">.bg-light</a> <span class="align-top">©</span>
        </div>
        <hr class="mb-4">
        <div class="row">
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">ABOUT US</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">About</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Our Story</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Shipping</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">CATEGORY</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Woman</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Man</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Kids</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">SUPPORT</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">FAQ</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Support</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Consultant</a>
          </div>
          <div class="col-sm pb-4">
            <div class="footer-text small font-weight-bold mb-3">PARTNERS</div>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Wholesale</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Office solutions</a>
            <a href="javascript:void(0)" class="footer-link d-block pb-2">Press Resource</a>
          </div>
        </div>
      </div>
    </nav>

  </div>
</template>

<script>
export default {
  name: 'ui-footer',
  metaInfo: {
    title: 'Footer - UI elements'
  }
}
</script>
