// angular-demo/src/app/+ui/tooltips-and-popovers/tooltips-and-popovers.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-tooltips-and-popovers', // tslint:disable-line
  templateUrl: './tooltips-and-popovers.component.html',
  styles: [`
    :host /deep/ .confirm-btn-container {
      flex-basis: auto !important;
    }
  `]
})
export class TooltipsAndPopoversComponent {
  isRTL: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Tooltips and popovers - UI elements';
    this.isRTL = appService.isRTL;
  }

  //
  // angular-confirmation-popover
  //

  confirm() {
    console.log('Confirmed');
  }

  cancel() {
    console.log('Cancelled');
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Tooltips and popovers
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    Tooltips
  </h6>
  <div class="card-body">
    <button type="button" class="btn btn-default" [placement]="isRTL ? 'left' : 'right'" ngbTooltip="Tooltip on right">Right</button>
    <button type="button" class="btn btn-default" placement="top" ngbTooltip="Tooltip on top">Top</button>
    <button type="button" class="btn btn-default" placement="bottom" ngbTooltip="Tooltip on bottom">Bottom</button>
    <button type="button" class="btn btn-default" [placement]="isRTL ? 'right' : 'left'" ngbTooltip="Tooltip on left">Left</button>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Variants</div>

    <button type="button" class="btn btn-default ngb-tooltip-primary" placement="top" ngbTooltip="Primary tooltip">Primary</button>
    <button type="button" class="btn btn-default ngb-tooltip-secondary" placement="bottom" ngbTooltip="Secondary tooltip">Secondary</button>
    <button type="button" class="btn btn-default ngb-tooltip-success" [placement]="isRTL ? 'left' : 'right'" ngbTooltip="Success tooltip">Success</button>
    <button type="button" class="btn btn-default ngb-tooltip-info" placement="top" ngbTooltip="Info tooltip">Info</button>
    <button type="button" class="btn btn-default ngb-tooltip-warning" placement="bottom" ngbTooltip="Warning tooltip">Warning</button>
    <button type="button" class="btn btn-default ngb-tooltip-danger" [placement]="isRTL ? 'right' : 'left'" ngbTooltip="Danger tooltip">Danger</button>
    <button type="button" class="btn btn-default ngb-tooltip-dark" placement="top" ngbTooltip="Dark tooltip">Dark</button>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    Popovers
  </h6>
  <div class="card-body">
    <button type="button" class="btn btn-default" [placement]="isRTL ? 'left' : 'right'"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Popover on right
    </button>
    <button type="button" class="btn btn-default" placement="top"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Popover on top
    </button>
    <button type="button" class="btn btn-default" placement="bottom"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Popover on bottom
    </button>
    <button type="button" class="btn btn-default" [placement]="isRTL ? 'right' : 'left'"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Popover on left
    </button>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Variants</div>

    <button type="button" class="btn btn-default ngb-popover-primary" [placement]="isRTL ? 'left' : 'right'"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Primary
    </button>
    <button type="button" class="btn btn-default ngb-popover-success" placement="top"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Success
    </button>
    <button type="button" class="btn btn-default ngb-popover-info" placement="bottom"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Info
    </button>
    <button type="button" class="btn btn-default ngb-popover-warning" [placement]="isRTL ? 'right' : 'left'"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Warning
    </button>
    <button type="button" class="btn btn-default ngb-popover-danger" placement="top"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Danger
    </button>
    <button type="button" class="btn btn-default ngb-popover-dark" placement="top"
            ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." popoverTitle="Popover title">
      Dark
    </button>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    angular-confirmation-popover
  </h6>
  <div class="card-body">
    <button class="btn btn-default"
      mwlConfirmationPopover
      popoverTitle="Popover title"
      popoverMessage="Popover description"
      [placement]="isRTL ? 'left' : 'right'"
      (confirm)="confirm()"
      (cancel)="cancel()">
      Right
    </button>

    <button class="btn btn-default"
      mwlConfirmationPopover
      popoverTitle="Popover title"
      popoverMessage="Popover description"
      placement="top"
      (confirm)="confirm()"
      (cancel)="cancel()">
      Top
    </button>

    <button class="btn btn-default"
      mwlConfirmationPopover
      popoverTitle="Popover title"
      popoverMessage="Popover description"
      placement="bottom"
      (confirm)="confirm()"
      (cancel)="cancel()">
      Bottom
    </button>

    <button class="btn btn-default"
      mwlConfirmationPopover
      popoverTitle="Popover title"
      popoverMessage="Popover description"
      [placement]="isRTL ? 'right' : 'left'"
      (confirm)="confirm()"
      (cancel)="cancel()">
      Left
    </button>
  </div>
</div>

// vue-demo/src/components/ui/TooltipsAndPopovers.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Tooltips and popovers
    </h4>

    <b-card no-body header="Tooltips" header-tag="h6" class="mb-4">
      <b-card-body class="demo-inline-spacing">
        <b-btn variant="default" v-b-tooltip.top title="Tooltip on top">Top</b-btn>
        <b-btn variant="default" v-b-tooltip.right title="Tooltip on right">Right</b-btn>
        <b-btn variant="default" v-b-tooltip.left title="Tooltip on left">Left</b-btn>
        <b-btn variant="default" v-b-tooltip.bottom title="Tooltip on bottom">Bottom</b-btn>
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="demo-inline-spacing">
        <div class="text-light small font-weight-semibold mb-3">Variants</div>

        <b-btn id="primaryTooltip" variant="default" title="Primary tooltip">Primary</b-btn>
        <b-tooltip id="primaryTooltip-container" container="primaryTooltip-container" target="primaryTooltip" class="tooltip-primary d-inline-block" placement="top" />

        <b-btn id="secondaryTooltip" variant="default" title="Secondary tooltip">Secondary</b-btn>
        <b-tooltip id="secondaryTooltip-container" container="secondaryTooltip-container" target="secondaryTooltip" class="tooltip-secondary d-inline-block" placement="bottom" />

        <b-btn id="successTooltip" variant="default" title="Success tooltip">Success</b-btn>
        <b-tooltip id="successTooltip-container" container="successTooltip-container" target="successTooltip" class="tooltip-success d-inline-block" placement="right" />

        <b-btn id="infoTooltip" variant="default" title="Info tooltip">Info</b-btn>
        <b-tooltip id="infoTooltip-container" container="infoTooltip-container" target="infoTooltip" class="tooltip-info d-inline-block" placement="left" />

        <b-btn id="warningTooltip" variant="default" title="Warning tooltip">Warning</b-btn>
        <b-tooltip id="warningTooltip-container" container="warningTooltip-container" target="warningTooltip" class="tooltip-warning d-inline-block" placement="bottom" />

        <b-btn id="dangerTooltip" variant="default" title="Danger tooltip">Danger</b-btn>
        <b-tooltip id="dangerTooltip-container" container="dangerTooltip-container" target="dangerTooltip" class="tooltip-danger d-inline-block" placement="left" />

        <b-btn id="darkTooltip" variant="default" title="Dark tooltip">Dark</b-btn>
        <b-tooltip id="darkTooltip-container" container="darkTooltip-container" target="darkTooltip" class="tooltip-dark d-inline-block" placement="top" />
      </b-card-body>
    </b-card>

    <b-card no-body header="Popovers" header-tag="h6" class="mb-4">
      <b-card-body class="demo-inline-spacing">
        <b-btn variant="default" v-b-popover.hover.focus.top="'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'" title="Tooltip on top">Top</b-btn>
        <b-btn variant="default" v-b-popover.hover.focus.right="'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'" title="Tooltip on right">Right</b-btn>
        <b-btn variant="default" v-b-popover.hover.focus.left="'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'" title="Tooltip on left">Left</b-btn>
        <b-btn variant="default" v-b-popover.hover.focus.bottom="'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'" title="Tooltip on bottom">Bottom</b-btn>
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="demo-inline-spacing">
        <div class="text-light small font-weight-semibold mb-3">Variants</div>

        <b-btn id="primaryPopover" variant="default" title="Primary popover">Primary</b-btn>
        <b-popover id="primaryPopover-container" container="primaryPopover-container" target="primaryPopover" class="popover-primary d-inline-block" placement="top" triggers="hover focus" content="Embedding content using properties is easy" />

        <b-btn id="secondaryPopover" variant="default" title="Secondary popover">Secondary</b-btn>
        <b-popover id="secondaryPopover-container" container="secondaryPopover-container" target="secondaryPopover" class="popover-secondary d-inline-block" placement="bottom" triggers="hover focus" content="Embedding content using properties is easy" />

        <b-btn id="successPopover" variant="default" title="Success popover">Success</b-btn>
        <b-popover id="successPopover-container" container="successPopover-container" target="successPopover" class="popover-success d-inline-block" placement="right" triggers="hover focus" content="Embedding content using properties is easy" />

        <b-btn id="infoPopover" variant="default" title="Info popover">Info</b-btn>
        <b-popover id="infoPopover-container" container="infoPopover-container" target="infoPopover" class="popover-info d-inline-block" placement="left" triggers="hover focus" content="Embedding content using properties is easy" />

        <b-btn id="warningPopover" variant="default" title="Warning popover">Warning</b-btn>
        <b-popover id="warningPopover-container" container="warningPopover-container" target="warningPopover" class="popover-warning d-inline-block" placement="bottom" triggers="hover focus" content="Embedding content using properties is easy" />

        <b-btn id="dangerPopover" variant="default" title="Danger popover">Danger</b-btn>
        <b-popover id="dangerPopover-container" container="dangerPopover-container" target="dangerPopover" class="popover-danger d-inline-block" placement="left" triggers="hover focus" content="Embedding content using properties is easy" />

        <b-btn id="darkPopover" variant="default" title="Dark popover">Dark</b-btn>
        <b-popover id="darkPopover-container" container="darkPopover-container" target="darkPopover" class="popover-dark d-inline-block" placement="top" triggers="hover focus" content="Embedding content using properties is easy" />
      </b-card-body>
    </b-card>

  </div>
</template>

<script>
export default {
  name: 'ui-tooltips-and-popovers',
  metaInfo: {
    title: 'Tooltips and popovers - UI elements'
  }
}
</script>
