// vue-demo-cli2-deprecated/src/cui-components/CuiUtilities.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Utilities</h3>
    <p class="ui-block-description">
      See more: <a href="https://getbootstrap.com/docs/4.0/utilities" target="_blank">https://getbootstrap.com/docs/4.0/utilities</a>
    </p>

    <h4 class="ui-block-heading">Border color</h4>

    <div class="cui-example">
      <div class="cui-utils-example-border-color">
        <span class="bg-lighter border-primary"></span>
        <span class="bg-lighter border-secondary"></span>
        <span class="bg-lighter border-success"></span>
        <span class="bg-lighter border-danger"></span>
        <span class="bg-lighter border-warning"></span>
        <span class="bg-lighter border-info"></span>
        <span class="bg-lighter border-light"></span>
        <span class="bg-lighter border-dark"></span>
        <span class="bg-lighter border-white"></span>
        <span class="bg-lighter border-transparent"></span>
      </div>
    </div>

    <h4 class="ui-block-heading">Text color</h4>

    <div class="cui-example cui-example-vertical-spacing">
      <div>
        <p><a href="javascript:void(0)" class="text-primary">Primary link</a></p>
        <p><a href="javascript:void(0)" class="text-secondary">Secondary link</a></p>
        <p><a href="javascript:void(0)" class="text-success">Success link</a></p>
        <p><a href="javascript:void(0)" class="text-danger">Danger link</a></p>
        <p><a href="javascript:void(0)" class="text-warning">Warning link</a></p>
        <p><a href="javascript:void(0)" class="text-info">Info link</a></p>
        <p><a href="javascript:void(0)" class="text-dark">Dark link</a></p>
        <p><a href="javascript:void(0)" class="text-muted">Muted link</a></p>
        <p><a href="javascript:void(0)" class="text-light">Light link</a></p>
        <p><a href="javascript:void(0)" class="text-lighter">Lighter link</a></p>
        <p><a href="javascript:void(0)" class="text-lightest">Lightest link</a></p>
      </div>
    </div>

    <h4 class="ui-block-heading">Background color</h4>

    <div class="cui-example cui-example-vertical-spacing">
      <div class="cui-utils-example-bg-color">
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-primary text-white"><code>.bg-primary</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-primary-dark text-white"><code>.bg-primary-dark</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-primary-darker text-white"><code>.bg-primary-darker</code></a>

          <div class="w-100"></div>

          <a href="javascript:void(0)" class="d-block col-sm bg-secondary text-white"><code>.bg-secondary</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-secondary-dark text-white"><code>.bg-secondary-dark</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-secondary-darker text-white"><code>.bg-secondary-darker</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-success text-white"><code>.bg-success</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-success-dark text-white"><code>.bg-success-dark</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-success-darker text-white"><code>.bg-success-darker</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-info text-white"><code>.bg-info</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-info-dark text-white"><code>.bg-info-dark</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-info-darker text-white"><code>.bg-info-darker</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-warning text-white"><code>.bg-warning</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-warning-dark text-white"><code>.bg-warning-dark</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-warning-darker text-white"><code>.bg-warning-darker</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-danger text-white"><code>.bg-danger</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-danger-dark text-white"><code>.bg-danger-dark</code></a>
          <a href="javascript:void(0)" class="d-block col-sm bg-danger-darker text-white"><code>.bg-danger-darker</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-light text-dark"><code>.bg-light</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-lighter text-dark"><code>.bg-lighter</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-lightest text-dark"><code>.bg-lightest</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-dark text-white"><code>.bg-dark</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-white text-dark"><code>.bg-white</code></a>
        </div>
        <div class="row mx-0">
          <a href="javascript:void(0)" class="d-block col-sm bg-transparent text-dark"><code>.bg-transparent</code></a>
        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Opacity</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <div class="bg-dark opacity-25 p-3"><code class="bg-transparent text-white">.opacity-25</code></div>
      <div class="bg-dark opacity-50 p-3"><code class="bg-transparent text-white">.opacity-50</code></div>
      <div class="bg-dark opacity-75 p-3"><code class="bg-transparent text-white">.opacity-75</code></div>
      <div class="bg-dark opacity-100 p-3"><code class="bg-transparent text-white">.opacity-100</code></div>
    </div>

    <h4 class="ui-block-heading">Text sizing</h4>

    <div class="cui-example">
      <!-- Tiny -->
      <p class="text-tiny">
        <code>.text-tiny</code> - Tiny text.
      </p>

      <!-- Big -->
      <p class="text-big">
        <code>.text-big</code> - Big text.
      </p>

      <!-- Large -->
      <p class="text-large">
        <code>.text-large</code> - Large text.
      </p>

      <!-- Extra large -->
      <p class="text-xlarge">
        <code>.text-xlarge</code> - Extra large.
      </p>
    </div>

    <h4 class="ui-block-heading">Font weight</h4>

    <div class="cui-example">
      <p>
        <code>.font-weight-bolder</code> - <span class="font-weight-bolder">Bolder text.</span>
      </p>
      <p>
        <code>.font-weight-semibold</code> - <span class="font-weight-semibold">Semibold text.</span>
      </p>
      <p>
        <code>.font-weight-light</code> - <span class="font-weight-light">Light text.</span>
      </p>
    </div>

    <h4 class="ui-block-heading">Line height</h4>

    <div class="cui-example">
      <p class="line-height-1">
        <code>.line-height-1</code> - line-height: 1<br>
        Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
      </p>

      <p class="line-height-condenced">
        <code>.line-height-condenced</code> - line-height: 1.3<br>
        Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
      </p>

      <p class="line-height-inherit">
        <code>.line-height-inherit</code> - line-height: inherit<br>
        Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
      </p>
    </div>

    <h4 class="ui-block-heading">Text decoration and transform</h4>

    <div class="cui-example">
      <p>
        <code>.text-decoration-none</code> - <span class="text-decoration-none" style="text-decoration: underline;">Text decoration - none</span>
      </p>

      <p>
        <code>.text-transform-none</code> - <span class="text-transform-none" style="text-transform: uppercase;">Text transform - none</span>
      </p>
    </div>

    <h4 class="ui-block-heading">Expanded text</h4>

    <div class="cui-example">
      <p>
        <code>.text-expanded</code> - <span class="text-expanded">Encrease letter-spacing property.</span>
      </p>
    </div>

    <h4 class="ui-block-heading">Shadows</h4>

    <div class="cui-example">
      <p class="box-shadow-none" style="box-shadow: 0 0 10px red">
        <code>.box-shadow-none</code> - box-shadow: none
      </p>
    </div>

    <h4 class="ui-block-heading">Overflow</h4>

    <div class="cui-example">
      <p class="text-nowrap overflow-hidden">
        <code>.overflow-hidden</code> - overflow: hidden<br>
        Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
      </p>

      <p class="text-nowrap overflow-scroll">
        <code>.overflow-scroll</code> - overflow: scroll<br>
        Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
      </p>

      <p class="overflow-auto text-nowrap">
        <code>.overflow-auto</code> - overflow: auto<br>
        Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
      </p>
    </div>

    <h4 class="ui-block-heading">Cursor</h4>

    <div class="cui-example">
      <div class="ui-bordered p-4 cursor-pointer">
        <code>.cursor-pointer</code> - cursor: pointer
      </div>
    </div>

    <h4 class="ui-block-heading">Sizing</h4>

    <p>Responsive variations for <code>.w-100</code> and <code>.w-auto</code>:</p>

    <ul>
      <li><code>.w-sm-100</code></li>
      <li><code>.w-md-100</code></li>
      <li><code>.w-lg-100</code></li>
      <li><code>.w-xl-100</code></li>
      <li><code>.w-sm-auto</code></li>
      <li><code>.w-md-auto</code></li>
      <li><code>.w-lg-auto</code></li>
      <li><code>.w-xl-auto</code></li>
    </ul>

    <h4 class="ui-block-heading">Layout container spacing</h4>

    <div class="cui-example mb-4">
      <div class="bg-light p-4 mb-4">
        <div class="bg-white container-p-x mb-4"><code>.container-p-x</code></div>
        <div class="bg-white container-p-y"><code>.container-p-y</code></div>
      </div>

      <p>Negative:</p>

      <div class="bg-light p-4">
        <div class="bg-light container-p-x mb-4">
          <div class="bg-white container-m--x"><code>.container-m--x</code></div>
        </div>
        <div class="bg-light container-p-y">
          <div class="bg-white container-m--y"><code>.container-m--y</code></div>
        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Negative horizontal margins</h4>

    <div class="cui-example mb-4">
      <div class="bg-light p-4">
        <div class="p-3">Top block</div>

        <div class="bg-dark text-white p-3 mx-lg--4">
          Collapse horizontal spacing on large screens
        </div>

        <div class="p-3">Bottom block</div>
      </div>
    </div>

    <p>
      The classes are named using the format <code>m{sides}--{size}</code>
      for xs and <code>m{sides}--{breakpoint}-{size}</code> for sm, md, lg, and xl.
    </p>

    <p>Where sides is one of:</p>

    <ul>
      <li><code>l</code> - for classes that set <code>margin-left</code></li>
      <li><code>r</code> - for classes that set <code>margin-right</code></li>
      <li><code>x</code> - for classes that set both <code>*-left</code> and <code>*-right</code></li>
    </ul>

    <p>Where size is one of:</p>

    <ul>
      <li><code>1</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * .25)</code></li>
      <li><code>2</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * .5)</code></li>
      <li><code>3</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer)</code></li>
      <li><code>4</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * 1.5)</code></li>
      <li><code>5</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * 3)</code></li>
    </ul>

    <h4 class="ui-block-heading">Flex</h4>

    <p><code>.flex-basis-100</code> - flex-basis: 100%</p>
    <p><code>.flex-basis-auto</code> - flex-basis: auto</p>

    <p>Responsive variations also exist for <code>.flex-basis-100</code> and <code>.flex-basis-auto</code>.</p>

    <ul>
      <li><code>.flex-basis-sm-100</code></li>
      <li><code>.flex-basis-md-100</code></li>
      <li><code>.flex-basis-lg-100</code></li>
      <li><code>.flex-basis-xl-100</code></li>
      <li><code>.flex-basis-sm-auto</code></li>
      <li><code>.flex-basis-md-auto</code></li>
      <li><code>.flex-basis-lg-auto</code></li>
      <li><code>.flex-basis-xl-auto</code></li>
    </ul>

    <h4 class="ui-block-heading">Bordered rows</h4>

    <div class="alert alert-info">
      <code>.row-bordered</code> class defines <code>overflow: hidden</code> on
      the parent container and <code>position: relative</code> on immediate children
      <code>.col</code> and <code>.col-*</code> blocks.
    </div>

    <div class="cui-example cui-example-vertical-spacing">
      <div class="row row-bordered">
        <div class="col p-3">Col 1</div>
        <div class="col p-3">Col 2</div>
        <div class="col p-3">Col 3</div>
        <div class="w-100"></div>
        <div class="col p-3">Col 4</div>
        <div class="col p-3">Col 5</div>
        <div class="col p-3">Col 6</div>
      </div>
      <div class="row row-bordered row-border-light">
        <div class="col-md-4 p-3">Col 1</div>
        <div class="col-md-4 p-3">Col 2</div>
        <div class="col-md-4 p-3">Col 3</div>
        <div class="col-md-4 p-3">Col 4</div>
        <div class="col-md-4 p-3">Col 5</div>
        <div class="col-md-4 p-3">Col 6</div>
      </div>
    </div>

    <h4 class="ui-block-heading">Transforms</h4>

    <div class="cui-example">
      <p class="font-weight-bold py-4">
        <code>.rotate-90</code> - <span class="rotate-90 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.rotate-180</code> - <span class="rotate-180 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.rotate-270</code> - <span class="rotate-270 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.rotate--90</code> - <span class="rotate--90 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.rotate--180</code> - <span class="rotate--180 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.rotate--270</code> - <span class="rotate--270 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.rotate-0</code> - <span class="rotate-0 d-inline-block">ROTATE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.scaleX--1</code> - <span class="scaleX--1 d-inline-block">SCALE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.scaleY--1</code> - <span class="scaleY--1 d-inline-block">SCALE</span>
      </p>

      <p>The next classes will have effect only in RTL mode:</p>

      <p class="font-weight-bold py-4">
        <code>.scaleX--1-rtl</code> - <span class="scaleX--1-rtl d-inline-block">SCALE</span>
      </p>

      <p class="font-weight-bold py-4">
        <code>.scaleY--1-rtl</code> - <span class="scaleY--1-rtl d-inline-block">SCALE</span>
      </p>
    </div>

    <h4 class="ui-block-heading">Fixes</h4>

    <div class="cui-example">
      <!-- flex-truncate -->
      <p><code>.flex-truncate</code> - Fix for truncated text within flexbox container</p>

      <!-- ie-mh-1 -->
      <p><code>.ie-mh-1</code> - Fix IE parent container height bug when containing image with fluid width</p>
    </div>
  </div>
</template>

<script>
export default {}
</script>

// angular-demo/src/app/+complete-ui/cui-utilities/cui-utilities.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-utilities', // tslint:disable-line
  templateUrl: './cui-utilities.component.html'
})
export class CuiUtilitiesComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">Utilities</h3>
  <p class="ui-block-description">
    See more: <a href="https://getbootstrap.com/docs/4.0/utilities" target="_blank">https://getbootstrap.com/docs/4.0/utilities</a>
  </p>

  <h4 class="ui-block-heading">Border color</h4>

  <div class="cui-example">
    <div class="cui-utils-example-border-color">
      <span class="bg-lighter border-primary"></span>
      <span class="bg-lighter border-secondary"></span>
      <span class="bg-lighter border-success"></span>
      <span class="bg-lighter border-danger"></span>
      <span class="bg-lighter border-warning"></span>
      <span class="bg-lighter border-info"></span>
      <span class="bg-lighter border-light"></span>
      <span class="bg-lighter border-dark"></span>
      <span class="bg-lighter border-white"></span>
      <span class="bg-lighter border-transparent"></span>
    </div>
  </div>

  <h4 class="ui-block-heading">Text color</h4>

  <div class="cui-example cui-example-vertical-spacing">
    <div>
      <p><a href="javascript:void(0)" class="text-primary">Primary link</a></p>
      <p><a href="javascript:void(0)" class="text-secondary">Secondary link</a></p>
      <p><a href="javascript:void(0)" class="text-success">Success link</a></p>
      <p><a href="javascript:void(0)" class="text-danger">Danger link</a></p>
      <p><a href="javascript:void(0)" class="text-warning">Warning link</a></p>
      <p><a href="javascript:void(0)" class="text-info">Info link</a></p>
      <p><a href="javascript:void(0)" class="text-dark">Dark link</a></p>
      <p><a href="javascript:void(0)" class="text-muted">Muted link</a></p>
      <p><a href="javascript:void(0)" class="text-light">Light link</a></p>
      <p><a href="javascript:void(0)" class="text-lighter">Lighter link</a></p>
      <p><a href="javascript:void(0)" class="text-lightest">Lightest link</a></p>
    </div>
  </div>

  <h4 class="ui-block-heading">Background color</h4>

  <div class="cui-example cui-example-vertical-spacing">
    <div class="cui-utils-example-bg-color">
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-primary text-white"><code>.bg-primary</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-primary-dark text-white"><code>.bg-primary-dark</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-primary-darker text-white"><code>.bg-primary-darker</code></a>

        <div class="w-100"></div>

        <a href="javascript:void(0)" class="d-block col-sm bg-secondary text-white"><code>.bg-secondary</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-secondary-dark text-white"><code>.bg-secondary-dark</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-secondary-darker text-white"><code>.bg-secondary-darker</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-success text-white"><code>.bg-success</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-success-dark text-white"><code>.bg-success-dark</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-success-darker text-white"><code>.bg-success-darker</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-info text-white"><code>.bg-info</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-info-dark text-white"><code>.bg-info-dark</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-info-darker text-white"><code>.bg-info-darker</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-warning text-white"><code>.bg-warning</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-warning-dark text-white"><code>.bg-warning-dark</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-warning-darker text-white"><code>.bg-warning-darker</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-danger text-white"><code>.bg-danger</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-danger-dark text-white"><code>.bg-danger-dark</code></a>
        <a href="javascript:void(0)" class="d-block col-sm bg-danger-darker text-white"><code>.bg-danger-darker</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-light text-dark"><code>.bg-light</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-lighter text-dark"><code>.bg-lighter</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-lightest text-dark"><code>.bg-lightest</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-dark text-white"><code>.bg-dark</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-white text-dark"><code>.bg-white</code></a>
      </div>
      <div class="row mx-0">
        <a href="javascript:void(0)" class="d-block col-sm bg-transparent text-dark"><code>.bg-transparent</code></a>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Opacity</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div class="bg-dark opacity-25 p-3"><code class="bg-transparent text-white">.opacity-25</code></div>
    <div class="bg-dark opacity-50 p-3"><code class="bg-transparent text-white">.opacity-50</code></div>
    <div class="bg-dark opacity-75 p-3"><code class="bg-transparent text-white">.opacity-75</code></div>
    <div class="bg-dark opacity-100 p-3"><code class="bg-transparent text-white">.opacity-100</code></div>
  </div>

  <h4 class="ui-block-heading">Text sizing</h4>

  <div class="cui-example">
    <!-- Tiny -->
    <p class="text-tiny">
      <code>.text-tiny</code> - Tiny text.
    </p>

    <!-- Big -->
    <p class="text-big">
      <code>.text-big</code> - Big text.
    </p>

    <!-- Large -->
    <p class="text-large">
      <code>.text-large</code> - Large text.
    </p>

    <!-- Extra large -->
    <p class="text-xlarge">
      <code>.text-xlarge</code> - Extra large.
    </p>
  </div>

  <h4 class="ui-block-heading">Font weight</h4>

  <div class="cui-example">
    <p>
      <code>.font-weight-bolder</code> - <span class="font-weight-bolder">Bolder text.</span>
    </p>
    <p>
      <code>.font-weight-semibold</code> - <span class="font-weight-semibold">Semibold text.</span>
    </p>
    <p>
      <code>.font-weight-light</code> - <span class="font-weight-light">Light text.</span>
    </p>
  </div>

  <h4 class="ui-block-heading">Line height</h4>

  <div class="cui-example">
    <p class="line-height-1">
      <code>.line-height-1</code> - line-height: 1<br>
      Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
    </p>

    <p class="line-height-condenced">
      <code>.line-height-condenced</code> - line-height: 1.3<br>
      Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
    </p>

    <p class="line-height-inherit">
      <code>.line-height-inherit</code> - line-height: inherit<br>
      Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
    </p>
  </div>

  <h4 class="ui-block-heading">Text decoration and transform</h4>

  <div class="cui-example">
    <p>
      <code>.text-decoration-none</code> - <span class="text-decoration-none" style="text-decoration: underline;">Text decoration - none</span>
    </p>

    <p>
      <code>.text-transform-none</code> - <span class="text-transform-none" style="text-transform: uppercase;">Text transform - none</span>
    </p>
  </div>

  <h4 class="ui-block-heading">Expanded text</h4>

  <div class="cui-example">
    <p>
      <code>.text-expanded</code> - <span class="text-expanded">Encrease letter-spacing property.</span>
    </p>
  </div>

  <h4 class="ui-block-heading">Shadows</h4>

  <div class="cui-example">
    <p class="box-shadow-none" style="box-shadow: 0 0 10px red">
      <code>.box-shadow-none</code> - box-shadow: none
    </p>
  </div>

  <h4 class="ui-block-heading">Overflow</h4>

  <div class="cui-example">
    <p class="text-nowrap overflow-hidden">
      <code>.overflow-hidden</code> - overflow: hidden<br>
      Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
    </p>

    <p class="text-nowrap overflow-scroll">
      <code>.overflow-scroll</code> - overflow: scroll<br>
      Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
    </p>

    <p class="overflow-auto text-nowrap">
      <code>.overflow-auto</code> - overflow: auto<br>
      Nullam ornare diam sed arcu interdum condimentum. Maecenas pharetra nibh interdum, laoreet ex et, dapibus lorem. Pellentesque a justo eu dolor tempus luctus. Suspendisse nec nisl quis ligula volutpat scelerisque vel a mi. Vivamus et velit elit. Aliquam consequat orci id arcu venenatis tempus. Donec varius convallis enim, ac auctor libero euismod eu. Nam rutrum molestie diam et sagittis. Integer consequat vestibulum interdum. Integer consequat scelerisque lectus, et viverra massa aliquam at. Phasellus consequat faucibus justo eu pulvinar. Maecenas tincidunt non urna in luctus. Vivamus et tellus tortor. In eleifend euismod imperdiet.
    </p>
  </div>

  <h4 class="ui-block-heading">Cursor</h4>

  <div class="cui-example">
    <div class="ui-bordered p-4 cursor-pointer">
      <code>.cursor-pointer</code> - cursor: pointer
    </div>
  </div>

  <h4 class="ui-block-heading">Sizing</h4>

  <p>Responsive variations for <code>.w-100</code> and <code>.w-auto</code>:</p>

  <ul>
    <li><code>.w-sm-100</code></li>
    <li><code>.w-md-100</code></li>
    <li><code>.w-lg-100</code></li>
    <li><code>.w-xl-100</code></li>
    <li><code>.w-sm-auto</code></li>
    <li><code>.w-md-auto</code></li>
    <li><code>.w-lg-auto</code></li>
    <li><code>.w-xl-auto</code></li>
  </ul>

  <h4 class="ui-block-heading">Layout container spacing</h4>

  <div class="cui-example mb-4">
    <div class="bg-light p-4 mb-4">
      <div class="bg-white container-p-x mb-4"><code>.container-p-x</code></div>
      <div class="bg-white container-p-y"><code>.container-p-y</code></div>
    </div>

    <p>Negative:</p>

    <div class="bg-light p-4">
      <div class="bg-light container-p-x mb-4">
        <div class="bg-white container-m--x"><code>.container-m--x</code></div>
      </div>
      <div class="bg-light container-p-y">
        <div class="bg-white container-m--y"><code>.container-m--y</code></div>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Negative horizontal margins</h4>

  <div class="cui-example mb-4">
    <div class="bg-light p-4">
      <div class="p-3">Top block</div>

      <div class="bg-dark text-white p-3 mx-lg--4">
        Collapse horizontal spacing on large screens
      </div>

      <div class="p-3">Bottom block</div>
    </div>
  </div>

  <p>
    The classes are named using the format <code>m{{'{'}}sides}--{{'{'}}size}</code>
    for xs and <code>m{{'{'}}sides}--{{'{'}}breakpoint}-{{'{'}}size}</code> for sm, md, lg, and xl.
  </p>

  <p>Where sides is one of:</p>

  <ul>
    <li><code>l</code> - for classes that set <code>margin-left</code></li>
    <li><code>r</code> - for classes that set <code>margin-right</code></li>
    <li><code>x</code> - for classes that set both <code>*-left</code> and <code>*-right</code></li>
  </ul>

  <p>Where size is one of:</p>

  <ul>
    <li><code>1</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * .25)</code></li>
    <li><code>2</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * .5)</code></li>
    <li><code>3</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer)</code></li>
    <li><code>4</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * 1.5)</code></li>
    <li><code>5</code> - (by default) for classes that set the <code>margin</code> to <code>-1 * ($spacer * 3)</code></li>
  </ul>

  <h4 class="ui-block-heading">Flex</h4>

  <p><code>.flex-basis-100</code> - flex-basis: 100%</p>
  <p><code>.flex-basis-auto</code> - flex-basis: auto</p>

  <p>Responsive variations also exist for <code>.flex-basis-100</code> and <code>.flex-basis-auto</code>.</p>

  <ul>
    <li><code>.flex-basis-sm-100</code></li>
    <li><code>.flex-basis-md-100</code></li>
    <li><code>.flex-basis-lg-100</code></li>
    <li><code>.flex-basis-xl-100</code></li>
    <li><code>.flex-basis-sm-auto</code></li>
    <li><code>.flex-basis-md-auto</code></li>
    <li><code>.flex-basis-lg-auto</code></li>
    <li><code>.flex-basis-xl-auto</code></li>
  </ul>

  <h4 class="ui-block-heading">Bordered rows</h4>

  <div class="alert alert-info">
    <code>.row-bordered</code> class defines <code>overflow: hidden</code> on
    the parent container and <code>position: relative</code> on immediate children
    <code>.col</code> and <code>.col-*</code> blocks.
  </div>

  <div class="cui-example cui-example-vertical-spacing">
    <div class="row row-bordered">
      <div class="col p-3">Col 1</div>
      <div class="col p-3">Col 2</div>
      <div class="col p-3">Col 3</div>
      <div class="w-100"></div>
      <div class="col p-3">Col 4</div>
      <div class="col p-3">Col 5</div>
      <div class="col p-3">Col 6</div>
    </div>
    <div class="row row-bordered row-border-light">
      <div class="col-md-4 p-3">Col 1</div>
      <div class="col-md-4 p-3">Col 2</div>
      <div class="col-md-4 p-3">Col 3</div>
      <div class="col-md-4 p-3">Col 4</div>
      <div class="col-md-4 p-3">Col 5</div>
      <div class="col-md-4 p-3">Col 6</div>
    </div>
  </div>

  <h4 class="ui-block-heading">Transforms</h4>

  <div class="cui-example">
    <p class="font-weight-bold py-4">
      <code>.rotate-90</code> - <span class="rotate-90 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.rotate-180</code> - <span class="rotate-180 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.rotate-270</code> - <span class="rotate-270 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.rotate--90</code> - <span class="rotate--90 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.rotate--180</code> - <span class="rotate--180 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.rotate--270</code> - <span class="rotate--270 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.rotate-0</code> - <span class="rotate-0 d-inline-block">ROTATE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.scaleX--1</code> - <span class="scaleX--1 d-inline-block">SCALE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.scaleY--1</code> - <span class="scaleY--1 d-inline-block">SCALE</span>
    </p>

    <p>The next classes will have effect only in RTL mode:</p>

    <p class="font-weight-bold py-4">
      <code>.scaleX--1-rtl</code> - <span class="scaleX--1-rtl d-inline-block">SCALE</span>
    </p>

    <p class="font-weight-bold py-4">
      <code>.scaleY--1-rtl</code> - <span class="scaleY--1-rtl d-inline-block">SCALE</span>
    </p>
  </div>

  <h4 class="ui-block-heading">Fixes</h4>

  <div class="cui-example">
    <!-- flex-truncate -->
    <p><code>.flex-truncate</code> - Fix for truncated text within flexbox container</p>

    <!-- ie-mh-1 -->
    <p><code>.ie-mh-1</code> - Fix IE parent container height bug when containing image with fluid width</p>
  </div>
</div>
