// vue-demo/src/components/forms/Editors.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Forms /</span> Editors
    </h4>

    <b-card header="Vue Simplemde" header-tag="h6" class="mb-4">
      <markdown-editor v-model="content" :configs="configs"></markdown-editor>
    </b-card>

    <b-card no-body header="Vue Quill Editor" header-tag="h6" class="mb-4" v-if="!isIE10Mode">
      <b-card-body>
        <quill-editor v-model="editorContent" :options="editorOptions" />
        <pre class="mt-4"><strong>Content:</strong><br>{{editorContent}}</pre>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Bubble</div>

        <quill-editor v-model="bubbleEditorContent" :options="bubbleEditorOptions" />
        <pre class="mt-4"><strong>Content:</strong><br>{{bubbleEditorContent}}</pre>
      </b-card-body>
    </b-card>

  </div>
</template>

<style src="simplemde/dist/simplemde.min.css" />
<style src="@/vendor/libs/vue-simplemde/vue-simplemde.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/typography.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-quill-editor/editor.scss" lang="scss"></style>

<script>
//
// Vue Simplemde
//

const isIE10 = typeof document.documentMode === 'number' && document.documentMode === 10

/* eslint-disable */

// Dirty hack to prevent fatal error in IE 10
if (isIE10) {
  Uint8Array.prototype.foo = function () { return 42 }
}

const markdownEditor = require('vue-simplemde/src/markdown-editor').default

if (isIE10) {
  delete Uint8Array.prototype.foo
  Uint8Array.prototype.foo = undefined
}
//

/* eslint-enable */

export default {
  name: 'forms-editors',
  metaInfo: {
    title: 'Editors - Forms'
  },
  components: {
    markdownEditor,
    quillEditor: () => import('vue-quill-editor/dist/vue-quill-editor').then(m => m.quillEditor).catch(() => {})
  },
  data: () => ({
    //
    // Vue Simplemde
    //

    content: `### Hello there
How are you?

I have bellow task for you :

Select from this text...
Click the bold on THIS WORD and make THESE ONE italic
Link GOOGLE to google.com
Test to insert image (and try to tab after write the image description)
Test Preview
And ending here... Click "List"

Enjoy!`,
    configs: {
      spellChecker: false
    },

    //
    // Vue Quill Editor
    //

    editorContent: '',
    bubbleEditorContent: '',

    editorOptions: {
      modules: {
        toolbar: [
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }, { 'font': [] }, { 'size': [] }],
          ['bold', 'italic', 'underline', 'strike'],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'script': 'sub' }, { 'script': 'super' }],
          ['blockquote', 'code-block'],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
          [{ 'direction': 'rtl' }, { 'align': [] }],
          ['link', 'image', 'video'],
          ['clean']
        ]
      }
    },

    bubbleEditorOptions: {
      theme: 'bubble',
      modules: {
        toolbar: [
          ['bold', 'italic', 'underline'],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'script': 'sub' }, { 'script': 'super' }],
          [{ 'header': 1 }, { 'header': 2 }],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
          [{ 'align': [] }],
          ['link', 'image', 'video'],
          ['clean']
        ]
      }
    }
  })
}
</script>

// angular-demo/src/app/+forms/editors/editors.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'forms-editors', // tslint:disable-line
  templateUrl: './editors.component.html',
  styleUrls: [
    '../../../vendor/libs/ngx-markdown-editor/ngx-markdown-editor.scss',
    '../../../vendor/libs/quill/typography.scss',
    '../../../vendor/libs/quill/editor.scss'
  ]
})
export class EditorsComponent {
  isIE10: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Editors - Forms';
    this.isIE10 = this.appService.isIE10;
  }

  markdownText = `### Hello there
How are you?

I have bellow task for you :

Select from this text...
Click the bold on THIS WORD and make THESE ONE italic
Link GOOGLE to google.com
Test to insert image (and try to tab after write the image description)
Test Preview
And ending here... Click "List"

Enjoy!`;

  editorContent = '';
  bubbleEditorContent = '';
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Forms /</span> Editors
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    ngx-markdown-editor
  </h6>
  <div class="card-body">
    <md-editor name="Content" [(ngModel)]="markdownText" [height]="'400px'" [options]="{}" required maxlength="500"></md-editor>
  </div>
</div>

<div class="card mb-4" *ngIf="!isIE10">
  <h6 class="card-header">
    Quill
  </h6>
  <div class="card-body">
    <quill-editor [(ngModel)]="editorContent" placeholder="Type something">
      <div quill-editor-toolbar>
        <span class="ql-formats">
          <select class="ql-font"></select>
          <select class="ql-size"></select>
        </span>
        <span class="ql-formats">
          <button class="ql-bold"></button>
          <button class="ql-italic"></button>
          <button class="ql-underline"></button>
          <button class="ql-strike"></button>
        </span>
        <span class="ql-formats">
          <select class="ql-color"></select>
          <select class="ql-background"></select>
        </span>
        <span class="ql-formats">
          <button class="ql-script" value="sub"></button>
          <button class="ql-script" value="super"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-header" value="1"></button>
          <button class="ql-header" value="2"></button>
          <button class="ql-blockquote"></button>
          <button class="ql-code-block"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-list" value="ordered"></button>
          <button class="ql-list" value="bullet"></button>
          <button class="ql-indent" value="-1"></button>
          <button class="ql-indent" value="+1"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-direction" value="rtl"></button>
          <select class="ql-align"></select>
        </span>
        <span class="ql-formats">
          <button class="ql-link"></button>
          <button class="ql-image"></button>
          <button class="ql-video"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-clean"></button>
        </span>
      </div>
    </quill-editor>

    <pre class="mt-4 mb-0">{{editorContent}}</pre>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Bubble</div>

    <quill-editor [(ngModel)]="bubbleEditorContent" theme="bubble" placeholder="Compose an epic...">
      <div quill-editor-toolbar>
        <span class="ql-formats">
          <button class="ql-bold"></button>
          <button class="ql-italic"></button>
          <button class="ql-underline"></button>
        </span>
        <span class="ql-formats">
          <select class="ql-color"></select>
          <select class="ql-background"></select>
        </span>
        <span class="ql-formats">
          <button class="ql-script" value="sub"></button>
          <button class="ql-script" value="super"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-header" value="1"></button>
          <button class="ql-header" value="2"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-list" value="ordered"></button>
          <button class="ql-list" value="bullet"></button>
          <button class="ql-indent" value="-1"></button>
          <button class="ql-indent" value="+1"></button>
        </span>
        <span class="ql-formats">
          <select class="ql-align"></select>
        </span>
        <span class="ql-formats">
          <button class="ql-link"></button>
          <button class="ql-image"></button>
          <button class="ql-video"></button>
        </span>
        <span class="ql-formats">
          <button class="ql-clean"></button>
        </span>
      </div>
    </quill-editor>

    <pre class="mt-4 mb-0">{{bubbleEditorContent}}</pre>
  </div>
</div>
