// angular-demo/src/app/+miscellaneous/numeraljs/numeraljs.component.ts
/// <reference types="numeral" />

import { Component } from '@angular/core';
import { AppService } from '../../app.service';
import * as numeral from 'numeral';

@Component({
  selector: 'miscellaneous-numeraljs', // tslint:disable-line
  templateUrl: './numeraljs.component.html'
})
export class NumeraljsComponent {
  example1 = '';
  example2 = '';
  example3 = '';
  example4 = '';
  example5 = '';

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Numeral.js - Miscellaneous';

    this.example1 = numeral(1000.1234).format('0,0');
    this.example2 = numeral(1000.1234).format('0,0.00');
    this.example3 = numeral(1000.1234).format('+0,0');
    this.example4 = numeral(1000.1234).format('.00');
    this.example5 = numeral(1000.1234).format('$0,0.00');
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Miscellaneous /</span> Numeral.js
</h4>

<hr class="border-light container-m--x mt-0 mb-4">

<div class="card">
  <div class="card-body demo-vertical-spacing">
    <p>{{ example1 }}</p>
    <p>{{ example2 }}</p>
    <p>{{ example3 }}</p>
    <p>{{ example4 }}</p>
    <p>{{ example5 }}</p>
  </div>
</div>

// vue-demo/src/components/miscellaneous/Numeraljs.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Miscellaneous /</span> Numeral.js
    </h4>

    <hr class="border-light container-m--x mt-0 mb-4">

    <b-card no-body>
      <b-card-body class="demo-vertical-spacing">
        <p>{{ example1 }}</p>
        <p>{{ example2 }}</p>
        <p>{{ example3 }}</p>
        <p>{{ example4 }}</p>
        <p>{{ example5 }}</p>
      </b-card-body>
    </b-card>
  </div>
</template>

<script>
import * as numeral from 'numeral'

export default {
  name: 'miscellaneous-numeraljs',
  metaInfo: {
    title: 'Numeral.js - Miscellaneous'
  },
  data: () => ({
    example1: numeral(1000.1234).format('0,0'),
    example2: numeral(1000.1234).format('0,0.00'),
    example3: numeral(1000.1234).format('+0,0'),
    example4: numeral(1000.1234).format('.00'),
    example5: numeral(1000.1234).format('$0,0.00')
  })
}
</script>
