// vue-demo-cli2-deprecated/src/cui-components/CuiInputGroups.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Input groups</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-input-group prepend="@">
        <b-input />
      </b-input-group>

      <b-input-group append="@example.com">
        <b-input placeholder="Recipient's username" />
      </b-input-group>

      <b-input-group prepend="https://example.com/users/">
        <b-input />
      </b-input-group>

      <b-input-group prepend="$" append=".00">
        <b-input />
      </b-input-group>

      <b-input-group>
        <b-input-group-text slot="prepend">$</b-input-group-text>
        <b-input-group-text slot="prepend">0.00</b-input-group-text>
        <b-input />
      </b-input-group>
    </div>

    <h4 class="ui-block-heading">Sizing</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-input-group size="sm" prepend="@">
        <b-input placeholder="Username" />
      </b-input-group>

      <b-input-group prepend="@">
        <b-input placeholder="Username" />
      </b-input-group>

      <b-input-group size="lg" prepend="@">
        <b-input placeholder="Username" />
      </b-input-group>
    </div>

    <h4 class="ui-block-heading">Checkbox and radio addons</h4>

    <div class="cui-example">
      <div class="row">
        <div class="col-md mb-3">

          <b-input-group>
            <b-input-group-text slot="prepend">
              <b-check class="px-2 m-0" />
            </b-input-group-text>
            <b-input placeholder="Username" />
          </b-input-group>

        </div>
        <div class="col-md mb-3">

          <b-input-group>
            <b-input-group-text slot="prepend">
              <b-radio class="px-2 m-0" />
            </b-input-group-text>
            <b-input placeholder="Username" />
          </b-input-group>

        </div>
        <div class="w-100"></div>
        <div class="col-md mb-3">

          <b-input-group>
            <b-input-group-text slot="prepend">
              <input type="checkbox">
            </b-input-group-text>
            <b-input placeholder="Username" />
          </b-input-group>

        </div>
        <div class="col-md mb-3">

          <b-input-group>
            <b-input-group-text slot="prepend">
              <input type="radio">
            </b-input-group-text>
            <b-input placeholder="Username" />
          </b-input-group>

        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Custom select</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-input-group>
        <b-select v-model="selected" :options="options" class="flex-grow-1" />
        <b-btn slot="append">Go!</b-btn>
      </b-input-group>

      <b-input-group>
        <b-input placeholder="Search for..." />
        <b-select v-model="selected" :options="options" />
        <b-btn slot="append">Go!</b-btn>
      </b-input-group>

      <b-input-group>
        <b-select v-model="selected" :options="options" />
        <b-input placeholder="Search for..." />
        <b-btn slot="append">Go!</b-btn>
      </b-input-group>

      <b-input-group>
        <b-btn slot="prepend">Go!</b-btn>
        <b-input placeholder="Search for..." />
        <b-select v-model="selected" :options="options" />
      </b-input-group>
    </div>

    <h4 class="ui-block-heading">Multiple addons</h4>

    <div class="cui-example">
      <div class="row">
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-input-group-text slot="prepend">$</b-input-group-text>
              <b-input-group-text slot="prepend">
                <input type="checkbox">
              </b-input-group-text>
              <b-input placeholder="Username" />
            </b-input-group>
          </b-form-group>

        </div>
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-input-group-text slot="prepend">$</b-input-group-text>
              <b-input-group-text slot="prepend">0.00</b-input-group-text>
              <b-input />
            </b-input-group>
          </b-form-group>

        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Button addons</h4>

    <div class="cui-example">
      <div class="row">
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-btn slot="prepend">Go!</b-btn>
              <b-input placeholder="Search for..." />
            </b-input-group>
          </b-form-group>

        </div>
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-input placeholder="Search for..." />
              <b-btn slot="append">Go!</b-btn>
            </b-input-group>
          </b-form-group>

        </div>
        <div class="w-100"></div>
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-btn slot="prepend">Hate it</b-btn>
              <b-input placeholder="Search for..." />
              <b-btn slot="append">Love it</b-btn>
            </b-input-group>
          </b-form-group>

        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Buttons with dropdowns</h4>

    <div class="cui-example">
      <div class="row">
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-dd text="Action" :right="isRTL" slot="prepend">
                <b-dd-item>Action 1</b-dd-item>
                <b-dd-item>Action 2</b-dd-item>
              </b-dd>
              <b-input placeholder="Search for..." />
            </b-input-group>
          </b-form-group>

        </div>
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-input placeholder="Search for..." />
              <b-dd text="Action" :right="!isRTL" slot="append">
                <b-dd-item>Action 1</b-dd-item>
                <b-dd-item>Action 2</b-dd-item>
              </b-dd>
            </b-input-group>
          </b-form-group>

        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Segmented buttons</h4>

    <div class="cui-example">
      <div class="row">
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-dd split text="Action" :right="isRTL" slot="prepend">
                <b-dd-item>Action 1</b-dd-item>
                <b-dd-item>Action 2</b-dd-item>
              </b-dd>
              <b-input placeholder="Search for..." />
            </b-input-group>
          </b-form-group>

        </div>
        <div class="col-md">

          <b-form-group>
            <b-input-group>
              <b-input placeholder="Search for..." />
              <b-dd split text="Action" :right="!isRTL" slot="append">
                <b-dd-item>Action 1</b-dd-item>
                <b-dd-item>Action 2</b-dd-item>
              </b-dd>
            </b-input-group>
          </b-form-group>

        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    options: [
      { text: 'Orange', value: 'orange' },
      { text: 'Apple', value: 'apple' },
      { text: 'Pineapple', value: 'pineapple' },
      { text: 'Grape', value: 'grape', disabled: true }
    ],
    selected: 'apple'
  })
}
</script>

// angular-demo/src/app/+complete-ui/cui-input-groups/cui-input-groups.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'cui-input-groups', // tslint:disable-line
  templateUrl: './cui-input-groups.component.html',
})
export class CuiInputGroupsComponent {
  isRTL: boolean;

  constructor(appService: AppService) {
    this.isRTL = appService.isRTL;
  }
}

<div class="ui-block">
  <h3 class="ui-block-heading">Input groups</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">@</span>
      </div>
      <input type="text" class="form-control" placeholder="Username">
    </div>

    <div class="input-group">
      <input type="text" class="form-control" placeholder="Recipient's username">
      <div class="input-group-append">
        <span class="input-group-text">@example.com</span>
      </div>
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">https://example.com/users/</span>
      </div>
      <input type="text" class="form-control">
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">$</span>
      </div>
      <input type="text" class="form-control">
      <div class="input-group-append">
        <span class="input-group-text">.00</span>
      </div>
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">$</span>
        <span class="input-group-text">0.00</span>
      </div>
      <input type="text" class="form-control">
    </div>
  </div>

  <h4 class="ui-block-heading">Sizing</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div class="input-group input-group-lg">
      <div class="input-group-prepend">
        <span class="input-group-text">@</span>
      </div>
      <input type="text" class="form-control" placeholder="Username">
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">@</span>
      </div>
      <input type="text" class="form-control" placeholder="Username">
    </div>

    <div class="input-group input-group-sm">
      <div class="input-group-prepend">
        <span class="input-group-text">@</span>
      </div>
      <input type="text" class="form-control" placeholder="Username">
    </div>
  </div>

  <h4 class="ui-block-heading">Checkbox and radio addons</h4>

  <div class="cui-example">
    <div class="row">
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <input type="checkbox">
              </div>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>

      </div>
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <input type="radio">
              </div>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>

      </div>
      <div class="w-100"></div>
      <div class="col-md">

        <!-- Custom checkbox -->
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <label class="custom-control custom-checkbox px-2 m-0">
                  <input type="checkbox" class="custom-control-input">
                  <span class="custom-control-label"></span>
                </label>
              </div>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>

      </div>
      <div class="col-md">

        <!-- Custom radio -->
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <label class="custom-control custom-radio px-2 m-0">
                  <input type="radio" class="custom-control-input">
                  <span class="custom-control-label"></span>
                </label>
              </div>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>

      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Custom select</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div class="input-group">
      <select class="custom-select flex-grow-1">
        <option>Select...</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
      <span class="input-group-append">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
    </div>

    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for...">
      <select class="custom-select">
        <option>Select...</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
      <span class="input-group-append">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
    </div>

    <div class="input-group">
      <select class="custom-select">
        <option>Select...</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
      <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-append">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
    </div>

    <div class="input-group">
      <span class="input-group-prepend">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
      <input type="text" class="form-control" placeholder="Search for...">
      <select class="custom-select">
        <option>Select...</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
    </div>
  </div>

  <h4 class="ui-block-heading">Multiple addons</h4>

  <div class="cui-example">
    <div class="row">
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <input type="checkbox">
              </span>
              <span class="input-group-text">$</span>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>

      </div>
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
              <span class="input-group-text">0.00</span>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>

      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Button addons</h4>

  <div class="cui-example">
    <div class="row">
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <span class="input-group-prepend">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
            <input type="text" class="form-control" placeholder="Search for...">
          </div>
        </div>

      </div>
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>

      </div>
      <div class="w-100"></div>
      <div class="col-md">

        <div class="form-group">
          <div class="input-group">
            <span class="input-group-prepend">
              <button class="btn btn-secondary" type="button">Hate it</button>
            </span>
            <input type="text" class="form-control" placeholder="Product name">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="button">Love it</button>
            </span>
          </div>
        </div>

      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Buttons with dropdowns</h4>

  <div class="cui-example">
    <div class="row">
      <div class="col-md">

        <div class="input-group">
          <div class="input-group-prepend d-inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
            <button class="btn btn-secondary" ngbDropdownToggle>Action</button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Action</a>
              <a class="dropdown-item" href="javascript:void(0)">Another action</a>
              <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
            </div>
          </div>
          <input type="text" class="form-control">
        </div>

      </div>
      <div class="col-md">

        <div class="input-group">
          <input type="text" class="form-control">
          <div class="input-group-append d-inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-left' : 'bottom-right'">
            <button class="btn btn-secondary" ngbDropdownToggle>Action</button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="!isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Action</a>
              <a class="dropdown-item" href="javascript:void(0)">Another action</a>
              <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Segmented buttons</h4>

  <div class="cui-example">
    <div class="row">
      <div class="col-md">

        <div class="input-group">
          <div class="input-group-prepend inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
            <button type="button" class="btn btn-secondary">Action</button>
            <button class="btn btn-secondary dropdown-toggle-split" ngbDropdownToggle></button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Action</a>
              <a class="dropdown-item" href="javascript:void(0)">Another action</a>
              <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
            </div>
          </div>
          <input type="text" class="form-control">
        </div>

      </div>
      <div class="col-md">

        <div class="input-group">
          <input type="text" class="form-control">
          <div class="input-group-append inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-left' : 'bottom-right'">
            <button type="button" class="btn btn-secondary">Action</button>
            <button class="btn btn-secondary dropdown-toggle-split" ngbDropdownToggle></button>
            <div ngbDropdownMenu [class.dropdown-menu-right]="!isRTL">
              <a class="dropdown-item" href="javascript:void(0)">Action</a>
              <a class="dropdown-item" href="javascript:void(0)">Another action</a>
              <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
