// angular-demo/src/app/+ui/pagination-and-breadcrumbs/pagination-and-breadcrumbs.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-pagination-and-breadcrumbs', // tslint:disable-line
  templateUrl: './pagination-and-breadcrumbs.component.html'
})
export class PaginationAndBreadcrumbsComponent {
  page = 4;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Pagination and breadcrumbs - UI elements';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Pagination and breadcrumbs
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    Pagination
  </h6>
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Default</div>

    <ngb-pagination [collectionSize]="120" [(page)]="page" [maxSize]="5"></ngb-pagination>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Sizes</div>

    <div class="demo-vertical-spacing-sm">
      <ngb-pagination [collectionSize]="120" [(page)]="page" [maxSize]="5" size="sm"></ngb-pagination>
      <ngb-pagination [collectionSize]="120" [(page)]="page" [maxSize]="5" size="lg"></ngb-pagination>
    </div>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    Breadcrumbs
  </h6>
  <div class="card-body demo-vertical-spacing">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Home</li>
    </ol>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
      <li class="breadcrumb-item active">Library</li>
    </ol>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
      <li class="breadcrumb-item"><a href="javascript:void(0)">Library</a></li>
      <li class="breadcrumb-item active">Data</li>
    </ol>
  </div>
</div>

// vue-demo-cli2-deprecated/src/components/ui/PaginationAndBreadcrumbs.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Pagination and breadcrumbs
    </h4>

    <b-card no-body header="Pagination" header-tag="h6" class="mb-4">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Default</div>

        <b-pagination size="md" :total-rows="100" v-model="currentPage" :per-page="10" />
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Sizes</div>

        <b-pagination size="sm" :total-rows="100" v-model="currentPage" :per-page="10" />
        <b-pagination size="lg" :total-rows="100" v-model="currentPage" :per-page="10" />
      </b-card-body>
    </b-card>

    <b-card no-body header="Breadcrumbs" header-tag="h6" class="mb-4">
      <b-card-body class="demo-vertical-spacing">
        <b-breadcrumb :items="items1"/>
        <b-breadcrumb :items="items2"/>
        <b-breadcrumb :items="items3"/>
      </b-card-body>
    </b-card>

  </div>
</template>

<script>
export default {
  name: 'ui-pagination-and-breadcrumbs',
  metaInfo: {
    title: 'Pagination and breadcrumbs - UI elements'
  },
  data: () => ({
    currentPage: 3,

    items1: [{ text: 'Admin', active: true }],
    items2: [{ text: 'Admin', href: '#' }, { text: 'Manage', active: true }],
    items3: [{ text: 'Admin', href: '#' }, { text: 'Manage', href: '#' }, { text: 'Library', active: true }]
  })
}
</script>
