// angular-demo/src/app/+complete-ui/cui-button-dropdowns/cui-button-dropdowns.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'cui-button-dropdowns', // tslint:disable-line
  templateUrl: './cui-button-dropdowns.component.html',
})
export class CuiButtonDropdownsComponent {
  isRTL: boolean;

  constructor(appService: AppService) {
    this.isRTL = appService.isRTL;
  }
}

<div class="ui-block">
  <h3 class="ui-block-heading">Button dropdowns</h3>

  <h4 class="ui-block-heading">Variations</h4>

  <div class="cui-example cui-example-inline-spacing">
    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-default" ngbDropdownToggle>Default</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-primary" ngbDropdownToggle>Primary</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-secondary" ngbDropdownToggle>Secondary</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-success" ngbDropdownToggle>Success</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-info" ngbDropdownToggle>Info</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-warning" ngbDropdownToggle>Warning</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-danger" ngbDropdownToggle>Danger</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-dark" ngbDropdownToggle>Dark</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Hidden arrow</h4>

  <div class="cui-example cui-example-inline-spacing">
    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
      <button class="btn btn-primary hide-arrow" ngbDropdownToggle>Primary</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="dropdown-toggle-hide-arrow d-inline-flex">
      <button class="btn btn-secondary" ngbDropdownToggle>Secondary</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Split</h4>

  <div class="cui-example cui-example-inline-spacing">
    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-default">Default</button>
      <button class="btn btn-default dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-primary">Primary</button>
      <button class="btn btn-primary dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-secondary">Secondary</button>
      <button class="btn btn-secondary dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-success">Success</button>
      <button class="btn btn-success dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-info">Info</button>
      <button class="btn btn-info dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-warning">Warning</button>
      <button class="btn btn-warning dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-danger">Danger</button>
      <button class="btn btn-danger dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button type="button" class="btn btn-dark">Dark</button>
      <button class="btn btn-dark dropdown-toggle-split" ngbDropdownToggle></button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Sizes</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button class="btn btn-default btn-xl" ngbDropdownToggle>Extra large button</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button class="btn btn-default btn-lg" ngbDropdownToggle>Large button</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button class="btn btn-default btn-sm" ngbDropdownToggle>Small button</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>

    <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
      <button class="btn btn-default btn-xs" ngbDropdownToggle>Extra small button</button>
      <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
        <a class="dropdown-item" href="javascript:void(0)">Action</a>
        <a class="dropdown-item" href="javascript:void(0)">Another action</a>
        <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
      </div>
    </div>
  </div>
</div>

// vue-demo-cli2-deprecated/src/cui-components/CuiButtonDropdowns.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Button dropdowns</h3>

    <h4 class="ui-block-heading">Variations</h4>

    <div class="cui-example cui-example-inline-spacing">
      <b-dd variant="default" text="Default" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="primary" text="Primary" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="secondary" text="Secondary" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="success" text="Success" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="info" text="Info" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="warning" text="Warning" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="danger" text="Danger" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd variant="dark" text="Dark" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
    </div>

    <h4 class="ui-block-heading">Hidden arrow</h4>

    <div class="cui-example cui-example-inline-spacing">
      <b-dd variant="primary" text="Primary" class="dropdown-toggle-hide-arrow" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
    </div>

    <h4 class="ui-block-heading">Split</h4>

    <div class="cui-example cui-example-inline-spacing">
      <b-dd split variant="default" text="Default" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="primary" text="Primary" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="secondary" text="Secondary" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="success" text="Success" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="info" text="Info" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="warning" text="Warning" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="danger" text="Danger" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>

      <b-dd split variant="dark" text="Dark" :right="isRTL">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
    </div>

    <h4 class="ui-block-heading">Sizes</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-dd text="Extra large button" :right="isRTL" class="btn-group-xl">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
      <br>

      <b-dd text="Large button" :right="isRTL" size="lg">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
      <br>

      <b-dd text="Small button" :right="isRTL" size="sm">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
      <br>

      <b-dd text="Extra small button" :right="isRTL" class="btn-group-xs">
        <b-dd-item>Action</b-dd-item>
        <b-dd-item>Another action</b-dd-item>
        <b-dd-item>Something else here</b-dd-item>
        <b-dd-divider></b-dd-divider>
        <b-dd-item>Separated link</b-dd-item>
      </b-dd>
    </div>
  </div>
</template>

<script>
export default {}
</script>
