// angular-demo/src/app/+complete-ui/cui-custom-select/cui-custom-select.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-custom-select', // tslint:disable-line
  templateUrl: './cui-custom-select.component.html'
})
export class CuiCustomSelectComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">Custom select</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <select class="custom-select">
      <option selected>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>
    <select class="custom-select" multiple>
      <option>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>
  </div>

  <h4 class="ui-block-heading">Sizes</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <select class="custom-select custom-select-lg">
      <option selected>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>
    <select class="custom-select custom-select-lg" multiple>
      <option>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>

    <select class="custom-select custom-select-sm">
      <option selected>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>
    <select class="custom-select custom-select-sm" multiple>
      <option>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>
  </div>

  <h4 class="ui-block-heading">Inverted</h4>

  <div class="cui-example">
    <div class="bg-dark p-4">
      <select class="custom-select custom-select-inverted">
        <option selected>Open this select menu</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
    </div>
  </div>

  <h4 class="ui-block-heading">Disabled</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <select class="custom-select" disabled="">
      <option selected>Open this select menu</option>
      <option>One</option>
      <option>Two</option>
      <option>Three</option>
    </select>

    <div class="bg-dark p-4">
      <select class="custom-select custom-select-inverted" disabled="">
        <option selected>Open this select menu</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
    </div>
  </div>

  <h4 class="ui-block-heading">Validations states</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <div class="form-group">
      <select class="custom-select is-valid">
        <option selected>Open this select menu</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
    </div>

    <div class="form-group">
      <select class="custom-select is-invalid">
        <option selected>Open this select menu</option>
        <option>One</option>
        <option>Two</option>
        <option>Three</option>
      </select>
    </div>
  </div>
</div>

// vue-demo-cli2-deprecated/src/cui-components/CuiCustomSelect.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Custom select</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-select v-model="selected" :options="options" />
      <b-select v-model="selected" :select-size="3" :options="options" />
    </div>

    <h4 class="ui-block-heading">Sizes</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-select v-model="selected" :options="options" size="lg" />
      <b-select v-model="selected" :select-size="3" :options="options" size="lg" />
      <b-select v-model="selected" :options="options" size="sm" />
      <b-select v-model="selected" :select-size="3" :options="options" size="sm" />
    </div>

    <h4 class="ui-block-heading">Inverted</h4>

    <div class="cui-example">
      <div class="bg-dark p-4">
        <b-select v-model="selected" :options="options" class="custom-select-inverted" />
      </div>
    </div>

    <h4 class="ui-block-heading">Disabled</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-select v-model="selected" :options="options" disabled />

      <div class="bg-dark p-4">
        <b-select v-model="selected" :options="options" class="custom-select-inverted" disabled />
      </div>
    </div>

    <h4 class="ui-block-heading">Validation states</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-select v-model="selected" :options="options" :state="'valid'" />
      <b-select v-model="selected" :options="options" :state="'invalid'" />
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    options: [
      { text: 'Orange', value: 'orange' },
      { text: 'Apple', value: 'apple' },
      { text: 'Pineapple', value: 'pineapple' },
      { text: 'Grape', value: 'grape', disabled: true }
    ],
    selected: 'apple'
  })
}
</script>
