// angular-demo/src/app/+complete-ui/cui-file-browser/cui-file-browser.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-file-browser', // tslint:disable-line
  templateUrl: './cui-file-browser.component.html'
})
export class CuiFileBrowserComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">File browser</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example">
    <label class="custom-file">
      <input type="file" class="custom-file-input">
      <span class="custom-file-label"></span>
    </label>
  </div>

  <h4 class="ui-block-heading">Disabled</h4>

  <div class="cui-example">
    <label class="custom-file">
      <input type="file" class="custom-file-input" disabled>
      <span class="custom-file-label"></span>
    </label>
  </div>

  <h4 class="ui-block-heading">Validations states</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <label class="custom-file">
      <input type="file" class="custom-file-input is-valid">
      <span class="custom-file-label"></span>
    </label>

    <label class="custom-file">
      <input type="file" class="custom-file-input is-invalid">
      <span class="custom-file-label"></span>
    </label>
  </div>
</div>

// vue-demo-cli2-deprecated/src/cui-components/CuiFileBrowser.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">File browser</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example">
      <b-file v-model="file"></b-file>
    </div>

    <h4 class="ui-block-heading">Disabled</h4>

    <div class="cui-example">
      <b-file v-model="file" disabled></b-file>
    </div>

    <h4 class="ui-block-heading">Validation states</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-file v-model="file" :state="'valid'"></b-file>
      <b-file v-model="file" :state="'invalid'"></b-file>
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    file: null
  })
}
</script>
