// angular-demo/src/app/+complete-ui/cui-forms/cui-forms.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-forms', // tslint:disable-line
  templateUrl: './cui-forms.component.html'
})
export class CuiFormsComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">Forms</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example">
    <form>
      <div class="form-group">
        <label class="form-label">Email address</label>
        <input type="email" class="form-control" placeholder="Email">
      </div>
      <div class="form-group">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" placeholder="Password">
      </div>
      <div class="form-group">
        <label class="form-label w-100">File input</label>
        <input type="file">
        <small class="form-text text-muted">Example block-level help text here.</small>
      </div>
      <div class="form-group">
        <label class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input">
          <span class="custom-control-label">Check this custom checkbox</span>
        </label>
      </div>
      <div class="form-group">
        <label class="form-check">
          <input class="form-check-input" type="checkbox" checked>
          <div class="form-check-label">
            Check me out
          </div>
        </label>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>

  <h4 class="ui-block-heading">Form row</h4>

  <div class="cui-example">
    <form>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label class="form-label">Email</label>
          <input type="email" class="form-control" placeholder="Email">
        </div>
        <div class="form-group col-md-6">
          <label class="form-label">Password</label>
          <input type="password" class="form-control" placeholder="Password">
        </div>
      </div>
      <div class="form-group">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" placeholder="1234 Main St">
      </div>
      <div class="form-group">
        <label class="form-label">Address 2</label>
        <input type="text" class="form-control" placeholder="Apartment, studio, or floor">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label class="form-label">City</label>
          <input type="text" class="form-control">
        </div>
        <div class="form-group col-md-4">
          <label class="form-label">State</label>
          <select class="custom-select">
            <option>Select state</option>
            <option>California</option>
            <option>Hawaii</option>
            <option>Florida</option>
            <option>Texas</option>
            <option>Massachusetts</option>
            <option>Alabama</option>
          </select>
        </div>
        <div class="form-group col-md-2">
          <label class="form-label">Zip</label>
          <input type="text" class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="custom-control custom-checkbox m-0">
          <input type="checkbox" class="custom-control-input">
          <span class="custom-control-label">Check this custom checkbox</span>
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Sign in</button>
    </form>
  </div>

  <h4 class="ui-block-heading">Horizontal</h4>

  <div class="cui-example">
    <form>
      <div class="form-group row">
        <label class="col-form-label col-sm-2 text-sm-right">Email</label>
        <div class="col-sm-10">
          <input type="email" class="form-control" placeholder="Email">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-form-label col-sm-2 text-sm-right">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" placeholder="Password">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-form-label col-sm-2 text-sm-right">Textarea</label>
        <div class="col-sm-10">
          <textarea class="form-control" placeholder="Textarea"></textarea>
        </div>
      </div>
      <fieldset class="form-group">
        <div class="row">
          <label class="col-form-legend col-sm-2 text-sm-right mt-sm-0">Radios</label>
          <div class="col-sm-10">
            <div class="custom-controls-stacked">
              <label class="custom-control custom-radio">
                <input name="custom-radio-3" type="radio" class="custom-control-input" checked="">
                <span class="custom-control-label">Option one is this and that&mdash;be sure to include why it's great</span>
              </label>
              <label class="custom-control custom-radio">
                <input name="custom-radio-3" type="radio" class="custom-control-input">
                <span class="custom-control-label">Option two can be something else and selecting it will deselect option one</span>
              </label>
              <label class="custom-control custom-radio">
                <input name="custom-radio-3" type="radio" class="custom-control-input" disabled>
                <span class="custom-control-label">Option three is disabled</span>
              </label>
            </div>
          </div>
        </div>
      </fieldset>
      <div class="form-group row">
        <label class="col-form-legend col-sm-2 text-sm-right mt-sm-0">Checkbox</label>
        <div class="col-sm-10">
          <label class="custom-control custom-checkbox m-0">
            <input type="checkbox" class="custom-control-input">
            <span class="custom-control-label">Check me out</span>
          </label>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10 ml-sm-auto">
          <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
      </div>
    </form>
  </div>

  <h4 class="ui-block-heading">Inline</h4>

  <div class="cui-example cui-example-vertical-spacing">
    <form class="form-inline">
      <label class="sr-only">Name</label>
      <input type="text" class="form-control mr-sm-2 mb-2 mb-sm-0" placeholder="Jane Doe">

      <label class="sr-only">Username</label>
      <div class="input-group mr-sm-2 mb-2 mb-sm-0">
        <div class="input-group-prepend">
          <div class="input-group-text">@</div>
        </div>
        <input type="text" class="form-control" placeholder="Username">
      </div>

      <label class="form-check mr-sm-2 mb-2 mb-sm-0">
        <input class="form-check-input" type="checkbox">
        <div class="form-check-label">
          Remember me
        </div>
      </label>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <form class="form-inline">
      <label class="form-label mr-sm-2">Preference</label>
      <select class="custom-select mr-sm-2 mb-2 mb-sm-0">
        <option selected>Choose...</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
      </select>

      <label class="custom-control custom-checkbox mr-sm-2 mb-2 mb-sm-0">
        <input type="checkbox" class="custom-control-input">
        <span class="custom-control-label">Remember my preference</span>
      </label>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>

  <h4 class="ui-block-heading">Help text</h4>

  <div class="cui-example cui-example-vertical-spacing">
    <form>
      <div class="form-group">
        <label class="form-label">Password</label>
        <input type="password" class="form-control">
        <small class="form-text text-muted">
          Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
        </small>
      </div>
    </form>

    <form class="form-inline">
      <div class="form-group">
        <label class="form-label">Password</label>
        <input type="password" class="form-control mx-sm-3">
        <small class="text-muted">
          Must be 8-20 characters long.
        </small>
      </div>
    </form>
  </div>

  <h4 class="ui-block-heading">Static controls</h4>

  <div class="cui-example cui-example-vertical-spacing">
    <form>
      <div class="form-group row">
        <label class="col-form-label col-sm-2 text-sm-right">Email</label>
        <div class="col-sm-10">
          <div class="form-control-plaintext">example.email.com</div>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-form-label col-sm-2 text-sm-right">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" placeholder="Password">
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10 ml-sm-auto">
          <button type="submit" class="btn btn-default">Confirm identity</button>
        </div>
      </div>
    </form>

    <!-- Inline form -->
    <form class="form-inline">
      <div class="form-control-plaintext mr-sm-2 mb-2 mb-sm-0">example.email.com</div>
      <input type="password" class="form-control mr-sm-2 mb-2 mb-sm-0" placeholder="Password">
      <button type="submit" class="btn btn-default">Confirm identity</button>
    </form>
  </div>

  <h4 class="ui-block-heading">States</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <!-- Valid -->
    <div class="form-group">
      <label class="form-label">Valid</label>
      <input type="text" class="form-control is-valid">
      <small class="valid-feedback">A block of help text that breaks onto a new line and may extend beyond one line.</small>
    </div>

    <!-- Invalid -->
    <div class="form-group">
      <label class="form-label">Invalid</label>
      <input type="text" class="form-control is-invalid">
      <small class="invalid-feedback">A block of help text that breaks onto a new line and may extend beyond one line.</small>
    </div>

    <!-- With tooltip -->
    <div class="form-group position-relative">
      <label class="form-label">Invalid with tooltip</label>
      <input type="text" class="form-control is-invalid">
      <div class="invalid-tooltip">Please provide a valid state.</div>
    </div>
  </div>

  <h4 class="ui-block-heading">Sizes</h4>

  <div class="cui-example cui-example-vertical-spacing">
    <form>
      <!-- Large -->
      <div class="form-group">
        <label class="form-label form-label-lg">Large label</label>
        <input type="text" class="form-control form-control-lg" placeholder="Large input">
      </div>

      <!-- Small -->
      <div class="form-group">
        <label class="form-label form-label-sm">Small label</label>
        <input type="text" class="form-control form-control-sm" placeholder="Small input">
      </div>
    </form>

    <form>
      <!-- Large -->
      <div class="form-group row">
        <label class="col-form-label col-form-label-lg col-sm-2 text-sm-right">Large label</label>
        <div class="col-sm-10">
          <input type="text" class="form-control form-control-lg" placeholder="Large input">
        </div>
      </div>

      <!-- Small -->
      <div class="form-group row">
        <label class="col-form-label col-form-label-sm col-sm-2 text-sm-right">Small label</label>
        <div class="col-sm-10">
          <input type="text" class="form-control form-control-sm" placeholder="Small input">
        </div>
      </div>
    </form>
  </div>
</div>

// vue-demo-cli2-deprecated/src/cui-components/CuiForms.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Forms</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example">
      <b-form>
        <b-form-group label="Email address">
          <b-input type="email" placeholder="Email" />
        </b-form-group>
        <b-form-group label="Password">
          <b-input type="password" placeholder="Password" />
        </b-form-group>
        <b-form-group label="File input" description="Example block-level help text here.">
          <b-file />
        </b-form-group>
        <b-form-group>
          <b-check>Check this custom checkbox</b-check>
        </b-form-group>
        <b-form-group>
          <b-check plain>Check me out</b-check>
        </b-form-group>
        <b-btn type="submit" variant="default">Submit</b-btn>
      </b-form>
    </div>

    <h4 class="ui-block-heading">Form row</h4>

    <div class="cui-example">
      <form>
        <b-form-row>
          <b-form-group label="Email" class="col-md-6">
            <b-input type="email" placeholder="Email" />
          </b-form-group>
          <b-form-group label="Password" class="col-md-6">
            <b-input type="password" placeholder="Password" />
          </b-form-group>
        </b-form-row>
        <b-form-group label="Address">
          <b-input placeholder="1234 Main St" />
        </b-form-group>
        <b-form-group label="Address 2">
          <b-input placeholder="Apartment, studio, or floor" />
        </b-form-group>
        <b-form-row>
          <b-form-group label="City" class="col-md-6">
            <b-input />
          </b-form-group>
          <b-form-group label="State" class="col-md-4">
            <b-select value="Select state" :options="['Select state','California','Hawaii','Florida','Texas','Massachusetts','Alabama']" />
          </b-form-group>
          <b-form-group label="Zip" class="col-md-2">
            <b-input />
          </b-form-group>
        </b-form-row>
        <b-form-group>
          <b-check>Check this custom checkbox</b-check>
        </b-form-group>
        <b-btn type="submit" variant="primary">Sign in</b-btn>
      </form>
    </div>

    <h4 class="ui-block-heading">Horizontal</h4>

    <div class="cui-example">
      <b-form>
        <b-form-group horizontal :label-cols="2">
          <div slot="label" class="text-sm-right pr-sm-2">Email</div>
          <b-input type="email" placeholder="Email" />
        </b-form-group>
        <b-form-group horizontal :label-cols="2">
          <div slot="label" class="text-sm-right pr-sm-2">Password</div>
          <b-input type="password" placeholder="Password" />
        </b-form-group>
        <b-form-group horizontal :label-cols="2">
          <div slot="label" class="text-sm-right pr-sm-2">Textarea</div>
          <b-textarea placeholder="Textarea" :rows="3" />
        </b-form-group>
        <b-form-group horizontal :label-cols="2" label-class="pt-sm-0">
          <div slot="label" class="text-sm-right pr-sm-2">Radios</div>
          <b-radio-group stacked :options="options" :checked="1" />
        </b-form-group>
        <b-form-group horizontal :label-cols="2" label-class="pt-sm-0">
          <div slot="label" class="text-sm-right pr-sm-2">Checkbox</div>
          <b-check>Check me out</b-check>
        </b-form-group>
        <b-form-row>
          <div class="col-sm-10 ml-sm-auto">
            <b-btn type="submit" variant="primary">Sign in</b-btn>
          </div>
        </b-form-row>
      </b-form>
    </div>

    <h4 class="ui-block-heading">Inline</h4>

    <div class="cui-example cui-example-vertical-spacing">
      <b-form inline>
        <b-input class="mr-sm-2 mb-2 mb-sm-0" placeholder="Jane Doe" />
        <b-input-group class="mr-sm-2 mb-2 mb-sm-0">
          <b-input-group-addon slot="left">@</b-input-group-addon>
          <b-input placeholder="Username" />
        </b-input-group>
        <b-check class="mr-sm-2 mb-2 mb-sm-0">Remember me</b-check>
        <b-btn variant="primary">Save</b-btn>
      </b-form>

      <b-form inline>
        <label class="form-label mr-sm-2">Preference</label>
        <b-select class="custom-select mr-sm-2 mb-2 mb-sm-0" value="Choose..." :options="['Choose...','One','Two','Three']" />
        <b-check class="mr-sm-2 mb-2 mb-sm-0">Remember my preference</b-check>
        <b-btn variant="primary">Submit</b-btn>
      </b-form>
    </div>

    <h4 class="ui-block-heading">Help text</h4>

    <div class="cui-example cui-example-vertical-spacing">
      <b-form>
        <b-form-group label="Password" description="Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.">
          <b-input type="password" />
        </b-form-group>
      </b-form>

      <b-form inline>
        <label class="form-label mr-sm-2">Password</label>
        <b-input type="password" class="mr-sm-2" />
        <small class="text-muted">Password must be 8-20 characters long</small>
      </b-form>
    </div>

    <h4 class="ui-block-heading">Static controls</h4>

    <div class="cui-example cui-example-vertical-spacing">
      <b-form>
        <b-form-group horizontal :label-cols="2">
          <div slot="label" class="text-sm-right pr-sm-2">Email</div>
          <b-input plaintext value="example@email.com" />
        </b-form-group>
        <b-form-group horizontal :label-cols="2">
          <div slot="label" class="text-sm-right pr-sm-2">Password</div>
          <b-input type="password" placeholder="Password" />
        </b-form-group>
        <b-form-row>
          <div class="col-sm-10 ml-sm-auto">
            <button type="submit" class="btn btn-default">Confirm identity</button>
          </div>
        </b-form-row>
      </b-form>

      <!-- Inline form -->
      <b-form inline>
        <b-input plaintext value="example@email.com" class="w-auto mr-sm-2 mb-2 mb-sm-0" />
        <b-input type="password" placeholder="Password" class="mr-sm-2 mb-2 mb-sm-0" />
        <button type="submit" class="btn btn-default">Confirm identity</button>
      </b-form>
    </div>

    <h4 class="ui-block-heading">States</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <!-- Valid -->
      <b-form-group label="Valid">
        <b-input :state="'valid'" />
      </b-form-group>

      <!-- Invalid -->
      <b-form-group label="Invalid" feedback="A block of help text that breaks onto a new line and may extend beyond one line.">
        <b-input :state="'invalid'" />
      </b-form-group>

      <!-- With tooltip -->
      <b-form-group label="Invalid with tooltip" class="position-relative">
        <b-input :state="'invalid'" />
        <div class="invalid-tooltip">Please provide a valid state.</div>
      </b-form-group>
    </div>

    <h4 class="ui-block-heading">Sizes</h4>

    <div class="cui-example cui-example-vertical-spacing">
      <b-form>
        <!-- Large -->
        <b-form-group>
          <label class="form-label form-label-lg">Large label</label>
          <b-input size="lg" placeholder="Large input" />
        </b-form-group>

        <!-- Small -->
        <b-form-group>
          <label class="form-label form-label-sm">Small label</label>
          <b-input size="sm" placeholder="Small input" />
        </b-form-group>
      </b-form>

      <b-form>
        <!-- Large -->
        <b-form-row class="mb-3">
          <label class="col-form-label col-form-label-lg col-sm-2 text-sm-right">Large label</label>
          <div class="col-sm-10">
            <b-input size="lg" placeholder="Large input" />
          </div>
        </b-form-row>

        <!-- Small -->
        <b-form-row>
          <label class="col-form-label col-form-label-sm col-sm-2 text-sm-right">Small label</label>
          <div class="col-sm-10">
            <b-input size="sm" placeholder="Small input" />
          </div>
        </b-form-row>
      </b-form>
    </div>
  </div>

</template>

<script>
export default {
  data: () => ({
    options: [
      { text: 'Option one is this and that&mdash;be sure to include why it\'s great', value: 1 },
      { text: 'Option two can be something else and selecting it will deselect option one', value: 2 },
      { text: 'Option three is disabled', value: 3, disabled: true }
    ]
  })
}
</script>
