// angular-demo/src/app/+complete-ui/cui-media/cui-media.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-media', // tslint:disable-line
  templateUrl: './cui-media.component.html'
})
export class CuiMediaComponent {}

<div class="ui-block">
  <h3 class="ui-block-heading">Media</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example">
    <div class="media">
      <a href="javascript:void(0)" class="d-flex mr-3">
        <img src="assets/img/avatars/1-small.png" alt="" style="width:46px;height:46px;" class="rounded">
      </a>
      <div class="media-body">
        <a href="javascript:void(0)">Mike Greene</a>
        <span class="text-muted">commented on</span>
        <a href="javascript:void(0)">Article Name</a>
        <p class="my-1">
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
          ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
          tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
          Donec lacinia congue felis in faucibus.
        </p>
        <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
        <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-up mr-2"></span></a>
        <span class="d-block float-left text-muted small">2 hours ago</span>
      </div>
    </div>

    <hr>

    <div class="media">
      <a href="javascript:void(0)" class="d-flex mr-3">
        <img src="assets/img/avatars/2-small.png" alt="" style="width:46px;height:46px;" class="rounded">
      </a>
      <div class="media-body">
        <a href="javascript:void(0)">Leon Wilson</a>
        <span class="text-muted">commented on</span>
        <a href="javascript:void(0)">Article Name</a>
        <p class="my-1">
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
          ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
          tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
          Donec lacinia congue felis in faucibus.
        </p>
        <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
        <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-up mr-2"></span></a>
        <span class="d-block float-left text-muted small">2 hours ago</span>
      </div>
    </div>

    <hr>

    <div class="media">
      <a href="javascript:void(0)" class="d-flex mr-3">
        <img src="assets/img/avatars/3-small.png" alt="" style="width:46px;height:46px;" class="rounded">
      </a>
      <div class="media-body">
        <a href="javascript:void(0)">Allie Rodriguez</a>
        <span class="text-muted">commented on</span>
        <a href="javascript:void(0)">Article Name</a>
        <p class="my-1">
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
          ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
          tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
          Donec lacinia congue felis in faucibus.
        </p>
        <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
        <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-up mr-2"></span></a>
        <span class="d-block float-left text-muted small">2 hours ago</span>
      </div>
    </div>
  </div>

  <h4 class="ui-block-heading">Nesting</h4>

  <div class="cui-example">
    <div class="media">
      <a href="javascript:void(0)" class="d-flex mr-3">
        <img src="assets/img/avatars/4-small.png" alt="" style="width:46px;height:46px;" class="rounded">
      </a>
      <div class="media-body">
        <a href="javascript:void(0)">Kenneth Frazier</a> <span class="text-muted small">14 hours ago</span>
        <p class="my-1">
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
          ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
          tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
          Donec lacinia congue felis in faucibus.
        </p>
        <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
        <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
        <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
        <a href="javascript:void(0)" class="text-muted small">Reply</a>

        <div class="media mt-3">
          <a href="javascript:void(0)" class="d-flex mr-3">
            <img src="assets/img/avatars/5-small.png" alt="" style="width:32px;height:32px;" class="rounded">
          </a>
          <div class="media-body">
            <a href="javascript:void(0)">Nelle Maxwell</a> <span class="text-muted small">14 hours ago</span>
            <p class="my-1">
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
              ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
              tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
              Donec lacinia congue felis in faucibus.
            </p>
            <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
            <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
            <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
            <a href="javascript:void(0)" class="text-muted small">Reply</a>

            <div class="media mt-3">
              <a href="javascript:void(0)" class="d-flex mr-3">
                <img src="assets/img/avatars/6-small.png" alt="" style="width:32px;height:32px;" class="rounded">
              </a>
              <div class="media-body">
                <a href="javascript:void(0)">Nelle Maxwell</a> <span class="text-muted small">14 hours ago</span>
                <p class="my-1">
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                  ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
                  tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
                  Donec lacinia congue felis in faucibus.
                </p>
                <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
                <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
                <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
                <a href="javascript:void(0)" class="text-muted small">Reply</a>
              </div>
            </div>
          </div>
        </div>

        <div class="media mt-3">
          <a href="javascript:void(0)" class="d-flex mr-3">
            <img src="assets/img/avatars/7-small.png" alt="" style="width:32px;height:32px;" class="rounded">
          </a>
          <div class="media-body">
            <a href="javascript:void(0)">Alice Hampton</a> <span class="text-muted small">14 hours ago</span>
            <p class="my-1">
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
              ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
              tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
              Donec lacinia congue felis in faucibus.
            </p>
            <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
            <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
            <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
            <a href="javascript:void(0)" class="text-muted small">Reply</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

// vue-demo-cli2-deprecated/src/cui-components/CuiMedia.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Media</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example">
      <div class="media">
        <a href="javascript:void(0)" class="d-flex mr-3">
          <img :src="`${baseUrl}img/avatars/1-small.png`" alt="" style="width:46px;height:46px;" class="rounded">
        </a>
        <div class="media-body">
          <a href="javascript:void(0)">Mike Greene</a>
          <span class="text-muted">commented on</span>
          <a href="javascript:void(0)">Article Name</a>
          <p class="my-1">
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
            ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
            tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
            Donec lacinia congue felis in faucibus.
          </p>
          <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
          <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-up mr-2"></span></a>
          <span class="d-block float-left text-muted small">2 hours ago</span>
        </div>
      </div>

      <hr>

      <div class="media">
        <a href="javascript:void(0)" class="d-flex mr-3">
          <img :src="`${baseUrl}img/avatars/2-small.png`" alt="" style="width:46px;height:46px;" class="rounded">
        </a>
        <div class="media-body">
          <a href="javascript:void(0)">Leon Wilson</a>
          <span class="text-muted">commented on</span>
          <a href="javascript:void(0)">Article Name</a>
          <p class="my-1">
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
            ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
            tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
            Donec lacinia congue felis in faucibus.
          </p>
          <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
          <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-up mr-2"></span></a>
          <span class="d-block float-left text-muted small">2 hours ago</span>
        </div>
      </div>

      <hr>

      <div class="media">
        <a href="javascript:void(0)" class="d-flex mr-3">
          <img :src="`${baseUrl}img/avatars/3-small.png`" alt="" style="width:46px;height:46px;" class="rounded">
        </a>
        <div class="media-body">
          <a href="javascript:void(0)">Allie Rodriguez</a>
          <span class="text-muted">commented on</span>
          <a href="javascript:void(0)">Article Name</a>
          <p class="my-1">
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
            ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
            tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
            Donec lacinia congue felis in faucibus.
          </p>
          <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
          <a href="javascript:void(0)" class="d-block float-right text-muted small"><span class="ion ion-ios-thumbs-up mr-2"></span></a>
          <span class="d-block float-left text-muted small">2 hours ago</span>
        </div>
      </div>
    </div>

    <h4 class="ui-block-heading">Nesting</h4>

    <div class="cui-example">
      <div class="media">
        <a href="javascript:void(0)" class="d-flex mr-3">
          <img :src="`${baseUrl}img/avatars/4-small.png`" alt="" style="width:46px;height:46px;" class="rounded">
        </a>
        <div class="media-body">
          <a href="javascript:void(0)">Kenneth Frazier</a> <span class="text-muted small">14 hours ago</span>
          <p class="my-1">
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
            ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
            tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
            Donec lacinia congue felis in faucibus.
          </p>
          <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
          <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
          <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
          <a href="javascript:void(0)" class="text-muted small">Reply</a>

          <div class="media mt-3">
            <a href="javascript:void(0)" class="d-flex mr-3">
              <img :src="`${baseUrl}img/avatars/5-small.png`" alt="" style="width:32px;height:32px;" class="rounded">
            </a>
            <div class="media-body">
              <a href="javascript:void(0)">Nelle Maxwell</a> <span class="text-muted small">14 hours ago</span>
              <p class="my-1">
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
                tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
                Donec lacinia congue felis in faucibus.
              </p>
              <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
              <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
              <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
              <a href="javascript:void(0)" class="text-muted small">Reply</a>

              <div class="media mt-3">
                <a href="javascript:void(0)" class="d-flex mr-3">
                  <img :src="`${baseUrl}img/avatars/6-small.png`" alt="" style="width:32px;height:32px;" class="rounded">
                </a>
                <div class="media-body">
                  <a href="javascript:void(0)">Nelle Maxwell</a> <span class="text-muted small">14 hours ago</span>
                  <p class="my-1">
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                    ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
                    tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
                    Donec lacinia congue felis in faucibus.
                  </p>
                  <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
                  <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
                  <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
                  <a href="javascript:void(0)" class="text-muted small">Reply</a>
                </div>
              </div>
            </div>
          </div>

          <div class="media mt-3">
            <a href="javascript:void(0)" class="d-flex mr-3">
              <img :src="`${baseUrl}img/avatars/7-small.png`" alt="" style="width:32px;height:32px;" class="rounded">
            </a>
            <div class="media-body">
              <a href="javascript:void(0)">Alice Hampton</a> <span class="text-muted small">14 hours ago</span>
              <p class="my-1">
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque
                ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at,
                tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
                Donec lacinia congue felis in faucibus.
              </p>
              <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-up"></span></a>&nbsp;&nbsp;
              <a href="javascript:void(0)" class="text-muted small"><span class="ion ion-ios-thumbs-down"></span></a>
              <span class="text-muted small">&nbsp;&nbsp;·&nbsp;&nbsp;</span>
              <a href="javascript:void(0)" class="text-muted small">Reply</a>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>
