// angular-demo/src/app/+complete-ui/cui-pagination/cui-pagination.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-pagination', // tslint:disable-line
  templateUrl: './cui-pagination.component.html'
})
export class CuiPaginationComponent {
  page = 4;
}

<div class="ui-block ui-block-inline ui-block-pagination">
  <h3 class="ui-block-heading">Pagination</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example">
    <ngb-pagination [collectionSize]="120" [(page)]="page" [maxSize]="5"></ngb-pagination>
  </div>

  <h4 class="ui-block-heading">Sizes</h4>

  <div class="cui-example cui-example-vertical-spacing-sm">
    <ngb-pagination [collectionSize]="120" [(page)]="page" [maxSize]="5" size="sm"></ngb-pagination>
    <ngb-pagination [collectionSize]="120" [(page)]="page" [maxSize]="5" size="lg"></ngb-pagination>
  </div>
</div>

// vue-demo-cli2-deprecated/src/cui-components/CuiPagination.vue
<template>
  <div class="ui-block ui-block-inline ui-block-pagination">
    <h3 class="ui-block-heading">Pagination</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example">
      <b-pagination size="md" :total-rows="100" v-model="currentPage" :per-page="10" />
    </div>

    <h4 class="ui-block-heading">Sizes</h4>

    <div class="cui-example cui-example-vertical-spacing-sm">
      <b-pagination size="sm" :total-rows="100" v-model="currentPage" :per-page="10" />
      <b-pagination size="lg" :total-rows="100" v-model="currentPage" :per-page="10" />
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    currentPage: 3
  })
}
</script>
