// vue-demo-cli2-deprecated/src/components/ui/Dropdowns.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Dropdowns
    </h4>

    <div class="bg-lighter rounded p-4 mb-4 clearfix">
      <div class="dropdown-menu d-block position-static float-left">
        <b-dd-item><b-badge variant="success" class="float-right">34</b-badge>Action</b-dd-item>
        <b-dd-item><b-badge pill variant="primary" class="float-right">16</b-badge>Another action</b-dd-item>
        <b-dd-item disabled>Something else here</b-dd-item>
        <b-dd-divider />
        <b-dd-header>Dropdown header</b-dd-header>
        <b-dd-item active><i class="ion ion-md-cloud"></i> &nbsp;With icon</b-dd-item>
        <b-dd-item>Last action</b-dd-item>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">

        <b-card header="Nested" header-tag="h6" class="mb-4">
          <b-dd variant="default" text="Nested dropdowns" :right="isRTL">
            <b-dd-item>First action</b-dd-item>

            <div class="dropdown-toggle">
              <b-dd-item>First menu</b-dd-item>
              <div class="dropdown-menu">
                <b-dd-item>First action</b-dd-item>
                <b-dd-item>Second action</b-dd-item>

                <div class="dropdown-toggle">
                  <b-dd-item>First menu</b-dd-item>
                  <div class="dropdown-menu">
                    <b-dd-item>First action</b-dd-item>
                    <b-dd-item>Second action</b-dd-item>
                  </div>
                </div>
              </div>
            </div>

            <b-dd-item>Second action</b-dd-item>

            <div class="dropdown-toggle">
              <b-dd-item>Second menu</b-dd-item>
              <div class="dropdown-menu">
                <b-dd-item>First action</b-dd-item>
                <b-dd-item>Second action</b-dd-item>
              </div>
            </div>
          </b-dd>
        </b-card>

      </div>
      <div class="col-md-6">

        <b-card header="Hover" header-tag="h6" class="mb-4">
          <b-dd v-hover-dropdown variant="primary" text="Hover" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider />
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
        </b-card>

      </div>
    </div>

    <b-card no-body header="Button dropdowns" header-tag="h6" class="mb-4">
      <b-card-body>
        <small class="text-light font-weight-semibold">Variations</small>
        <div class="demo-inline-spacing mt-3">
          <b-dd variant="default" text="Default" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="primary" text="Primary" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="secondary" text="Secondary" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="success" text="Success" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="info" text="Info" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="warning" text="Warning" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="danger" text="Danger" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="dark" text="Dark" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <small class="text-light font-weight-semibold">Hidden arrow</small>
        <div class="demo-inline-spacing mt-3">
          <b-dd variant="primary" text="Primary" class="dropdown-toggle-hide-arrow" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd variant="secondary" text="Secondary" class="dropdown-toggle-hide-arrow" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <small class="text-light font-weight-semibold">Split</small>
        <div class="demo-inline-spacing mt-3">
          <b-dd split variant="default" text="Default" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="primary" text="Primary" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="secondary" text="Secondary" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="success" text="Success" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="info" text="Info" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="warning" text="Warning" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="danger" text="Danger" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>

          <b-dd split variant="dark" text="Dark" :right="isRTL">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <small class="text-light font-weight-semibold">Sizes</small>
        <div class="demo-vertical-spacing-sm mt-3">
          <b-dd text="Extra large button" :right="isRTL" class="btn-group-xl">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
          <br>

          <b-dd text="Large button" :right="isRTL" size="lg">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
          <br>

          <b-dd text="Small button" :right="isRTL" size="sm">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
          <br>

          <b-dd text="Extra small button" :right="isRTL" class="btn-group-xs">
            <b-dd-item>Action</b-dd-item>
            <b-dd-item>Another action</b-dd-item>
            <b-dd-item>Something else here</b-dd-item>
            <b-dd-divider></b-dd-divider>
            <b-dd-item>Separated link</b-dd-item>
          </b-dd>
        </div>
      </b-card-body>
    </b-card>

    <b-card header="Vue Context Menu" header-tag="h6" class="mb-4">
      <div class="text-center" style="height: 300px; border:1px solid #ddd" @contextmenu.prevent="$refs.ctxMenu.open">
        <span style="line-height: 300px">Right click anywhere inside this box</span>
      </div>

      <context-menu id="ctxMenuExample" ref="ctxMenu">
        <button type="button" class="dropdown-item" @click="clicked('Option 1')">Option 1</button>
        <button type="button" class="dropdown-item disabled">Option 2</button>
        <button type="button" class="dropdown-item" @click="clicked('Option 3')">Option 3</button>
      </context-menu>
    </b-card>

  </div>
</template>

<style src="@/vendor/libs/vue-context-menu/vue-context-menu.scss" lang="scss"></style>

<script>
import '@/vendor/libs/hover-dropdown/HoverDropdown'
import contextMenu from 'vue-context-menu'

export default {
  name: 'ui-dropdowns',
  metaInfo: {
    title: 'Dropdowns - UI elements'
  },
  components: {
    contextMenu
  },
  methods: {
    clicked (item) {
      alert(`${item} clicked!`)
    }
  }
}
</script>

// angular-demo/src/app/+ui/dropdowns/dropdowns.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-dropdowns', // tslint:disable-line
  templateUrl: './dropdowns.component.html',
  styleUrls: ['../../../vendor/libs/ngx-contextmenu/ngx-contextmenu.scss'],
  encapsulation: ViewEncapsulation.None
})
export class DropdownsComponent {
  isRTL: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Dropdowns - UI elements';
    this.isRTL = appService.isRTL;
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Dropdowns
</h4>

<div class="bg-lighter rounded p-4 mb-4 clearfix">
  <div class="dropdown-menu d-block position-static float-left">
    <a class="dropdown-item" href="javascript:void(0)">
      <span class="badge badge-success float-right">34</span>Action</a>
    <a class="dropdown-item" href="javascript:void(0)">
      <span class="badge badge-pill badge-primary float-right">16</span>Another action</a>
    <a class="dropdown-item disabled" href="javascript:void(0)">Something else here</a>
    <div class="dropdown-divider"></div>
    <h6 class="dropdown-header">Dropdown header</h6>
    <a class="dropdown-item active" href="javascript:void(0)">
      <i class="ion ion-md-cloud"></i> &nbsp;With icon</a>
    <a class="dropdown-item" href="javascript:void(0)">Last action</a>
  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <div class="card mb-4">
      <h6 class="card-header">
        Nested
      </h6>
      <div class="card-body">
        <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
          <button class="btn btn-default" ngbDropdownToggle>Nested dropdowns</button>
          <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
            <a class="dropdown-item" href="javascript:void(0)">First action</a>

            <!-- Level two -->
            <div class="dropdown-toggle">
              <div class="dropdown-item">First menu</div>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="javascript:void(0)">First action</a>
                <a class="dropdown-item" href="javascript:void(0)">Second action</a>

                <!-- Level three -->
                <div class="dropdown-toggle">
                  <div class="dropdown-item">Second menu</div>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="javascript:void(0)">First action</a>
                    <a class="dropdown-item" href="javascript:void(0)">Second action</a>
                  </div>
                </div>

              </div>
            </div>

            <a class="dropdown-item" href="javascript:void(0)">Second action</a>

            <!-- Level two -->
            <div class="dropdown-toggle">
              <div class="dropdown-item">Second menu</div>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="javascript:void(0)">First action</a>
                <a class="dropdown-item" href="javascript:void(0)">Second action</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-6">

    <div class="card mb-4">
      <h6 class="card-header">
        Hover
      </h6>
      <div class="card-body">
        <div ngbDropdown hoverDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
          <button type="button" class="btn btn-primary dropdown-toggle" ngbDropdownToggle>Hover</button>
          <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
            <a class="dropdown-item" href="javascript:void(0)">Action</a>
            <a class="dropdown-item" href="javascript:void(0)">Another action</a>
            <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    Button dropdowns
  </h6>
  <div class="card-body">
    <small class="text-light font-weight-semibold">Variations</small>
    <div class="demo-inline-spacing mt-3">
      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-default" ngbDropdownToggle>Default</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-primary" ngbDropdownToggle>Primary</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-secondary" ngbDropdownToggle>Secondary</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-success" ngbDropdownToggle>Success</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-info" ngbDropdownToggle>Info</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-warning" ngbDropdownToggle>Warning</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-danger" ngbDropdownToggle>Danger</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-dark" ngbDropdownToggle>Dark</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <small class="text-light font-weight-semibold">Hidden arrow</small>
    <div class="demo-inline-spacing mt-3">
      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="d-inline-flex">
        <button class="btn btn-primary hide-arrow" ngbDropdownToggle>Primary</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'" class="dropdown-toggle-hide-arrow d-inline-flex">
        <button class="btn btn-secondary" ngbDropdownToggle>Secondary</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <small class="text-light font-weight-semibold">Split</small>
    <div class="demo-inline-spacing mt-3">
      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-default">Default</button>
        <button class="btn btn-default dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-primary">Primary</button>
        <button class="btn btn-primary dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-secondary">Secondary</button>
        <button class="btn btn-secondary dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-success">Success</button>
        <button class="btn btn-success dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-info">Info</button>
        <button class="btn btn-info dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-warning">Warning</button>
        <button class="btn btn-warning dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-danger">Danger</button>
        <button class="btn btn-danger dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div class="btn-group inline-flex" ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button type="button" class="btn btn-dark">Dark</button>
        <button class="btn btn-dark dropdown-toggle-split" ngbDropdownToggle></button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <small class="text-light font-weight-semibold">Sizes</small>
    <div class="demo-vertical-spacing-sm mt-3">
      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-default btn-xl" ngbDropdownToggle>Extra large button</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-default btn-lg" ngbDropdownToggle>Large button</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-default btn-sm" ngbDropdownToggle>Small button</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>

      <div ngbDropdown [placement]="isRTL ? 'bottom-right' : 'bottom-left'">
        <button class="btn btn-default btn-xs" ngbDropdownToggle>Extra small button</button>
        <div ngbDropdownMenu [class.dropdown-menu-right]="isRTL">
          <a class="dropdown-item" href="javascript:void(0)">Action</a>
          <a class="dropdown-item" href="javascript:void(0)">Another action</a>
          <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void(0)">Separated link</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    ngx-contextmenu
  </h6>
  <div class="card-body">
    <div [contextMenu]="basicMenu" class="text-center" style="height: 300px; border:1px solid #ddd">
      <span style="line-height: 300px">Right click anywhere inside this box</span>
    </div>

    <context-menu #basicMenu>
      <ng-template contextMenuItem>View</ng-template>
      <ng-template contextMenuItem>Copy</ng-template>
      <ng-template contextMenuItem>Paste</ng-template>

      <ng-template contextMenuItem [subMenu]="basicSubMenu">Actions</ng-template>

      <context-menu #basicSubMenu>
        <ng-template contextMenuItem>Lock</ng-template>
        <ng-template contextMenuItem>Update</ng-template>
        <ng-template contextMenuItem>Delete</ng-template>
      </context-menu>

      <ng-template contextMenuItem divider="true"></ng-template>
      <ng-template contextMenuItem passive="true">
        <input type="text" class="form-control form-control-sm" placeholder="Dropdown input">
      </ng-template>
    </context-menu>
  </div>
</div>
