// vue-demo-cli2-deprecated/src/components/ui/ProgressBars.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Progress bars
    </h4>

    <b-card no-body class="mb-4">
      <b-card-body class="card-body">
        <div class="text-light small font-weight-semibold mb-3">Default</div>

        <b-progress :value="60" height="0.75rem" />
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="card-body">
        <div class="text-light small font-weight-semibold mb-3">Height</div>

        <b-progress :value="60" height="0.25rem" />
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="card-body">
        <div class="text-light small font-weight-semibold mb-3">With label</div>

        <b-progress :value="30" show-progress height="0.75rem" />
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="card-body">
        <div class="text-light small font-weight-semibold mb-3">Variations</div>

        <div class="demo-vertical-spacing-sm">
          <b-progress variant="secondary" :value="30" height="0.75rem" />
          <b-progress variant="success" :value="40" height="0.75rem" />
          <b-progress variant="info" :value="20" height="0.75rem" />
          <b-progress variant="warning" :value="60" height="0.75rem" />
          <b-progress variant="danger" :value="80" height="0.75rem" />
          <b-progress variant="dark" :value="50" height="0.75rem" />
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="card-body">
        <div class="text-light small font-weight-semibold mb-3">Striped</div>

        <div class="demo-vertical-spacing-sm">
          <b-progress striped :value="45" height="0.75rem" />
          <b-progress variant="secondary" striped :value="30" height="0.75rem" />
          <b-progress variant="success" striped :value="40" height="0.75rem" />
          <b-progress variant="info" striped :value="20" height="0.75rem" />
          <b-progress variant="warning" striped :value="60" height="0.75rem" />
          <b-progress variant="danger" striped :value="80" height="0.75rem" />
          <b-progress variant="dark" striped :value="50" height="0.75rem" />
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body class="card-body">
        <div class="text-light small font-weight-semibold mb-3">Animated</div>

        <div class="demo-vertical-spacing-sm">
          <b-progress striped animated :value="45" height="0.75rem" />
          <b-progress variant="secondary" striped animated :value="30" height="0.75rem" />
          <b-progress variant="success" striped animated :value="40" height="0.75rem" />
          <b-progress variant="info" striped animated :value="20" height="0.75rem" />
          <b-progress variant="warning" striped animated :value="60" height="0.75rem" />
          <b-progress variant="danger" striped animated :value="80" height="0.75rem" />
          <b-progress variant="dark" striped animated :value="50" height="0.75rem" />
        </div>
      </b-card-body>
    </b-card>

  </div>
</template>

<script>
export default {
  name: 'ui-progress-bars',
  metaInfo: {
    title: 'Progress bars - UI elements'
  }
}
</script>

// angular-demo/src/app/+ui/progress-bars/progress-bars.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-progress-bars', // tslint:disable-line
  templateUrl: './progress-bars.component.html'
})
export class ProgressBarsComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Progress bars - UI elements';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Progress bars
</h4>

<div class="card mb-4">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Default</div>

    <ngb-progressbar [value]="60"></ngb-progressbar>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">With label</div>

    <ngb-progressbar [showValue]="true" [value]="30"></ngb-progressbar>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Variations</div>

    <div class="demo-vertical-spacing-sm">
      <p><ngb-progressbar [value]="30" type="secondary"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="40" type="success"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="20" type="info"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="60" type="warning"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="80" type="danger"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="50" type="dark"></ngb-progressbar></p>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Striped</div>

    <div class="demo-vertical-spacing-sm">
      <p><ngb-progressbar [value]="45" [striped]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="30" type="secondary" [striped]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="40" type="success" [striped]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="20" type="info" [striped]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="60" type="warning" [striped]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="80" type="danger" [striped]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="50" type="dark" [striped]="true"></ngb-progressbar></p>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Animated</div>

    <div class="demo-vertical-spacing-sm">
      <p><ngb-progressbar [value]="45" [striped]="true" [animated]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="30" type="secondary" [striped]="true" [animated]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="40" type="success" [striped]="true" [animated]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="20" type="info" [striped]="true" [animated]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="60" type="warning" [striped]="true" [animated]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="80" type="danger" [striped]="true" [animated]="true"></ngb-progressbar></p>
      <p><ngb-progressbar [value]="50" type="dark" [striped]="true" [animated]="true"></ngb-progressbar></p>
    </div>
  </div>
</div>
