// vue-demo-cli2-deprecated/src/components/pages/UsersEdit.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      Edit user <span class="text-muted">#{{userData.id}}</span>
    </h4>

    <b-tabs class="nav-tabs-top nav-responsive-sm">
      <b-tab title="Account" active>
        <b-card-body>

          <div class="media align-items-center">
            <img :src="`${baseUrl}img/avatars/${userData.avatar}`" alt="" class="d-block ui-w-80">
            <div class="media-body ml-3">
              <label class="form-label d-block mb-2">Avatar</label>
              <b-btn variant="outline-primary" size="sm">Change</b-btn>&nbsp;
              <b-btn variant="default md-btn-flat" size="sm">Reset</b-btn>
            </div>
          </div>

        </b-card-body>
        <hr class="border-light m-0">
        <b-card-body class="pb-2">

          <b-form-group label="Username">
            <b-input v-model="userData.username" class="mb-1" />
            <a href="javascript:void(0)" class="small">Reset password</a>
          </b-form-group>

          <b-form-group label="Name">
            <b-input v-model="userData.name" />
          </b-form-group>

          <b-form-group label="Email">
            <b-input v-model="userData.email" class="mb-1" />
            <a href="javascript:void(0)" class="small">Resend confirmation</a>
          </b-form-group>

          <b-form-group label="Company">
            <b-input v-model="userData.company" />
          </b-form-group>

        </b-card-body>
        <hr class="border-light m-0">
        <b-card-body class="pb-2">

          <b-form-group label="Role">
            <b-select v-model="userData.role" :options="{1: 'User', 2: 'Author', 3: 'Staff', 4: 'Admin'}" />
          </b-form-group>

          <b-form-group label="Status">
            <b-select v-model="userData.status" :options="{1: 'Active', 2: 'Banned', 3: 'Deleted'}" />
          </b-form-group>

          <b-form-group>
            <b-check v-model="userData.verified">Verified</b-check>
          </b-form-group>

        </b-card-body>
        <hr class="border-light m-0">
        <div class="table-responsive">

          <b-table :items="userData.permissions" class="card-table m-0">
            <template slot="read" slot-scope="data">
              <b-check v-model="data.item.read" class="px-2 m-0" />
            </template>
            <template slot="write" slot-scope="data">
              <b-check v-model="data.item.write" class="px-2 m-0" />
            </template>
            <template slot="create" slot-scope="data">
              <b-check v-model="data.item.create" class="px-2 m-0" />
            </template>
            <template slot="delete" slot-scope="data">
              <b-check v-model="data.item.delete" class="px-2 m-0" />
            </template>
          </b-table>

        </div>
      </b-tab>
      <b-tab title="Information">
        <b-card-body class="pb-2">

          <h6 class="mb-4">Social links</h6>

          <b-form-group label="Twitter">
            <b-input v-model="userData.info.twitter" />
          </b-form-group>

          <b-form-group label="Facebook">
            <b-input v-model="userData.info.facebook" />
          </b-form-group>

          <b-form-group label="Google+">
            <b-input v-model="userData.info.google" />
          </b-form-group>

          <b-form-group label="LinkedIn">
            <b-input v-model="userData.info.linkedin" />
          </b-form-group>

          <b-form-group label="Instagram">
            <b-input v-model="userData.info.instagram" />
          </b-form-group>

        </b-card-body>
        <hr class="border-light m-0">
        <b-card-body class="pb-2">

          <h6 class="mb-4">Personal info</h6>

          <b-form-group label="Birthday">
            <b-input v-model="userData.info.birthday" />
          </b-form-group>

          <b-form-group label="Country">
            <b-select v-model="userData.info.country" :options="['USA', 'Canada', 'UK', 'Germany', 'France']" />
          </b-form-group>

          <b-form-group label="Languages">
            <multiselect v-model="userData.info.languages" :multiple="true" :options="['English', 'German', 'French']" />
          </b-form-group>

        </b-card-body>
        <hr class="border-light m-0">
        <b-card-body class="pb-2">

          <h6 class="mb-4">Contacts</h6>

          <b-form-group label="Phone">
            <b-input v-model="userData.info.phone" />
          </b-form-group>

          <b-form-group label="Website">
            <b-input v-model="userData.info.website" />
          </b-form-group>

        </b-card-body>
        <hr class="border-light m-0">
        <b-card-body class="pb-2">

          <h6 class="mb-4">Interests</h6>

          <b-form-group label="Favorite music">
            <multiselect v-model="userData.info.music" :multiple="true" :taggable="true" :options="[]" @tag="addMusicTag" placeholder="Add tag" />
          </b-form-group>

          <b-form-group label="Favorite movies">
            <multiselect v-model="userData.info.movies" :multiple="true" :taggable="true" :options="[]" @tag="addMovieTag" placeholder="Add tag" />
          </b-form-group>

        </b-card-body>
      </b-tab>
    </b-tabs>

    <div class="text-right mt-3">
      <b-btn variant="primary">Save changes</b-btn>&nbsp;
      <b-btn variant="default">Cancel</b-btn>
    </div>
  </div>
</template>

<style src="vue-multiselect/dist/vue-multiselect.min.css" />
<style src="@/vendor/libs/vue-multiselect/vue-multiselect.scss" lang="scss"></style>

<!-- Page -->
<style src="@/vendor/styles/pages/users.scss" lang="scss"></style>

<script>
import Multiselect from 'vue-multiselect'

export default {
  name: 'pages-user-edit',
  metaInfo: {
    title: 'User edit - Pages'
  },
  components: {
    Multiselect
  },
  data: () => ({
    userData: {
      avatar: '5-small.png',
      name: 'Nelle Maxwell',
      username: 'nmaxwell',
      email: 'nmaxwell@mail.com',
      company: 'Company Ltd.',
      id: 3425433,
      verified: true,
      role: 1,
      status: 1,

      permissions: [
        { module: 'Users', read: true, write: false, create: false, delete: false },
        { module: 'Articles', read: true, write: true, create: true, delete: false },
        { module: 'Staff', read: false, write: false, create: false, delete: false }
      ],

      info: {
        birthday: 'May 3, 1995',
        country: 'Canada',
        languages: ['English'],
        phone: '+0 (123) 456 7891',
        website: '',
        music: ['Rock', 'Alternative', 'Electro', 'Drum & Bass', 'Dance'],
        movies: ['The Green Mile', 'Pulp Fiction', 'Back to the Future', 'WALL·E', 'Django Unchained', 'The Truman Show', 'Home Alone', 'Seven Pounds'],

        twitter: 'https://twitter.com/user',
        facebook: 'https://www.facebook.com/user',
        google: '',
        linkedin: '',
        instagram: 'https://www.instagram.com/user'
      }
    }
  }),
  methods: {
    addMusicTag (newTag) {
      this.userData.info.music.push(newTag)
    },
    addMovieTag (newTag) {
      this.userData.info.movies.push(newTag)
    }
  }
}
</script>

// angular-demo/src/app/+pages/users-edit/users-edit.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-users-edit',
  templateUrl: './users-edit.component.html',
  styleUrls: [
    '../../../vendor/libs/ng-select/ng-select.scss',
    '../../../vendor/styles/pages/users.scss',
    './users-edit.component.scss'
  ]
})
export class UsersEditComponent {
  isRTL: boolean;

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Edit user - Pages';
    this.isRTL = appService.isRTL;
  }

  languages = [
    { value: 'English', label: 'English' },
    { value: 'German', label: 'German' },
    { value: 'French', label: 'French' }
  ];

  userData = {
    avatar: '5-small.png',
    name: 'Nelle Maxwell',
    username: 'nmaxwell',
    email: 'nmaxwell@mail.com',
    company: 'Company Ltd.',
    id: 3425433,
    verified: true,
    role: 1,
    status: 1,

    permissions: [
      { module: 'Users', read: true, write: false, create: false, delete: false },
      { module: 'Articles', read: true, write: true, create: true, delete: false },
      { module: 'Staff', read: false, write: false, create: false, delete: false }
    ],

    info: {
      birthday: 'May 3, 1995',
      country: 'Canada',
      languages: ['English'],
      phone: '+0 (123) 456 7891',
      website: '',
      music: ['Rock', 'Alternative', 'Electro', 'Drum & Bass', 'Dance'],
      movies: [
        'The Green Mile', 'Pulp Fiction', 'Back to the Future', 'WALL·E',
        'Django Unchained', 'The Truman Show', 'Home Alone', 'Seven Pounds'
      ],

      twitter: 'https://twitter.com/user',
      facebook: 'https://www.facebook.com/user',
      google: '',
      linkedin: '',
      instagram: 'https://www.instagram.com/user'
    }
  };
}

<h4 class="font-weight-bold py-3 mb-4">
  Edit user <span class="text-muted">#{{userData.id}}</span>
</h4>

<ngb-tabset class="nav-tabs-top">
  <ngb-tab title="Account">
    <ng-template ngbTabContent>

      <div class="card-body">

        <div class="media align-items-center">
          <img [src]="'assets/img/avatars/' + userData.avatar" alt="" class="d-block ui-w-80">
          <div class="media-body ml-3">
            <label class="form-label d-block mb-2">Avatar</label>
            <button type="button" class="btn btn-outline-primary btn-sm">Change</button>&nbsp;
            <button type="button" class="btn btn-default btn-sm md-btn-flat">Reset</button>
          </div>
        </div>

      </div>
      <hr class="border-light m-0">
      <div class="card-body pb-2">

        <div class="form-group">
          <label class="form-label">Username</label>
          <input [(ngModel)]="userData.username" type="text" class="form-control mb-1">
          <a href="javascript:void(0)" class="small">Reset password</a>
        </div>
        <div class="form-group">
          <label class="form-label">Name</label>
          <input [(ngModel)]="userData.name" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">E-mail</label>
          <input [(ngModel)]="userData.email" type="text" class="form-control mb-1">
          <a href="javascript:void(0)" class="small">Resend confirmation</a>
        </div>
        <div class="form-group">
          <label class="form-label">Company</label>
          <input [(ngModel)]="userData.company" type="text" class="form-control">
        </div>

      </div>
      <hr class="border-light m-0">
      <div class="card-body pb-2">

        <div class="form-group">
          <label class="form-label">Role</label>
          <select class="custom-select" [(ngModel)]="userData.role">
            <option *ngFor="let i of [[1, 'User'], [2, 'Author'], [3, 'Staff'], [4, 'Admin']]" [value]="i[0]">{{i[1]}}</option>
          </select>
        </div>
        <div class="form-group">
          <label class="form-label">Status</label>
          <select class="custom-select" [(ngModel)]="userData.status">
            <option *ngFor="let i of [[1, 'Active'], [2, 'Banned'], [3, 'Deleted']]" [value]="i[0]">{{i[1]}}</option>
          </select>
        </div>
        <div class="form-group">
          <label class="custom-control custom-checkbox m-0">
            <input type="checkbox" class="custom-control-input" [(ngModel)]="userData.verified">
            <span class="custom-control-label">Verified</span>
          </label>
        </div>

      </div>
      <hr class="border-light m-0">
      <div class="table-responsive">
        <table class="table card-table m-0">
          <tbody>
            <tr>
              <th>Module</th>
              <th>Read</th>
              <th>Write</th>
              <th>Create</th>
              <th>Delete</th>
            </tr>
            <tr *ngFor="let p of userData.permissions">
              <td>{{p.module}}</td>
              <td>
                <label class="custom-control custom-checkbox px-2 m-0">
                  <input type="checkbox" class="custom-control-input" [(ngModel)]="p.read">
                  <span class="custom-control-label"></span>
                </label>
              </td>
              <td>
                <label class="custom-control custom-checkbox px-2 m-0">
                  <input type="checkbox" class="custom-control-input"[(ngModel)]="p.write">
                  <span class="custom-control-label"></span>
                </label>
              </td>
              <td>
                <label class="custom-control custom-checkbox px-2 m-0">
                  <input type="checkbox" class="custom-control-input"[(ngModel)]="p.create">
                  <span class="custom-control-label"></span>
                </label>
              </td>
              <td>
                <label class="custom-control custom-checkbox px-2 m-0">
                  <input type="checkbox" class="custom-control-input"[(ngModel)]="p.delete">
                  <span class="custom-control-label"></span>
                </label>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

    </ng-template>
  </ngb-tab>
  <ngb-tab title="Information">
    <ng-template ngbTabContent>

      <div class="card-body pb-2">

        <h6 class="mb-4">Social links</h6>
        <div class="form-group">
          <label class="form-label">Twitter</label>
          <input [(ngModel)]="userData.info.twitter" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">Facebook</label>
          <input [(ngModel)]="userData.info.facebook" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">Google+</label>
          <input [(ngModel)]="userData.info.google" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">LinkedIn</label>
          <input [(ngModel)]="userData.info.linkedin" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">Instagram</label>
          <input [(ngModel)]="userData.info.instagram" type="text" class="form-control">
        </div>

      </div>
      <hr class="border-light m-0">
      <div class="card-body pb-2">

        <h6 class="mb-4">Personal info</h6>
        <div class="form-group">
          <label class="form-label">Birthday</label>
          <input [(ngModel)]="userData.info.birthday" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">Country</label>
          <select class="custom-select" [(ngModel)]="userData.info.country">
            <option *ngFor="let country of ['USA', 'Canada', 'UK', 'Germany', 'France']" [value]="country">{{country}}</option>
          </select>
        </div>
        <div class="form-group">
          <label class="form-label">Languages</label>
          <ng-select [items]="languages" bindLabel="label" bindValue="value" [multiple]="true" [(ngModel)]="userData.info.languages"></ng-select>
        </div>

      </div>
      <hr class="border-light m-0">
      <div class="card-body pb-2">

        <h6 class="mb-4">Contacts</h6>
        <div class="form-group">
          <label class="form-label">Phone</label>
          <input [(ngModel)]="userData.info.phone" type="text" class="form-control">
        </div>
        <div class="form-group">
          <label class="form-label">Website</label>
          <input [(ngModel)]="userData.info.website" type="text" class="form-control">
        </div>

      </div>
      <hr class="border-light m-0">
      <div class="card-body pb-2">

        <h6 class="mb-4">Interests</h6>
        <div class="form-group">
          <label class="form-label">Favorite music</label>
          <tag-input [(ngModel)]="userData.info.music"></tag-input>
        </div>
        <div class="form-group">
          <label class="form-label">Favorite movies</label>
          <tag-input [(ngModel)]="userData.info.movies"></tag-input>
        </div>

      </div>

    </ng-template>
  </ngb-tab>
</ngb-tabset>

<div class="text-right mt-3">
  <button type="button" class="btn btn-primary">Save changes</button>&nbsp;
  <button type="button" class="btn btn-default">Cancel</button>
</div>
